### ISSUE TITLE
The bigger allowed orbit in the second screen needs to fit in the play area with the last zoom-out 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#10]
The second screen of the simulation is for comparing elliptical orbits and measuring, which means that the user needs to get a full view of the orbits that are allowed:

This is the simulation now:
![image](https://user-images.githubusercontent.com/26031501/178345326-58a94d39-3388-4fe5-a9af-c09e700b11ac.png)

the allowed orbits (not doted line) need to fit in the play area white rectangle in the picture):
![image](https://user-images.githubusercontent.com/26031501/178345705-01570719-a303-4d69-9701-01a3d9723c23.png)

**Comment by AgustinVallejo** [comment]
This one needs discussion, because it was said that the orbit that needed to fit was the biggest one when changing the initial separation. However, the biggest possible orbit when changing velocities is going to be WAY bigger, and we'd need to adjust the zoom levels accordingly.

**Comment by DianaTavares** [comment]
In the design meeting was discussed this issue, and we agreed to leave it the way it is.
