### ISSUE TITLE
Finalize credits for 1.2 publication

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#101]
For https://github.com/phetsims/my-solar-system/issues/88

**Comment by samreid** [comment]
What else needs to be done here?

**Comment by arouinfar** [comment]
Looks like we need to finalize QA credits, which will happen during RC.

I noticed that the `ó` in López and `í` in Agustín aren't using the unicode escape sequence, and they probably should be.

Here's an [example](https://github.com/phetsims/density/blob/master/js/density-main.ts#L19) of how Diana is usually credited with `\u00f3` in place of `ó`. If we decide to change things `\u00ed` is the sequence for `í`.

**Comment by arouinfar** [comment]
@KatieWoe said the QA testers in the most recent dev test were:
> Me, Nancy, Jaron, Martin

Everyone except for Martin was already credited, so I added him in the above commit.

**Comment by DianaTavares** [comment]
@kathy-phet noticed that we also need to credit Michael Dubson, the original designer of MSS. Like Geometric Optics, his name can go with mine in the Lead Design section. 

Is someone else from the Flash work that needs to be added to the credits? @arouinfar you have more experience with this converted sims. Thanks!!

**Comment by arouinfar** [comment]
Tagging https://github.com/phetsims/qa/issues/935 so we don't forget to confirm QA credits for rc.1 testing.

**Comment by zepumph** [comment]
Cherry picked.

**Comment by zepumph** [comment]
QA can you give us the QA credits if you are ready for them?

**Comment by KatieWoe** [comment]
No additions are needed at this time.

**Comment by zepumph** [comment]
Sounds great. If you do, please open a new issue, we are going to proceed with RC spot check now.

**Comment by kathy-phet** [comment]
@DianaTavares - Just to confirm that it was only Michael Dubson on the Flash version.
