### ISSUE TITLE
Interactive Description

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#103]
Hello! You can include in this issue all the descriptions that are ready so that we can be adding them to the sim.

**Comment by zepumph** [comment]
>You can include in this issue all the descriptions

To be clear, my understanding is that we are adding accessible names for components, and possibly some state descriptions. We are not working on interactive and responsive descriptions for this release. Is that correct?

**Comment by AgustinVallejo** [comment]
@zepumph Yes, that's correct. It's just the initial static description. According to @emily-phet it's about "5% of the full description but it's good practice"

**Comment by emily-phet** [comment]
@zepumph Adding on to @AgustinVallejo's comment - We were planning to add static state descriptions. It might be worthwhile since you're helping Agustin to at least share how you would make something in the state descriptions dynamic.

**Comment by samreid** [comment]
From today's standup. This is a high priority issue so we can get ready for dev testing.  @Matthew-Moore240 said these just need a bit of updates. Maybe could get it done today.

**Comment by Matthew-Moore240** [comment]
@AgustinVallejo Here are the static state descriptions for My Solar System

**Here is screen 1**

H1: My Solar System: Intro Screen(Screen 1)

{{My Solar System}} is an interactive sim. It changes as you play with it. It has a Play Area and a Control Area.

The Play Area is an observation window showing a scene with two planetary bodies. Experiment with the mass, velocity, location and direction of the two planetary bodies.

In the Control Area, there are options to add a grid and a measuring tape. You can also toggle on or off the path and values of your planetary bodies and also check their center of mass. The Control Area has options for how fast the action happens in the observation window including buttons to pause and step forward. 

**Here is screen 2**

H1: My Solar System: Lab (Screen 2)

{{My Solar System}} is an interactive sim. It changes as you play with it. It has a Play Area and a Control Area.


The Play Area is an observation window showing a scene with many options to set up your own experiments. Recreate our own Sun and earth or make up your own solar system.


In the Control Area, there are options to view and change the area of the orbit and options to adjust and view orbital information. You can choose premade planetary alignments or choose your own, along with a Zoom in and out option. The Control Area has options for how fast the action happens in the observation window including buttons to pause and step forward.

**Comment by zepumph** [comment]
Awesome! That is excellent. Thanks! @AgustinVallejo, Please use `setScreenSummaryContent` to set the screen summary content. For example in https://github.com/phetsims/ratio-and-proportion/blob/b0d613facad0c3312708b4b21886fe087bc3fd47/js/discover/view/DiscoverScreenView.ts#L68

Please let me know if you want to discuss further. The Ratio and Proportion content has dynamic content that needs to listen to model variables to update, so I believe this will be quite a bit more simple. Good luck!

**Comment by samreid** [comment]
> Please use setScreenSummaryContent to set the screen summary

@AgustinVallejo and I implemented it before reading the preceding comment, so we put it in `screenSummaryContent` constructor options.  Is that OK?

I also set the intro strings in the 2nd commit (bad commit message).

**Comment by samreid** [comment]
I got the a11y view showing, but I don't think I'm doing it right. I don't see other sims using that method.

**Comment by samreid** [comment]
I got the a11y view showing, but I don't think I'm doing it right. I don't see other sims using that method.

**Comment by samreid** [comment]
I got the a11y view showing, but I don't think I'm doing it right. I don't see other sims using that method.  Will need more time..

**Comment by samreid** [comment]
I got the a11y view showing, but I don't think I'm doing it right. I don't see other sims using that method.

**Comment by samreid** [comment]
I got the a11y view showing, but I don't think I'm doing it right. I don't see other sims using that method.  Will need more time..

**Comment by samreid** [comment]
@Matthew-Moore240 can you please check the behavior in the sim?  It currently looks like this:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/679486/225699326-de6510dd-0c36-4224-b5ed-c7f8fb8f479b.png">

**Comment by zepumph** [comment]
Today we had a design meeting to confirm the interactive description feature set for this MSS publication:

- Full alt input (added keypad, and draggable bodies, vectors, measuring tape)
- Screen summary
- Accessible Names
- No other portions of state descriptions (extra headings or help text or extra PDOM content)
- No response description

**Comment by zepumph** [comment]
Designers signed off, I'll review the implementation.

**Comment by zepumph** [comment]
https://github.com/phetsims/my-solar-system/commit/8e65bd2ea58cac0505450cd0c5d8c1a0ae829994 is excellent. Sorry to confuse about `setScreenSummaryContent`.

I'm ready to close this issue. Thanks all!
