### ISSUE TITLE
keyboard number input should auto work when mouse opens KeypadDialog

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#106]
From https://github.com/phetsims/my-solar-system/issues/86 and @samreid and @zepumph's thoughts. Let's have this behavior work like so:

1. Click the number display with a mouse which opens a dialog
2. Pressing numbers on the keyboard will then input into the keypad.

**Comment by zepumph** [comment]
@jessegreenberg, this was really quite straight forward, but would you spot check me to see if you have any improvements?

**Comment by AgustinVallejo** [comment]
Looking really good on our side!!

**Comment by jessegreenberg** [comment]
Code change looks good!
