### ISSUE TITLE
Memory Test and fix Memory Leaks

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#108]

**Comment by samreid** [comment]
Testing procedure:
* Pull all
* `grunt --brands=phet --minify.mangle=false`
* launch http://localhost/main/my-solar-system/build/phet/my-solar-system_en_phet.html?debugger&fuzz

Then to record a snapshot,
* Pause fuzzing with `phet.chipper.queryParameters.fuzz = !phet.chipper.queryParameters.fuzz;`
* Press reset all on each screen
* Go to screen 1
* Memory snapshot

These snapshots are 5 minutes apart after a 5-minute warmup. All the deltas look like noise:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/679486/225332236-239f6bc9-718e-4d3e-82f3-08f1ece97755.png">

So it looks like there is not currently a memory leak.  But it is easy to introduce a memory leak while working on other issues, so this should be double checked right before dev test.

**Comment by AgustinVallejo** [comment]
Ran memory tests again and looking good!
