### ISSUE TITLE
Improve bodiesEscapedProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/my-solar-system#112]
From a review comment in https://github.com/phetsims/my-solar-system/issues/95, we should improve `bodiesEscapedProperty`. 

* Rename it to `isAnyBodyEscapedProperty`
* Update the documentation
* Change it to a DerivedProperty.or
* Eliminate manual resets (should happen automatically)

**Comment by samreid** [comment]
Fixed, @AgustinVallejo please review.  The most concerning part is how the manual reset behavior was changed, so that should be carefully reviewed/tested.

**Comment by AgustinVallejo** [comment]
Thank you @samreid
