### ISSUE TITLE
Adding sounds to vectors and pickables

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#113]
After a discussion on https://github.com/phetsims/my-solar-system/issues/107 we asked EM and she said: 

> It’s ideal to have a pickup/drop sound for every object that you “pick up”. Since this sim has many pickup-able objects, we might want to have some different variants of the pickup/drop sound.

So we have to decide on:

- [x] Will picking up a Velocity Arrow make a different sound than picking up a planet?
- [x] Should the keyboard interaction sound on focus/unfocus or on start/end key presses?
- [x] If the former, the unfocusing sound goes at the same time as the next focusing sound, is this ok?

**Comment by emily-phet** [comment]
First question:
- I think it would be good to hear the one pick up/drop sound set for all (let's call that pick up/drop sound set A), and then if needed, swap out for the velocity vectors only sound A for a sound B (@Ashton-Morris can create a slightly different sound as an option). This is the kind of thing that needs to be felt out, if it "feels" fine when you play with the sim on a tablet device, with a mouse, and using focus that one pickup/drop sound set for all is great, that's the simplest to move forward with. I anticipate though, that it might feel a bit off, so the second sound for vectors would be the next thing to try. If it still feels off, then we might need a different sound for each object in a sim, in that case Ashton would need to create a large set of related pickup/drop sounds (maybe like 20 to cover a wide range of sim scenarios). 

For the second question: the sounds should not occur on focus, it should be on action to actually move the object. You can navigate focus to an object without interacting with it, so it shouldn't sound like you've picked it up.

**Comment by AgustinVallejo** [comment]
I think having the same grab/drop sound for bodies and vectors works well, marking ready for review.

**Comment by AgustinVallejo** [comment]
With @arouinfar we decided this is reasonable, closing!

**Comment by AgustinVallejo** [comment]
@Ashton-Morris if you feel vectors should sound different, feel free to open, and we can implement it in next version :)
