### ISSUE TITLE
What to do with cueing arrows?

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#115]
@DianaTavares and @AgustinVallejo have decided that cueing arrows should not be on by default in the sim, but they are still usable with a query parameter: `?cueingArrows=true`. 

During code review today, @samreid  @AgustinVallejo @jonathanolson and I ran into changes to be made in that file, and I was interested in why they are needed if we aren't going to have cueing arrows in the sim? I know the query parameter was useful during interviews, but now that it has been decided, should we remove the cueing arrows from the sim? I am not too involved in MSS design decisions though, so over to the leads.

**Comment by zepumph** [comment]
If we keep it, then it should be because users will want to be able to have them. In that case, we will want to make sure to mark it as a `public` parameter, and likely include it in teacher tips.

**Comment by DianaTavares** [comment]
I used them in one interview, and I didn't like it the result of it. In the other interviews I hide them, and the interaction with the simulations has a better flow that supports student interpretations. I think it is something that we can just delete. I don't see them as something that users are going to use.

**Comment by samreid** [comment]
Thanks, I'll delete them.

**Comment by samreid** [comment]
Removed, closing.
