### ISSUE TITLE
Layout work to be done with ?stringTest=long

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#118]
![image](https://user-images.githubusercontent.com/6856943/225981531-2386a249-70b2-49b5-8886-9df8c88b664b.png)

**Comment by zepumph** [comment]
I think a large portion of this problem is actually the maxWidth for the InteractiveNumberDisplay columns heading. That pushes so much over to the right. 

Let me know if you want more help.

**Comment by zepumph** [comment]
We fixed a max width in the FullDataPanel and it helped a lot. I think we are done here because I can't get the resetAllButton to be covered again. Anything else here @AgustinVallejo?

**Comment by AgustinVallejo** [comment]
Seems to be correct, thanks!
