### ISSUE TITLE
Mass => radius not monotonically increasing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#120]
Looking at the mass => radius function (Body.massToRadius), it looks like the following (x-axis mass, y-axis radius):

<img width="403" alt="image" src="https://user-images.githubusercontent.com/480878/226077360-e0fc5871-ad1a-4449-bc63-2299797298cf.png">

Is this by design? Additionally, it's a bit weird to have 1.7 + something proportional. Can we just model this with a pure `Math.max( c * Math.pow( mass, 1 / 3 ), minRadius)`, so that it (a) doesn't have the discontinuity/non-monotinicity, and (b) above a certain value, is modeled accurately?

**Comment by AgustinVallejo** [comment]
You're right, it did seem a little weird, pushed a change. Please review :)

**Comment by jonathanolson** [comment]
Looks great to me, thanks!
