### ISSUE TITLE
Return bodies results in unexpected configurations

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#121]
Start in lab screen, select hyperbolic:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/480878/226078526-ab39323b-b0ad-4e76-806a-28df2bed808e.png">

Hit play until all bodies are off, then pause:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/480878/226078545-9b9220db-af9c-4cd7-9062-dd85ec9fefa6.png">

Click return bodies:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/480878/226078560-d373bdfc-8d67-47c8-88ae-fe0b71c6627a.png">

This are already off, and trace out this pattern, while saying it's the hyperbolic preset:

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/480878/226078582-aa23826e-fcf9-4614-aff9-745d08c6797d.png">

**Comment by AgustinVallejo** [comment]
Pushing changes to address this. Please let me know how it looks.

**Comment by jonathanolson** [comment]
Better, but now let only one go off screen, pause, and return bodies. It switches to a weird configuration. I'd presume this should switch it to "custom", no? (How should that work?)

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/480878/226221189-35360b43-44e1-4195-b38c-4a65dd745d9e.png">

**Comment by jonathanolson** [comment]
I guess before I review more of this, I'm curious what the expected behavior should be in these cases.

**Comment by AgustinVallejo** [comment]
With @samreid, @arouinfar and @zepumph we decided that this logic has a bunch of corner cases and what the sim does is good. Regarding the last image you posted, what happened is that one body escaped the screen before the others, so when you press the button, only that one returns. But it's expected behavior. If you let all the bodies escape, they would all return together.
