### ISSUE TITLE
Time "Clear" button disables the rewind button, but the rewind button doesn't rewind to the new "0" time

### ISSUE THREAD

**Issue by samreid** [phetsims/my-solar-system#122]
While working on #86, @zepumph and I observed that the Clear button disables the rewind button, but the rewind button doesn't rewind to the new "0" time.  What should the behavior be?

![Kapture 2023-03-20 at 13 19 09](https://user-images.githubusercontent.com/679486/226443874-226fad55-3a64-4da7-af3a-d25667099f2d.gif)

**Comment by arouinfar** [comment]
@AgustinVallejo asked me to take a look at this on Slack and said:

> We have two options:
> 1. Same as GaO: If you clear the time and then press restart you still go back to the last restartable state.
> 2. When you press 'clear', set the new restartable state right there.
>
>I like 2 better but it makes sense to do the same as GaO

I think it would be confusing to create a new saved state when pressing Clear, so I would go with option (1) and keep consistent with GAO.
