### ISSUE TITLE
"Follow center of mass” button is active and shouldn't in the initial state of the lab screen

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#124]
When the user opens for the first time the Lab screen, the “Follow center of mass" button is there, and is there in all the pre-sets. The button needs to appear until the user changes one of the variables that modify the initial state. 

Moreover, I feel that it is very low on the screen. I recommend moving it closer to the play area, aligned with the info button.

![Screenshot 2023-03-21 at 6 51 00 p m](https://user-images.githubusercontent.com/26031501/226774015-38d38a9d-f2ec-4c04-802d-accec1467142.png)

**Comment by AgustinVallejo** [comment]
![image](https://user-images.githubusercontent.com/37052186/226976328-33e27309-b51d-4397-9a14-29c82a044a9a.png)
Regarding the position of the button, translation and max width won't let us put it higher. 

Marking this ready for review, if it seems ok, please close.

**Comment by DianaTavares** [comment]
Now I entered directly in Lab, and yes! The button is not there! 
But when I select any other pre-set, the button appears. I understand that the center of mass of the systems shown in the pre-sets are not in the center of the play area because we put the object in places that make visible the trajectory. That should be the reason that makes the button appears.  Is there a way to not show the button when a pre-set is selected? 

In the way it is now, I feel that 1) students click the button, then it is an extra click to see the trajectory of the pre-set, or 2, like that button is always there, it don't bring the attention of the user when she/he modify the system.

**Comment by AgustinVallejo** [comment]
I believe this is fixed now, please check!

**Comment by DianaTavares** [comment]
It works perfectly!!
