### ISSUE TITLE
Add the “return body” button when an object crashes. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#125]
During today's interview, I noticed that the user can lose one (or more) bodies when they crash, move one of the objects that continue in the play area, and want to return the lost bodies with the play panel. Probably this is more of an issue in the intro screen because the Lab screen has the number spinner for the bodies, but I recommend to also showing the “Return bodies” button when one of the objects crashes. When the user activates that button, the bodies that crash can come back to the play are in the last initial state.

**Comment by AgustinVallejo** [comment]
I don't think this it's worth the time. First, GaO doesn't do it, as the user can rely on the restart or reset button easily; in the case of Lab even the number of bodies spinner. Also, the property behind the bodies escape is very much linked to screen escape, so I'm not sure if the seemingly small effort can turn into something longer.

Please close the issue if you agree and this can remain as it is (When bodies crash, the return bodies button wont appear)

**Comment by DianaTavares** [comment]
Ok!
