### ISSUE TITLE
Use numbers as another way to call bodies in the simulation 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#126]
During today's interview, I noticed that the student had problems identifying the bodies when I made reference to them by their color. We test for color blindness, then all the objects are well distinguished, but it was hard for the student to identify which body I was making reference to when I asked him to move the “Pink” body.  Colors are the only way to differentiate the bodies in the sim at this moment.

He recommended adding labels, like numbers when the speed is displayed (for example, v1=# km/s). I like that idea! @AgustinVallejo, can you implement it?  I know that in the lab we can have v1, v3 and not v2 because the pink planet crashed, but I think it is ok:
![image](https://user-images.githubusercontent.com/26031501/226775884-48496342-125d-490e-a465-d43c5fefe6f3.png)

Also, we can use the way collision lab use numbers to differentiate objects by adding a number inside the circles in the mass control:
![image](https://user-images.githubusercontent.com/26031501/226776217-4873163a-5140-457a-96bd-4e052c07d285.png)

for that @AgustinVallejo, you need to make the circles in the mass panel a little bigger, but it has space:

![image](https://user-images.githubusercontent.com/26031501/226775840-16b84740-4925-4a0b-a71f-094ee62f5b81.png)
 
We cannot add the number in the bodies because they can be tiny (different from Collision Lab). But I think that at least with the number, the match color for the body in the mass panel, and the object in the play area is better than the way we have it now. Or do you have any ideas @arouinfar?

**Comment by AgustinVallejo** [comment]
![image](https://user-images.githubusercontent.com/37052186/227052938-84a58f64-c375-4846-8052-cecfa4f342a6.png)
Looking like this. Closing.

**Comment by DianaTavares** [comment]
What about the idea of using v1, v2, etc. when the speed is active to also have some kind of reference to the body in the play area?

**Comment by AgustinVallejo** [comment]
What about V<sub>1</sub>, V<sub>2</sub>...

**Comment by AgustinVallejo** [comment]
![image](https://user-images.githubusercontent.com/37052186/227074687-d79069b3-9b80-4f43-8035-e72345e7a13d.png)
This is how it'd look

**Comment by DianaTavares** [comment]
Yeah!! Thanks Agustin!!  I think that this is the most that we can do to support differentiation of the bodies. Closing!
