### ISSUE TITLE
Should we apply drag bounds to the DraggableVectorNodes?

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#129]
Discovered while reviewing https://github.com/phetsims/my-solar-system/issues/86, we were interested in how you can drag the vector outside the drag bounds. But in general we are torn about if we should add it, and need some design help.

Case for adding dragBounds:
* I feel like it is likely QA would open an issue about this during testing. (a metric for bugginess)
* With the keyboard there is no limit to how far outside of the drag bounds you can move the vector nodes. This seems distracting and something that a young learner could easily get carried away with.

Case for not adding dragBounds:
* Similar to the measuring tape, when you are dragging the planet (or measuring tape base), it is likely better to keep the vector the size it is, no matter where the planet is. I wouldn't want it to be hard to reproduce actually important body arrangements because the vectors get "cut off" by the edge of the dragBounds, and are forced to decrease. For example:
![image](https://user-images.githubusercontent.com/6856943/226993431-f900606a-786a-4fc3-9ce3-07ca7c580219.png)

**Comment by arouinfar** [comment]
@jonathanolson the drag behavior of the planets is looking really nice!

**Comment by veillette** [comment]
Great Work. Sorry to high jack this issue but you can move an object without dragging it. On the `lab` screen, with `more data` toggled on, it is possible to put a body under the main panel if you set it x-position to 8.
