### ISSUE TITLE
Renaming Scale Gravity Vector and adding a Note in the Unit Info

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#132]
I had today an interview with a high school student, and She uses the scale gravity control, thinking that it increases/decreases the gravity. I explained to her what “scale” means and what the slider was doing, and she understand immediately (also the text message makes essay my explanation).

I just think that it can be common confusion for the public of the simulation (High school and intro to university). “Scale” can be hard to interpret and needs teacher support.

KP suggested changing it to "Zoom". I like this suggestion!! 

Also, I think we can add something to the Units Information window: 
![image](https://user-images.githubusercontent.com/26031501/227384422-b5c88981-21fb-41ae-ba31-e00577b488e2.png)

Note 3: The Gravity force vector is just a qualitative visualization. It doesn't include values or units.  The range of sizes of the vector is huge for the masses and distances allowed in the simulation. Use the zoom below the Gravity Force control for a better visualization of the vectors. 

@AgustinVallejo, what do you think about the renaming and the Note3? Please review the wording of the note.

**Comment by AgustinVallejo** [comment]
![image](https://user-images.githubusercontent.com/37052186/227627195-83d81b15-cdac-41b6-840c-618b4f4640f7.png)
Looking like this, please review and close if done

**Comment by arouinfar** [comment]
@AgustinVallejo @DianaTavares how about:

> Due to the large range of values in the simulation, the gravity force vectors may sometimes be too small to display. The gravity force vectors can be rescaled with the zoom control.

**Comment by DianaTavares** [comment]
I like it!

**Comment by jonathanolson** [comment]
Implemented the above two items, can you verify?

**Comment by arouinfar** [comment]
Thanks @jonathanolson. Looks good in master, closing.
