### ISSUE TITLE
Adding an extra decimal 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#133]
We know that several teachers have already labs with the Flash MSS. To reproduce the setups in the old simulation, the HTML5 versions need to accept a second decimal for the Position and velocity variables. 

I don't think mass need this.

**Comment by AgustinVallejo** [comment]
Done! Please review and close if it looks okay

**Comment by DianaTavares** [comment]
It looks wonderful! 
But… now that I am playing with it, it takes time to set the vector to a specific value by dragging. I think that people that drag vectors are not interested in super specific two decimal values. Then I suggest to snap (I think that is the word) the dragging of the vector to jumps of 1.

**Comment by DianaTavares** [comment]
We decide that only position needs 2 decimals because with the zoom in needed. Velocity doesn't need 2 decimals. My request of snapping vector to integer values is hard to implement, and if users need a specific value, they can use the number kay pad.
