### ISSUE TITLE
Sound balancing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/my-solar-system#137]
With the exception of #136, all sounds have been implemented and finalized. We'll soon be ready for the final sound mixing to balance the volume. Assigning to @Ashton-Morris

**Comment by Ashton-Morris** [comment]
Working on #136 https://github.com/phetsims/my-solar-system/issues/136#issuecomment-1502606608 mixing will be next.

**Comment by Ashton-Morris** [comment]
- On the **Lab** screen I don't think we need the button click sound and then the number of bodies sound for those **up and down arrows that say Bodies**. I think just the number of bodies sound will work on its own.

- The Bodies colliding sound should go up 15% or perhaps add a little audio ducking when that takes place. It hard to hear when other things are going on.

I think the levels sound good other than that! Sometimes it can get loud when there are four going and there is high velocity but I think that is part of the point.

**Comment by AgustinVallejo** [comment]
Regarding the number spinner change, I spoke with @jbphet and he told me we should do the following:

- [ ] Modify NumberSpinner to include an option for arrowButtonSoundPlayer.

Will work on it shortly, commenting to keep track of it.

**Comment by AgustinVallejo** [comment]
@jbphet Could you please look at the above issue for review of the changes in NumberSpinner? @samreid and I were wondering what happens if in the future somebody wants a different sound for each arrow?

**Comment by AgustinVallejo** [comment]
@Ashton-Morris can you please confirm if the 15% increase sounds good?

**Comment by Ashton-Morris** [comment]
I will review this Tue morning when I get back in my studio.

**Comment by jbphet** [comment]
> @jbphet Could you please look at the commit below (https://github.com/phetsims/sun/commit/814999a9c3109a2adb8d43dbf9d0c95a5ad55112) for review of the changes in NumberSpinner? @samreid and I were wondering what happens if in the future somebody wants a different sound for each arrow?

I think it would be a good idea to support different sounds for each arrow.  I'd suggest doing something like the piece of musical gear that I pasted a screenshot for below, where you use one sound if only one is provided, and use both if both are provided.

![image](https://user-images.githubusercontent.com/3082831/232578517-0378f8b3-32ff-442f-a7b0-b8341b2e7fed.png)

**Comment by Ashton-Morris** [comment]
@AgustinVallejo It is still sounding too quiet to me. Can you add another 20% for the  **Bodies colliding sound**.

**Comment by Ashton-Morris** [comment]
I heard it and I think it sounds great. Closing
