### ISSUE TITLE
"Some force vectors..." message appears with large vectors

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#140]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/927, the "Some force vectors are too small to display" message appears on the screen when large vectors are present. This is seen when the Play button is pressed and not when the sim is paused.
 
**Steps to reproduce**
1. On either screen, press Play
2. Check the Gravity Force checkbox
3. Move the Gravity Force slider to the right

**Visuals**
<img width="1177" alt="Screenshot 2023-04-06 at 10 56 31 AM" src="https://user-images.githubusercontent.com/87318828/230431127-dd14a669-2d8f-4860-96fa-a798fbcf250b.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.9/phet/my-solar-system_all_phet.html
Version: 1.1.0-dev.9 2023-04-05 16:58:00 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language: en-US
Window: 1435x773
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
I think this is fixed now, can you verify and close @Nancy-Salpepi ?

**Comment by Nancy-Salpepi** [comment]
The message still pops up when the vectors are very small, but still visible. Is that OK @AgustinVallejo @DianaTavares?
<img width="365" alt="Screenshot 2023-04-10 at 7 52 57 AM" src="https://user-images.githubusercontent.com/87318828/230897015-c53bf200-5e86-4deb-9bc4-2cf8df63787b.png">

**Comment by AgustinVallejo** [comment]
10/04 with @arouinfar, @DianaTavares and @samreid: The threshold seems at a good place. Vectors are visible but not that noticeable, so the message still applies.
