### ISSUE TITLE
Missing interactive highlights for some objects

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#141]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/927, the bodies and velocity vectors are missing interactive highlights for the mouse. 

**Steps to reproduce**
1. Turn on interactive highlights
2. Hover over bodies and velocity vectors

**Visuals**
Here is a video showing the objects missing interactive highlights (first moving my mouse, and then using Tab)

https://user-images.githubusercontent.com/87318828/230475223-530e2c95-8d29-4e48-9508-43d06027c3a4.mp4

**Comment by samreid** [comment]
I was able to reproduce the same problem, using `&interactiveHighlightsInitiallyEnabled`

**Comment by samreid** [comment]
`onPointerFocusChange` is being called for other nodes but not for BodyNode or the velocity.  @jessegreenberg likely has expertise in this area.

**Comment by jessegreenberg** [comment]
Hey there! Information about instrumenting for Interactive Highlights can be found at interactive-highlights-quickstart-guide.md. Those components likely need to make use of InteractiveHighlighting.ts or InteractiveHighlightingNode.ts.

If you have any questions or would like to quickly pair on this together, feel free to reach out any time next week.

**Comment by AgustinVallejo** [comment]
Thanks @jessegreenberg for sharing the document, this should be fixed now. However, I'm not sure if the way I implemented it  is correct in one place: For the draggable vector the dragListener is on a Path constant. To add interactive highlights I created a class called InteractivePath and replaced the new Path, as you can see here: https://github.com/phetsims/solar-system-common/commit/f17ffa3240e608eb0977f93a21a6f7ab2905e98e#diff-912a31ebd4d8da51db8db8f7aa959c83942c9c51c34289e7c869e4d3214027b0

Would that be okay? Is there a better way? I'm open for pairing on this.

**Comment by jessegreenberg** [comment]
Those changes look good @AgustinVallejo and its working well from what I can see, well done! Making an inner class for the Path seems reasonable.

One potential thing - UI components that use InteractiveHighlighting may need disposal if they are every destroyed. I forgot about this in the quick start guide, I added a note about it.

**Comment by samreid** [comment]
> One potential thing - UI components that use InteractiveHighlighting may need disposal if they are every destroyed. 

In ValuesColumnNode, it creates `InteractiveNumberDisplay`. Should those every be `disposed` (I can't see if they are already disposed or not).

Here's a patch that disposes the InteractiveHighlight in DraggableVectorNode:

```diff
Subject: [PATCH] Dispose
---
Index: js/view/DraggableVectorNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/view/DraggableVectorNode.ts b/js/view/DraggableVectorNode.ts
--- a/js/view/DraggableVectorNode.ts	(revision 516a2d96832e7b18a29add41ddf329fbcede1ab0)
+++ b/js/view/DraggableVectorNode.ts	(date 1681142885289)
@@ -180,8 +180,8 @@
       dragListener.dispose();
       keyboardDragListener.dispose();
       vectorPositionProperty.dispose();
+      grabArea.dispose();
     } );
-
 
     // For PhET-iO, when the node does not support input, don't show the drag circle
     const onInputEnabled = ( inputEnabled: boolean ) => {
```
