### ISSUE TITLE
How to deal with sim after collision on Intro Screen

### ISSUE THREAD

**Issue by veillette** [phetsims/my-solar-system#143]
For https://github.com/phetsims/qa/issues/927

Test device
Dell XPS 15

Operating System
Windows 10

Browser
Chrome

Problem description

On `Intro` screen, the sim is somewhat useless after a collision.

From your very naïve fill-in  QA here, I found that after a collision, there is only one body left moving steadily and there is not much to do at this point. I am more or less forced to press the reset all button to recover a second object. However, the reset all button resets all the controls (center of mass, path, grid, measuring tape) which I didn't want to reset.

@stemilymill demonstrated to me how one can recover the second body by pressing the rewind button, which preserve all the other control panel settings and recover the second body. It does everything I wanted, expect that it is not very intuitive. (hence this issue)  I'll note that Gravity-and-orbits has a more iconic "scene rewind" button 
![image](https://user-images.githubusercontent.com/7633344/230653942-e4488742-9661-4ded-a72a-7db1d7bd9e86.png)
which I found clearer.

This is somewhat related to #139.

**Comment by veillette** [comment]
I labelled it as a bug although it could be potentially be addressed in teacher-tips, etc.

**Comment by veillette** [comment]
I forgot @DianaTavares. Assigning to her as well.

**Comment by samreid** [comment]
We discussed this in design meeting today, and I don't recall the decision, but I think @AgustinVallejo does. Assigning him.

**Comment by arouinfar** [comment]
Thanks for reporting @veillette. There are definitely some severe usability issues in the current implementation, especially on the Intro screen. The design team talked through many options and scenarios, and settled on the behavior described in #147.

>1. 'Return bodies' appears either when there's a natural collision or a body escapes the screen.
>2. On Intro screen, if a body is destroyed or escapes, we will no longer save body states upon interaction. This is because you would be rewinding to a sim with just one body, which doesn't do much.
>3. When pressed, 'Return bodies' behaves as a rewind.

Collisions will now trigger the Return Bodies button, which restores the most recent rewind state. However, on the Intro screen, manual collisions will not trigger a new saved rewind state. That means that pressing Return Bodies/Rewind will take users back to the most recently saved configuration with two bodies. 

We considered adding a minor rest button, similar to the one in Gravity and Orbits, but ultimately decided against it for a few reasons.
* It's strange UX to add a control to one screen, but not the other. A minor reset button could work nicely in Intro, but it becomes complicated in Lab. Making any change to a preset system will automatically switch you to the "Custom" scene. What state should the minor reset restore? Should it restore the default values of "Custom" or should it take you back to the most recent preset?  We would have to make a lot of assumptions about the user's intentions. Presets can also be restored by selecting them from the ComboBox.
* Where would we put a minor reset button so it is noticeable? There are already so many buttons in this sim, and adding another would create some clutter. There are also alt input considerations to make too.

The remaining work is being tracked in #147, so I'm going to close this issue.
