### ISSUE TITLE
Center of Mass button appears when using Zoom buttons

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#148]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.2.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/927, on both screens: Every time I press a zoom button the Center of Mass button appears on the screen. Pressing this button the first time, re-centers the bodies. Pressing it any other time, appears to do nothing. 

**Steps to reproduce**
Here is an example:
1. On the Intro Screen, press the zoom in button
2. Press Center of Mass button-- the bodies recenter
3. Press the zoom out button twice
4. Press Center of Mass button-- nothing appears to change

**Visuals**

https://user-images.githubusercontent.com/87318828/230988271-bea48789-380e-422f-93c4-d345c4b407a4.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.9/phet/my-solar-system_all_phet.html
Version: 1.1.0-dev.9 2023-04-05 16:58:00 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1508x773
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
@jonathanolson and I observed this code: https://github.com/phetsims/solar-system-common/blob/7523089f5c92ec924b6b0235f69c253777878e3a/js/view/SolarSystemCommonScreenView.ts#L221-L223

This sets the model to be userControlled=true any time the model view transform changes.  We were surprised to see it.  @AgustinVallejo can you please comment?

**Comment by AgustinVallejo** [comment]
Thanks for noticing, it was there to disable the CueingArrowsNode at first, shouldn't be there now. Pushing changes.
