### ISSUE TITLE
"Some force vectors..." statement blocked by combobox with stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#149]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/927, with stringTest=dynamic, when the Return Bodies button is on the screen, the "Some force vectors..." statement extends behind the combobox. 

**Steps to reproduce**
1. Add ?stringTest=dynamic to url
2. On either screen, check Gravity Force and decrease Zoom to x10^-2
4. Arrange bodies so that 1 will move off screen and press play
5. Once the Return Bodies button appears, press the right arrow a couple of times

**Visuals**
<img width="812" alt="Screenshot 2023-04-11 at 9 36 15 AM" src="https://user-images.githubusercontent.com/87318828/231182939-6e472361-778a-4113-86df-5832600eb958.png">

**Comment by samreid** [comment]
I adjusted the maxWidth, after the change the worst case scenario looks like this:

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/679486/231190195-b44f4912-3f23-4e3f-8dcb-6d898f62c88e.png">

Committing shortly.

**Comment by samreid** [comment]
Fixed, @Nancy-Salpepi can you please test/verify on phettest?

**Comment by Nancy-Salpepi** [comment]
This looks good @samreid!

**Comment by samreid** [comment]
Thanks! Closing.
