### ISSUE TITLE
Make the panels on the edges float

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#15]
I am not very sure that the word is "float," but I mean that if the user modifies the size of the simulations, the penalties always move to the edges. At this moment, if I modify the screen, the panels are fixed:
![image](https://user-images.githubusercontent.com/26031501/187308948-5abf098e-1b77-4b28-80c2-cdb5c45a4b41.png)

But we  can have more play area if the panels move like other sims, like Density or build a circuit: 
![image](https://user-images.githubusercontent.com/26031501/187309294-80113076-fe38-4c6f-ac9f-1632bb8c2d91.png)

**Comment by DianaTavares** [comment]
Great job @AgustinVallejo, just not very sure about the control in the bottom.  I feel that the play buttons need to be closer to the play area. 

![image](https://user-images.githubusercontent.com/26031501/189773061-057c32a3-04e7-4473-a8c6-8d74035952ca.png)

I only find this example of a sim where the right and left controls go to the edges of the screen, but the ones at the bottom remain in their positions, as I think this simulation should do it:

![image](https://user-images.githubusercontent.com/26031501/189773029-6c943e91-3270-485d-a253-db20c21d03fd.png)

Then I think that the play buttons, and the mass controller need to remain in the center of the bottom of the simulation. not super sure about it, then I hope @ariel-phet can give us his opinion.

**Comment by ariel-phet** [comment]
@DianaTavares @AgustinVallejo 

Yes, in this case, I think you should keep the all the controls on the bottom of the sim in the same place (except the resetAll) in terms of horizontal position (the could float towards the bottom of the screen if it is made tall). So let the "Reset All" button float to the corner, and keep the horizontal position of the mass/bodies/play pause/timer all fixed.

**Comment by DianaTavares** [comment]
I like it. @AgustinVallejo, can you work on it?

**Comment by DianaTavares** [comment]
Amazing work, thanks!!
