### ISSUE TITLE
Rows can be misaligned with stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#151]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/927, on the Lab Screen with stringTest=dynamic, it is possible for the rows in the data panel to become misaligned. 

**Steps to reproduce**
1. Add query parameter ?stringTest=dynamic
2. Check More Data
3. Press the right arrow a couple of times
4. Cycle through words using the down arrow

**Visuals**
<img width="482" alt="Screenshot 2023-04-11 at 10 01 52 AM" src="https://user-images.githubusercontent.com/87318828/231211766-05d115dd-1869-4b34-b118-d7fa32ef278b.png">

<img width="579" alt="Screenshot 2023-04-11 at 10 02 11 AM" src="https://user-images.githubusercontent.com/87318828/231211996-a51d448c-e839-49c9-b177-e52d8d839655.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: My Solar SystemMy Solar SystemMy Solar SystemMy Solar SystemMy Solar SystemMy Solar SystemMy Solar SystemMy Solar System
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.9/phet/my-solar-system_all_phet.html?stringTest=dynamic
Version: 1.1.0-dev.9 2023-04-05 16:58:00 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1380x705
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
@AgustinVallejo and I fixed it in the commit, and it seems good in our tests. Thanks for finding the problem.  Can you please test on phettest and close if all is well?

**Comment by Nancy-Salpepi** [comment]
This looks good in master!
Closing!
