### ISSUE TITLE
Opening combobox while zoomed in causes screen to pan

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#152]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/927, on the Lab Screen, opening the combobox causes the screen to pan down. This doesn't happen in the published prototype, Molecule Shapes, or Concentration. 

**Steps to reproduce**
1. Zoom in using command + (on a mac) or control + (on Windows)
2. Pan to the combobox and open

**Visuals**

https://user-images.githubusercontent.com/87318828/231295325-868dfe78-5d9e-4870-829e-ba4e0a2b69f0.mp4

**Comment by jessegreenberg** [comment]
I was not able to investigate this this week. What should happen is that the sim should scroll to the selected item in the combobox. That seems to work for items far down the list but not the first items in the list.

This issue may not block publication of the sim, feel free to check with design team. I will be out of office until 4/24/23 but @jonathanolson said he could take a look if this needs to move forward while I am away. Thanks @jonathanolson!

**Comment by jessegreenberg** [comment]
I believe this was fixed along with https://github.com/phetsims/scenery/issues/1550 and #157. I can no longer reproduce this issue. I can believe that the problems with focus management in those issues could cause this but I didn't dive into it too deeply.

@Nancy-Salpepi would you mind confirming this is fixed?

**Comment by arouinfar** [comment]
I cannot reproduce on master @jessegreenberg. The sim will pan when the selected ListBox item is outside of the zoomed-in region, but it won't pan if the selected ListBox item is within the view.

**Comment by Nancy-Salpepi** [comment]
This looks good to me too @jessegreenberg. With both the mouse and keyboard nav, panning will occur if the selection is off the screen, but not when it isn't.

**Comment by jessegreenberg** [comment]
Wonderful. Thanks @arouinfar and @Nancy-Salpepi!
