### ISSUE TITLE
Ctrl may activate keyboard nav

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#154]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/927
If you open the drop down menu and press ctrl, it will activate keyboard nav as if you had hit tab.
**Steps to reproduce**
1. Go to the second screen
2. Open the drop down menu for different set ups
3. Press ctrl

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.9/phet/my-solar-system_all_phet.html
Version: 1.1.0-dev.9 2023-04-05 16:58:00 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
04/13 stand up:
1. We don't consider this to be a sim breaking issue.
2. We managed to replicate this in GO with its dropdown. Also in any sim with alt input on the PhET Menu and pressing either Ctrl, Alt, Shift or any modifier key. 

@jessegreenberg we will take a look into this, and we thought it'd be good to also keep you updated

**Comment by jessegreenberg** [comment]
Hey there! I think this is expected. When you open a pop-up like a menu or dialog focus may be set by that UI component. Pressing keys and other alt input events will just make the focus highlight visible. Please let me know if you would like to discuss further.

**Comment by AgustinVallejo** [comment]
Ok! That's good to hear, thanks! Closing.
