### ISSUE TITLE
Focus leaves the ComboBox on selection

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/my-solar-system#157]
While investigating https://github.com/phetsims/my-solar-system/issues/152 I noticed that focus is lost from the ComboBox when a new item is selected. I expected focus to move back to the ComboBox button. I am not seeing that behavior in the sun demo. Is this the expected behavior for this sim or should we investigate why this is happening?

**Comment by jessegreenberg** [comment]
It is looking like the same problem as https://github.com/phetsims/scenery/issues/1550 and https://github.com/phetsims/my-solar-system/issues/142. Focus is lost because of reentrant `focus` and `blur` events that happen when the ComboBox is closed.

**Comment by jessegreenberg** [comment]
Ill be working on this today, assigning myself since it seems like a very general problem.

**Comment by jessegreenberg** [comment]
I believe this issue blocks publication of this sim. I added notes about the problem in https://github.com/phetsims/scenery/issues/1550#issuecomment-1509369303

I will be out of office until 4/24/23, but @jonathanolson kindly offered to investigate if my-solar-system needs to move forward before then, thank you!

**Comment by jonathanolson** [comment]
Notes in https://github.com/phetsims/scenery/issues/1550#issuecomment-1516812771.

**Comment by jonathanolson** [comment]
I believe this should be handled now. @arouinfar can you verify in master?

**Comment by arouinfar** [comment]
Looks good in master, thanks @jonathanolson @jessegreenberg!!
