### ISSUE TITLE
Path behind grid lines

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#158]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/927
The path lines for orbits are layered behind the grid lines, which seems odd.

**Visuals**
<img width="131" alt="behindgrid" src="https://user-images.githubusercontent.com/41024075/232104865-24801bfd-516c-477b-b1f7-f0083cbeb242.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.9/phet/my-solar-system_all_phet.html
Version: 1.1.0-dev.9 2023-04-05 16:58:00 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
My reference is always Gravity and Orbits, and the path is the same color of the grid!!
But I think that, like the bodies are behind the grid to make measurements easier and more accurate, I think is the same for the paths. What do you think @arouinfar ?
