### ISSUE TITLE
Update max Period Division to 6 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#16]
It is not necessary to have many period divisions to visualize Kepplers' Laws and for to fit all the graphs in the bar graph; in the last design meeting, we agreed to have only 6 max divisions and always visualize all the areas in the Swept Areagraph. Next is some examples of mock-ups.

![image](https://user-images.githubusercontent.com/26031501/187322050-53cfcaa6-3dc1-43c3-bf77-fe242fb538a2.png)

![image](https://user-images.githubusercontent.com/26031501/187322022-7f33d343-94e8-480b-a581-74eeb3176aa4.png)

The bar graphs don't autoscale because that supports students in comparing areas of different orbits. The max size of the bars is for the bigger area that can be generated in the play area, and if the user draws a bigger area, the graph is going to show arrows indicating that the graph is bigger, like Energy graph in Masses and Springs:
![image](https://user-images.githubusercontent.com/26031501/187322520-1ead6c80-46c0-4b66-82b4-a0551e0fe923.png)

I think it is not necessary to add zoom buttons because this screen is going to be used to analyze orbits that fit in the play area. The areas will be in a range of values that will be visible in the Area Swept graph, but we can check that when the graph is working.

**Comment by AgustinVallejo** [comment]
Solved it here: https://github.com/phetsims/my-solar-system/commit/64745daef5b10a8b5c7c08b6871ff3e3c0eda1a5

**Comment by DianaTavares** [comment]
nice! Probably I will reopen this issue when you are working in the Swept Areas to be sure that the graph includes all the areas.
