### ISSUE TITLE
Comment on calculation of circular orbits 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/my-solar-system#160]
This is from a twitter user who has thoroughly tested the prototype

> The other things is just a comment. I am not sure anything needs to be changed. In the old version if you calculated the period of a circular orbit it did not match the time the sim displayed. To get around this I had students predict the ratio of the period of 2 different orbits. This worked well. I calculated the period of a circular orbit in the new one using the value of G one gets using the sim's units. This is 4.46 (AU*km^2)/(s^2*kg*10^28). It works but it is not trivial to get an answer in years to check with the output of the sim! I suggest you give it a try yourself. It might make you rethink the input units you are using. However, I doubt there is something workable that would be better. This is why the old sim used made-up units and it resulted in an inconsistent time unit. At least the new one works.

**Comment by AgustinVallejo** [comment]
Thanks for the feedback! Also, it seems there's nothing to be done here, closing.
