### ISSUE TITLE
User requests: significant figures, super slow, longer path, keyboard number entry

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/my-solar-system#164]
> I had been using the Flash version of My Solar System with my AP Physics C: Mechanics students for many years to study orbital mechanics, and I really missed it last year when it was no longer available. I was so happy to see the HTML5 version become available this year, and just finished using this new version with my students to analyze orbit shapes and to measure total energy and angular momentum at various positions in elliptical orbits to show that these quantities are conserved.
>  
> I see that this sim is still in the prototype phase, so I wanted to offer some (hopefully helpful) user feedback:

> 1. We ran into a bit of an issue trying to show angular momentum and energy conservation because the simulation gives so few significant figures on the position and velocity measurements. When using the “Ellipses” preset, the planet distance from the sun on closest approach is only 0.5 AU, so the rounding error is significant enough to throw off the angular momentum calculation by up to 10% and make it look different from other points in the orbit even though it should be the same.  The gravitational potential energy calculation is thrown off even more, and makes it look like total energy is not conserved when that point is used for comparison. The measuring tape helps a little, because it has 2 decimal places, but it’s difficult to see whether it’s lined up correctly, so I found that students didn’t make reliable measurements with that tool. For those of us using the sim for quantitative analysis, it would be very helpful to have at least 2 decimal places on the numbers shown when the “More Data” pane is displayed.  

> 2. It would be very helpful to have a “Super Slow” setting that is even slower than the current “Slow” setting. Pausing the sim when the planet is exactly to the left, right, above, or below the sun facilitates much easier calculation of angular momentum. The time step used on the current “Slow” setting makes this nearly impossible, and students either have to use approximate numbers, or deal with more difficult vector math to do the angular momentum calculation at a random point along the orbit.

> 3. The “Path” feature is very useful, but I wish it would leave a longer trail or leave the trail displayed permanently. When trying to observe orbit shapes, some initial position and velocity combinations cause the path to only display a small portion of the stable orbit instead of the whole ellipse. This made it hard to get good screen shots of orbits with different sizes and eccentricities for comparison. I also see why some of the other more complicated scenarios may benefit from having the path disappear eventually to eliminate clutter on the screen. Maybe there could be a slider added under the path setting to let the user choose how long of a trail to leave so it’s adaptable to different uses?

> 4. For usability, it would also be nice to be able to type numbers in the position and velocity boxes instead of clicking the numbers on the pop-up. My students found this method of entering desired numbers time-consuming and onerous.

Just to note: I also despise the numberPad entry we use in sims.

**Comment by oliver-phet** [comment]
Hi @DianaTavares assigning this feedback to you as responsible designer!

**Comment by AgustinVallejo** [comment]
Hi! Regarding the number pad, that was solved for the current version, should be done for the future deployment :)

I think the rest of the suggestions could potentially be added as preferences, but more discussion is needed.

**Comment by DianaTavares** [comment]
Thanks, Oliver, for sharing this user feedback.

**For point 1)** in the new version, position has 2 decimals, and I think velocity can also have 2 decimals! It has enough space for that. @AgustinVallejo, can you implement it?

**For point 2**) We can just suggest to the user the step-forward button. I used it to place the planet in the position of the orbit where I need it, but it is not perfect. In this case, Can the step-forward button do smaller steps?  In the picture I show how I stop the sim, trying to place the planet in the line of the grid, and when I click that button, it went after the line. 
![image](https://user-images.githubusercontent.com/26031501/235016003-bcf31d12-555b-4492-b112-cacd8a54e295.png)
![image](https://user-images.githubusercontent.com/26031501/235016016-ef64b2b2-bf7c-44b2-befd-7fa1540dd81c.png)

I realize that the step-forward button gives different steps depending on the speed of reproduction selected. If I am in slow, this is the position of one step vs the next step: 
![image](https://user-images.githubusercontent.com/26031501/235016444-d7d555aa-c9b8-4d2e-af56-94fa75260b6e.png)
![image](https://user-images.githubusercontent.com/26031501/235016494-d0fe0419-7e3e-479a-87c2-d88f5d05cfe8.png)
![image](https://user-images.githubusercontent.com/26031501/235016517-4c2664c4-b3bb-4422-838a-def64beb160d.png)
It don't fit exactly in the middle of the line, but I think is well enough, right? I can add this information in the teacher tip for teachers to know how to take more precisely measurements. 

**For point 3**Interesting proposal, but we don't have mores space for controls. The solution is make a little longer the path, but how much? In the way it is, it doesn't disturb any of the setups in the lab. Ideas @arouinfar 

 **For point 4**, well, it is the way it is for touch devices, nothing to do there.

**Comment by DianaTavares** [comment]
From stand up- April 28,

- [ ] add the extra decimal to the velocity
- [ ] see if possible to make smaller steps with the step-forward button 
- [ ] It is possible to write on the number pad with the keyboard!! I will add it in the teacher tips!

For future
We can add an option for not delete the path in the setting dialog

**Comment by zepumph** [comment]
Noting that the above commits are currently in MSS 1.2 and scheduled for immediate deployment. Marking the last checkbox as deferred and not for the 1.2 release

**Comment by zepumph** [comment]
> See Dan Burns's the activity to see if more user requests are needed

@AgustinVallejo can you please comment on this last unchecked checkmark?

**Comment by AgustinVallejo** [comment]
I remember reading through the activity some months ago replicating it in the sim, and didn't find any obvious change that should be done for MSS. We left it open in case anybody found anything but I think it's safe to close now. If more suggestions/requests come in, they should be done in a new issue.
