### ISSUE TITLE
Sound for sliders seems to be in reverse

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#168]
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/935, the sound for the sliders seems to be reversed. If I increase the mass, the sound goes down. I associate ascending sounds with numbers getting larger and descending sounds with numbers getting smaller. 

**Steps to reproduce**
On either screen, grab a mass slider and increase it and then decrease it. 

**Visuals**
(sorry my computer screen is sooooo dirty!!)

https://user-images.githubusercontent.com/87318828/235327002-1461c1a9-087a-4517-b009-ba6d8d1a6246.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.1.0-rc.1 2023-04-28 19:28:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15
Language: en-US
Window: 1318x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
It was decided in the sound design that, while it sounds a little bit counter intuitive, we prefer this mapping because it links bigger masses with deeper tones. Like elephant vs mouse walking sounds.

@DianaTavares @arouinfar @Ashton-Morris would any of you like to make an additional comment or this or is it good for closing?

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. Your expectation is not unreasonable, and we've had some internal debate on the team about this very issue. We've used a similar pitch mapping to represent mass in Gravity Force Lab (turn on enhanced sounds) and Gravity Force Lab: Basics. Musical instruments are another example of larger = deeper, such as violin vs. double bass or trumpet vs. tuba. (This can be attributed to longer wavelengths having a lower pitch.)

I recommend we leave the behavior as-is, but tagging @BLFiedler to make sure this is documented #82.
