### ISSUE TITLE
Mass can change when pressing Restart after using increment/decrement buttons

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#171]
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Safari/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/935 (and in master): On either screen, after using the increment/decrement buttons to change the mass, pressing the restart button will result in the mass being off by 1. This only happens if the button is press repeatedly to change the mass instead of holding it down. 

**Steps to reproduce**

1. On either screen, increase the mass of a body by pressing the increment button 5 times
2. Press Play
3. Press Restart-- the mass will change by 1

**Visuals**

https://user-images.githubusercontent.com/87318828/235683113-32ad0c59-4a2a-4e9c-b174-9d18019f92ee.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.1.0-rc.1 2023-04-28 19:28:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1575x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Fixed, please review and close! Thanks

**Comment by AgustinVallejo** [comment]
My potential solution was causing some unwanted consequences. So I will meet today with JB to look into the more in-depth problem, which is that for ArrowButtons, End Callback is called before the actual numberProperty is changed

**Comment by AgustinVallejo** [comment]
With @jbphet implemented a fix for the button value to change when the button is down instead of up. @Nancy-Salpepi please review!

Will also open an issue in Sun regarding the order of callbacks.

**Comment by Nancy-Salpepi** [comment]
This looks good now!

**Comment by zepumph** [comment]
This has been cherry picked onto 1.2, QA feel free to close once verified fixed in the next RC.
