### ISSUE TITLE
Overlap of speed labels

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#172]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/935
A few of the scene set ups have overlaps in their speed labels before the orbits even start. This is at default zoom level.

**Visuals**
![labeloverlap](https://user-images.githubusercontent.com/41024075/235756153-71f8a01f-a90f-4885-92e3-78e9c19c65a7.png)
![label2](https://user-images.githubusercontent.com/41024075/235756156-92ed7abe-e6b0-4a7a-a11e-12de32213b3a.png)
![overlap3](https://user-images.githubusercontent.com/41024075/235756159-c3f8f207-6afe-453c-93e4-c5ec0c4fd79e.png)
![overlap4](https://user-images.githubusercontent.com/41024075/235756161-bc6f54a8-beeb-4c25-bccb-84c7443d6632.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.2.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.2.0-rc.1 2023-05-02 15:04:18 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. 

I don't really think there's much we can do about this one. The initial conditions of each system often require objects to be close to one another, which will create overlap of the speed labels. In some cases, changing the zoom level may make the labels more readable. Generally, though, the initial velocities are one-dimensional so the component values in the "More Data" view will make the speed calculation trivial. 

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/8419308/236002757-980aef74-3688-4813-9bba-5d219c4519a6.png">

To completely avoid the labels overlapping would require more complicated logic, and I'm not convinced it's worth it. I recommend closing this as wont-fix, but I'll leave this open in case @DianaTavares wants to add any additional suggestions.

**Comment by DianaTavares** [comment]
I agree with what @arouinfar said! Closing this issue.
