### ISSUE TITLE
Return bodies button stays when you switch scenes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#173]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/935
On the second screen, if an object crashes on one scene and you switch to a new one, the Return Bodies button stays even though there is nothing to return anymore.
**Steps to reproduce**
1. Go to the Lab screen
2. Go to the Binary Star, Planet scene
3. Press play and wait for a crash
4. Switch to another scene and observe return button
5. Return to the Binary Star, Planet scene and note return button even though scene is reset

**Visuals**
![returnbutton](https://user-images.githubusercontent.com/41024075/235764501-461b1825-6f9a-4bd6-a572-c56761331288.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.2.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.2.0-rc.1 2023-05-02 15:04:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
This one should be fixed, please review and close! Thanks

**Comment by KatieWoe** [comment]
I was unable to test this on master because I got this error which froze the sim.
![trytest](https://user-images.githubusercontent.com/41024075/235779368-a31ddabe-c9f6-4fa9-9bc3-d04f1681d254.png)

**Comment by AgustinVallejo** [comment]
Sorry, forgot to push to a repo, could you try again now?

**Comment by KatieWoe** [comment]
Looks fixed on master

**Comment by zepumph** [comment]
We needed to push https://github.com/phetsims/solar-system-common/commit/71a510ff99747ff93eb902063cacded830419e73, to see this fix in action, but we don't need to patch the RC with it.

To cherry-pick: https://github.com/phetsims/my-solar-system/commit/f93342b7744ec1b1001da5c04985d8c60897e933

**Comment by zepumph** [comment]
Cherry picked onto 1.2, please feel free to close when confirmed fixed.

**Comment by stemilymill** [comment]
Fixed!
