### ISSUE TITLE
Performance noticeably worse than dev.9 version

### ISSUE THREAD

**Issue by stemilymill** [phetsims/my-solar-system#174]
For https://github.com/phetsims/qa/issues/935

Originally I noticed that on Windows devices, performance/animation is significantly worse in Firefox than Chrome. This was true on multiple devices, both Win10 and Win11. 

After further investigation, @Nancy-Salpepi and I discovered that between [dev.9](https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.9/phet/my-solar-system_all_phet.html) and [dev.10](https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.10/phet/my-solar-system_all_phet.html) performance significantly decreased in general. On our devices, this is most evident with windows Firefox and on chromebook.

Here is a particularly bad example (this recording is at 45 frames per second, the video quality isnt exaggerating the problem)

https://user-images.githubusercontent.com/85511101/235779467-4f42b4d0-9481-45d7-8669-13a6f3484c20.mp4

While the animation is playing, slider use is also impacted- there is lag when dragging the thumb and snap points are skipped. This is more evident with sound but the lag is definitely visible with this screen recording.

https://user-images.githubusercontent.com/85511101/235778837-51176453-b5a9-48d4-a5eb-337e67c5574a.mp4

**Comment by AgustinVallejo** [comment]
Thanks for noting! Will investigate

**Comment by AgustinVallejo** [comment]
I implemented a potential solution, which after pushing, improved significantly the performance according to @stemilymill. Also showed it to @jonathanolson and he said I should double check a couple things but overall seems fine. A change I noticed right away is that when you hold the step button, we move in big intervals, somewhat affecting the accuracy of the Sim but not greatly (noticeable deviations from the normal playing mode after multiple orbits). That might get fixed with JO's suggestions but I don't think it's worrying.

**Comment by Nancy-Salpepi** [comment]
Looking at the Lab Screen with Win10 + FF some of the orbits aren't smooth in master. Here is an example with Double Slingshot:
![orbit](https://user-images.githubusercontent.com/87318828/236001746-c704c1e8-d2e3-4bfe-964c-6c001c296958.JPG)

Oddly, if I switch to slow speed, things look much smoother.

**Comment by Nancy-Salpepi** [comment]
Also, if I use the step forward button on any scene and then switch to Double Slingshot and press play, the green body will immediately collide with the pink one.

**Comment by arouinfar** [comment]
> A change I noticed right away is that when you hold the step button, we move in big intervals, somewhat affecting the accuracy of the Sim but not greatly (noticeable deviations from the normal playing mode after multiple orbits). 

I find this statement concerning. Using the step forward button can be vital to setting up particular scenarios, and was a strategy we recommended to a user in #164. I think increasing its granularity is problematic.

**Comment by AgustinVallejo** [comment]
The above commit tries to keep the performance enhancement and avoid the artifacts. Seems to be working better on my end, but I'm not really sure how effective it is for low end devices. Could you please test @stemilymill @Nancy-Salpepi ?

**Comment by Nancy-Salpepi** [comment]
Things look better on Win10 + FF for me. I didn't look at the Chromebook in master earlier, but comparing it to 1.2.0-rc.1 it looks much better.

**Comment by arouinfar** [comment]
@AgustinVallejo should this remain open for cherry-picking?

**Comment by zepumph** [comment]
Cherry picks are in 1.2, QA feel free to close upon next RC verification.

**Comment by stemilymill** [comment]
> Also, if I use the step forward button on any scene and then switch to Double Slingshot and press play, the green body will immediately collide with the pink one.

During spot-check I had a collision with double slingshot, but I have not been able to reproduce it yet. It was after going back and forth with different scenes multiple times, so definitely not as simple as before when it was just using the step forward button.

**Comment by zepumph** [comment]
I'll leave open for AG to verify as acceptable, but not blocking. If we need to do a quick MR next month that will be easy and fine!
