### ISSUE TITLE
Restart button enabled after switching scenes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#175]
**Test device**
Dell 

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/935 on the Lab Screen, the Restart button stays enabled when switching scenes. 

**Steps to reproduce**
1. On the lab screen press play
2. Switch scenes

**Visuals**

https://user-images.githubusercontent.com/87318828/235922565-043a00a2-bab3-4d2e-93f4-2a1dab90ce19.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.2.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.2.0-rc.1 2023-05-02 15:04:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1433x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
This looks fixed in master!.

**Comment by zepumph** [comment]
Cherry picked onto 1.2, please feel free to close when confirmed fixed.

**Comment by stemilymill** [comment]
Fixed!
