### ISSUE TITLE
Punctuation change needed in Note 1

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#176]
For https://github.com/phetsims/qa/issues/935, on the Lab Screen, I would change the comma after "kilometers" in Note 1 to a period to look like this:

>Astronomical Unit (AU) is about 150 million kilometers. This is the average distance between the Sun and the Earth.

**Comment by AgustinVallejo** [comment]
This is ready for review now, thanks!

**Comment by Nancy-Salpepi** [comment]
This looks good now!

**Comment by zepumph** [comment]
Cherry picked onto 1.2, please feel free to close when confirmed fixed.

**Comment by stemilymill** [comment]
Fixed!
