### ISSUE TITLE
Clear Button should be disabled at the start of sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#177]
**Test device**
Dell

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/935, the clear button should be disabled when the time is 0 years. This occurs 

- at the start of the sim/after pressing reset all
-  after pressing restart
- after switching scenes while the sim is paused

**Visuals**
<img width="240" alt="Screenshot 2023-05-03 at 10 54 18 AM" src="https://user-images.githubusercontent.com/87318828/235954890-e442d31d-05a4-45bf-9350-aa7cbbc577e7.png">

Gravity and Orbits:
<img width="903" alt="Screenshot 2023-05-03 at 10 48 52 AM" src="https://user-images.githubusercontent.com/87318828/235955015-1ec1d558-9838-4081-8a93-5274b2b439c7.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.2.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.2.0-rc.1 2023-05-02 15:04:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1433x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
This looks good now!

**Comment by zepumph** [comment]
Cherry picked onto 1.2, please feel free to close when confirmed fixed.

**Comment by stemilymill** [comment]
Fixed!
