### ISSUE TITLE
Return Bodies button still present with 4 bodies on screen 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#178]
**Test device**
Dell

**Operating System**
Win10

**Browser**
FF

**Problem description**
For https://github.com/phetsims/qa/issues/935 and seen on master:

On the Lab Screen, after bodies collide the Return Bodies button appears. Instead of pressing it or the Restart button, I can increase the number of bodies using the number spinner. When I do that, there are 4 bodies on the screen and the Return Bodies button is still there.
This is similar to https://github.com/phetsims/my-solar-system/issues/173.

**Steps to reproduce**
1. On the Lab Screen, cause the yellow and pink bodies to collide
2. Increase the number of bodies to 4 using the number spinner

**Visuals**

https://user-images.githubusercontent.com/87318828/236087263-a023874c-1651-4978-8da9-11062320b97f.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.2.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.2.0-rc.1 2023-05-02 15:04:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language: en-US
Window: 1433x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Things look good to me in master!

**Comment by zepumph** [comment]
Cherry picked onto 1.2, please feel free to close when confirmed fixed.

**Comment by stemilymill** [comment]
@AgustinVallejo @DianaTavares I'm not sure if this is intended behavior - if some bodies are off screen and I use the number spinner to increase the number of bodies, using the return bodies button can result in still having some bodies off screen

![no return bodies button](https://user-images.githubusercontent.com/85511101/236880572-5b641483-256a-4370-8a71-98d05ff2222b.jpg)

**Comment by AgustinVallejo** [comment]
Yes, this is inevitable behavior and has been agreed upon after multiple conversations. The user could fix that by manually changing the body position in the data panel.

**Comment by stemilymill** [comment]
ok, thanks! Then this issue is confirmed fixed 👍
