### ISSUE TITLE
Time progresses differently with play vs step button

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#18]
Noticed in the code review (will commit soon), confirmed in the sim.

Try opening the Intro screen, and get the magenta body to directly above the yellow one (by either hitting the play button, or by repeatedly hitting the step button). The time will show dramatically different values:

Hitting the step button (many) times to get the body here:
<img width="383" alt="image" src="https://user-images.githubusercontent.com/480878/188937847-8587c520-518f-4f0c-9a4a-449caef04ba8.png">

Pressing the play button once, and pausing to get the body here:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/480878/188937906-984b8aba-e1dc-4090-9d4c-a2fb79777ff6.png">

**Comment by AgustinVallejo** [comment]
Forgot to mention this issue on the commit, but see https://github.com/phetsims/my-solar-system/commit/b7de3114b618dcad6f4281aebe480796dba14327

**Comment by jonathanolson** [comment]
Looks good, thanks!
