### ISSUE TITLE
Grid not visible in full screen on Chromebook

### ISSUE THREAD

**Issue by stemilymill** [phetsims/my-solar-system#181]
For https://github.com/phetsims/qa/issues/935

On my chromebook (Lenovo 100e Chromebook 2nd gen MTK, ChromeOS 112.0.5615.134 32-bit)

The grid does not appear in full screen mode, regardless of turning it on while in fullscreen or turning it on before going full screen. If I take a screenshot, the grid is visible in the screenshot.

In addition, having the grid turned on (though not visible) while in fullscreen makes the sim extremely laggy, especially mouse movements and keyboard navigation. This happens on master as well as the [rc version](https://phet-dev.colorado.edu/html/my-solar-system/1.2.0-rc.1/phet/my-solar-system_all_phet.html). Tagging https://github.com/phetsims/my-solar-system/issues/174 in case it's relevant.

**Comment by AgustinVallejo** [comment]
Hi! Could you please check if the issue is also present in this old version? We made changes to the Grid Node right after that, essentially making it much bigger, and that could be causing it. 

https://phet-dev.colorado.edu/html/my-solar-system/1.1.0-dev.7/phet/my-solar-system_all_phet.html

**Comment by zepumph** [comment]
We are going to proceed with the 1.2 rc spotcheck without continuing with this bug fix. If we find a fix we can always patch it into the published version.

**Comment by Nancy-Salpepi** [comment]
@AgustinVallejo for https://github.com/phetsims/qa/issues/997, I don't see an issue with the gridlines on my Chromebook (Levono 100e). I also tested the [rc version](https://phet-dev.colorado.edu/html/my-solar-system/1.2.0-rc.1/phet/my-solar-system_all_phet.html) that was used to report this issue and didn't see a problem. Perhaps it was device specific?

**Comment by AgustinVallejo** [comment]
Thanks @Nancy-Salpepi, I think this is then good to close
