### ISSUE TITLE
Errors when running debug test

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#182]
For https://github.com/phetsims/qa/issues/940
When running a fuzz test on the debug version of the sim errors like this appeared.
<img width="364" alt="debug" src="https://user-images.githubusercontent.com/41024075/236953020-68383a1d-6768-4519-a0ef-4cddcecf436f.png">

**Comment by zepumph** [comment]
Can you paste the URL you used to reproduce this problem?

**Comment by KatieWoe** [comment]
https://phet-dev.colorado.edu/html/my-solar-system/1.2.0-rc.2/phet/my-solar-system_all_phet_debug.html?fuzz
