### ISSUE TITLE
Revise SolarSystemCommonColors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#191]
Identified during 9/26/23 PhET-iO design meeting ...  In SolarSystemCommonColors:

- [x] Rename `firstBodyColorProperty` to `body1ColorProperty` etc.
- [x] Uninstrument all ProfileColorProperty instances except `body1ColorProperty` etc.

**Comment by pixelzoom** [comment]
This is done, Studio tree is shown below.  @arouinfar @AgustinVallejo please review. Last one assigned can close the issue.

@AgustinVallejo also note that the `colorName` argument to ProfileColorProperty was incorrect in almost all cases. By convention, it should be the name of the ProfileColorProperty, with the "Property" suffix removed. For example:

```diff
- controlPanelFillProperty: new ProfileColorProperty( solarSystemCommon, 'control panel fill', {
+ controlPanelFillProperty: new ProfileColorProperty( solarSystemCommon, 'controlPanelFill', {
    default: 'rgb( 40, 40, 40 )',
    projector: new Color( 222, 234, 255 )
  } ),
```

**Comment by AgustinVallejo** [comment]
Looks like a proper change, and also thanks for noting the incorrect naming!

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good on main!
