### ISSUE TITLE
Remove rasterization workaround in IntroScreenIcon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#199]
In https://github.com/phetsims/my-solar-system/issues/46, this complicated bit was introduced into IntroScreenIcon, to work around a clipping problem on Safari:

```ts
    const containerNode = new Node();

    Multilink.multilink( [ SolarSystemCommonColors.firstBodyColorProperty, SolarSystemCommonColors.secondBodyColorProperty ], () => {

      // Rasterizing the icon because clip areas weren't working on Safari, see https://github.com/phetsims/my-solar-system/issues/46
      // Because rasterization reduces quality, we only do it on Safari
      containerNode.children = [ platform.safari ? node.rasterized( {
        resolution: 16,

        sourceBounds: new Bounds2( -8, -10, 22, 10 )
      } ) : node ];
    } );
```

I've experienced this in other sims, and there's no need to resort to platform-specific workarounds like rasterizing. It's usually a case that clipping was applied to the wrong Node.   In this case, the solution is even easier -- use `Shape.ellipticalArc` to draw the desired portion of the magenta-color orbit, rather than using `Shape.ellipse` to draw the entire orbit and then having to clip it.

**Comment by pixelzoom** [comment]
Done in the above commit.  Screenshots below show what it looks like on both Safari and Chrome.  Note that I didn't match the previous arc exactly - the icon is a bit larger, which I think is a slight improvement, while not requiring new screenshots.

@AgustinVallejo please review, close if OK.

<img width="1116" alt="screenshot_2802" src="https://github.com/phetsims/my-solar-system/assets/3046552/47585b91-60ff-4c76-8258-bcc795680c15">

<img width="1137" alt="screenshot_2803" src="https://github.com/phetsims/my-solar-system/assets/3046552/212cde0d-67c0-45f5-8382-930346d91b4d">

**Comment by AgustinVallejo** [comment]
Thanks, this definitely seems like a simpler way forward. Closing.
