### ISSUE TITLE
Screens Icons  

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#20]
Here is the picture of the suggested icons for the sim: 

![image](https://user-images.githubusercontent.com/26031501/189778528-c53b9dcc-cc4e-4650-b16b-beb1353a457f.png)

I already presented them before ion the design meeting, I want to know if they are ready for @AgustinVallejo to include them in the sim.  

What do you think @ariel-phet and @arouinfar ?

**Comment by ariel-phet** [comment]
@DianaTavares Those look pretty nice, the one change I would suggest is that on Intro and Lab you make the stroke weight of the  lines for the orbits thicker. When the icons are quite small, the line weight you have now gets a bit pixelated.

**Comment by DianaTavares** [comment]
Nice, I will work in a mockup with the strokes thicker. I understand that these icons are made with code and not with pictures, then @AgustinVallejo, if you have time to code them,  please do it with the change that @ariel-phet suggests.

**Comment by DianaTavares** [comment]
I add bigger strokes, and the orbit of the yellow star in the Intro screen because I feel that, if the center of mass is outside the massive object, it generates an orbit around the center of mass too!! 

![image](https://user-images.githubusercontent.com/26031501/191565302-ebb252cf-808b-4d93-bd44-b7fa6ad174df.png)

**Comment by DianaTavares** [comment]
Thanks @ariel-phet and @arouinfar! Then @AgustinVallejo these icons are ready to be added in the Sim!  For the Intro, then without the star's orbit.

**Comment by DianaTavares** [comment]
It looks beautiful! Thanks Agustin!! :D
