### ISSUE TITLE
Keyboard help is missing for combo box in Lab screen.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#200]
The Lab screen has a combo box that does not appear in the Intro screen:

<img width="274" alt="screenshot_2804" src="https://github.com/phetsims/my-solar-system/assets/3046552/484d5e52-488b-4fcc-b3e2-d2b5abf0a7e5">

The keyboard help is identical for both screens (`MySolarSystemKeyboardHelpContent`), so the Lab screen missing the keyboard help for the combo box (`ComboBoxKeyboardHelpSection`):

<img width="1127" alt="screenshot_2805" src="https://github.com/phetsims/my-solar-system/assets/3046552/628ce7f1-8eff-457d-9e8e-377ae227256e">

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/keplers-laws/issues/188 for an example of how to use and customize `ComboBoxKeyboardHelpSectionOptions`.  I'm not sure what you're going to call the items here.  They are of type `LabMode`, but that does not seem like a public-facing name for the items in the combo box.

**Comment by pixelzoom** [comment]
@DianaTavares or @arouinfar What should the langugage be for the keyboard help related to the combo box? In the screenshot below, what term should be substituted for "Object"?

<img width="379" alt="screenshot_2814" src="https://github.com/phetsims/my-solar-system/assets/3046552/7b4b0c5a-4802-4746-956c-2237c5543c96">

**Comment by DianaTavares** [comment]
We call them "System" in the teacher tips. I remember that we had these discussions when we wrote the teacher tips (because we call them pre-sets in the design doc). The simulation is called "My solar System" because users can create their own systems, and that combo box gives them some systems to explore.

@AgustinVallejo agreed with this term in a Slack conversation.

**Comment by pixelzoom** [comment]
System sounds excellent.

@AgustinVallejo we should probably change internal code names accordingly, e.g:

* labModeProperty => systemProperty
* LabMode => System
* ??

**Comment by AgustinVallejo** [comment]
Will take a look and start refactoring

**Comment by pixelzoom** [comment]
@arouinfar feel free to weight in here too.

**Comment by pixelzoom** [comment]
I discussed the proposed "Planetary System" name with @arouinfar.  She agreed that "System" was too vague and sounded like something related to the operating system.  There is definitely a sun in all screens of Kepler's Laws.  And the title "My Solar System" implies that there is a sun.   So we feel safe proceeding with "Planetary System".

**Comment by AgustinVallejo** [comment]
Not going to oppose "Planetary System", but it also seems to imply the bodies are planets, and that's not necessary. Maybe "orbital system" could be better?

**Comment by pixelzoom** [comment]
"Orbital System" sounds great, and was an alterative that @arouinfar mentioned that I forgot to record in my comment above.

**Comment by pixelzoom** [comment]
The switch to "Orbital System" was completed in the above commits.

Remaining work is to add the keboard help for OrbitalSystemComboBox.

**Comment by pixelzoom** [comment]
Note that it was not possible to change "mode" in string keys.  The sim uses a "mode" prefix for all of the orbital system names, for example: "mode.sunAndPlanet", "mode.sunPlanetAndMoon",...   Due to the difficulty of renaming string keys, we should plan on living with these.

**Comment by pixelzoom** [comment]
Keyboard help for the Lab screen's combo box was added in the above commit.   It appears only in the help dialog for the Lab screen, and not the intro screen - see screenshot below.  The implementation and layout issues were identical to https://github.com/phetsims/keplers-laws/issues/188 (and no, I don't think this should be moved to solar-system-common).

@AgustinVallejo please review the implementation. @arouinfar please review the design, since you reviewed https://github.com/phetsims/keplers-laws/issues/188.   Last person assigned please close the issue.

<img width="846" alt="screenshot_2824" src="https://github.com/phetsims/my-solar-system/assets/3046552/b4f82d93-fb03-4707-bc18-6cc77cf553ac">
