### ISSUE TITLE
Rename FullDataPanel to ValuesPanel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#201]
Naming is particularly important because of PhET-iO.

The sim currently has ValuesColumnTypes and ValuesColumnNode.  But ValuesColumnNode are assembled into FullDataPanel, which currently has no tandem.  And it's doc is "The panel that shows the numeric values..." So I'm going to rename FullDataPanel to ValuesPanel for consistency, and its tandem name will be 'valuesPanel'.

**Comment by pixelzoom** [comment]
Renamed and basic instrumentation was added.  @AgustinVallejo please review, close if OK.

**Comment by AgustinVallejo** [comment]
Thanks, looks ok.
