### ISSUE TITLE
Revise unsafe uses of `combineOptions`.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#204]
Most of the uses of `combineOptions` are unsafe, for example in MySolarSystemScreenView.ts:

```ts
      combineOptions<CheckboxOptions>( {
        accessibleName: MySolarSystemStrings.a11y.moreDataStringProperty,
        touchAreaXDilation: 10,
        touchAreaYDilation: 10,
        tandem: model.isLab ? options.tandem.createTandem( 'moreDataCheckbox' ) : Tandem.OPT_OUT
      }, SolarSystemCommonConstants.CHECKBOX_OPTIONS )
```

If you were to add something to `SolarSystemCommonConstants.CHECKBOX_OPTIONS`, you risk unintentionally blowing away your custom settings in the first argument to  `combineOptions`.

In general, the arguments to `combineOptions` should be ordered from least to most specific.  So the customizations should be last, like this:

```ts
      combineOptions<CheckboxOptions>( {}, SolarSystemCommonConstants.CHECKBOX_OPTIONS, {
        accessibleName: MySolarSystemStrings.a11y.moreDataStringProperty,
        touchAreaXDilation: 10,
        touchAreaYDilation: 10,
        tandem: model.isLab ? options.tandem.createTandem( 'moreDataCheckbox' ) : Tandem.OPT_OUT
      } )
```

Note that the first argument should be `{}`, so that you're not modifying the shared options values - in this case `SolarSystemCommonConstants.CHECKBOX_OPTIONS`.

**Comment by pixelzoom** [comment]
I took care of my-solar-system in the above commit.  Still need to do solar-system-common when it is unblocked.

**Comment by pixelzoom** [comment]
All unsafe uses of `combineOptions` have been addressed in my-solar-system, solar-system-common, and keplers-laws.

There are still some _incorrect_ uses of `combineOptions` in keplers-laws - see https://github.com/phetsims/keplers-laws/issues/190.

@AgustinVallejo please review, close if OK.

**Comment by AgustinVallejo** [comment]
I wasn't aware of the correct usage of combineOptions, thanks for pointing that out!
