### ISSUE TITLE
labModeProperty and LabMode are only used by my-solar-system

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#205]
solar-system-common repo contains enumeration `LabMode`. And SolarSystemCommonModel contains this field:

```ts
  public readonly labModeProperty: EnumerationProperty<LabMode>;
```

`labModeProperty` and `LabMode` are used only in my-solar-system. They are not used in keplers-laws.  That will be a problem when keplers-laws is eventually instrumented.   Can we move `labModeProperty` to MySolarSystemModel (or LabModel?), and relocate `LabMode` to my-solar-system?

**Comment by pixelzoom** [comment]
Summary of above commits:

* labModeProperty is now created by LabModel, instead of SolarSystemCommonModel
* labModePanel is not created by LabScreenView, instead of MySolarSystemScreenView
* LabMode was moved to my-solar-system/js/lab/model
* LabModePanel and LabModeComboBox were moved to my-solar-system/js/lab/view

Over to @AgustinVallejo to review.

**Comment by AgustinVallejo** [comment]
Definitely makes more sense this way, LabMode was used entirely by the lab screen.
