### ISSUE TITLE
Get rid of SolarSystemCommonModel `isLab`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#206]
SolarSystemCommonModel has this option and field:

```ts
type SelfOptions<EngineType extends Engine> = {
...
  isLab?: boolean;

  public readonly isLab: boolean;
```

The semantics of this field have one meaning in my-solar-system, and a different meaning in keplers-laws.  And it's doubly confusing because there is no "Lab" in keplers-laws. 

Recommended to remove this field from SolarSystemCommonModel, and add sim-specific fields to MySolarSystemModel and KeplersLawsModel.  They could be `isLabScreen` and `isAllLawsScreens` respectively.

Even better would be to get rid of this field entirely, and use the class hierarchy appropriately.  Having a flag like `isLab` is a bandaid for a class design problem.  And that problem is going to be exposed by PhET-iO, as we find ourselves creating (and instrumenting) things that are irrelevant for some screens.

**Comment by pixelzoom** [comment]
Summary of the above commits:

* The `isLab` option was moved from SolarSystemCommonModel to MySolarSystemModel.
* A new `isAllLaws` options was added to KeplersLawsModel.

This should address the confusion of having an `isLab` option in a sim that has no "Lab" screen.

@AgustinVallejo please review, close if OK.

**Comment by AgustinVallejo** [comment]
Yup, the above changes make more sense. Thanks!
