### ISSUE TITLE
Standardize on `.value` for setting and getting Property values.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#209]
Usage of the API for setting and getting Property values is inconsistent.  In some places, `property.get()` and `property.set( value )` are used.  In other some places `property.value` and `property.value =value` are used.   This makes it difficult to search for usages.  And while usage is up to developer discretion, it's highly recommended to be consistent. 

So I propose that we standardize on `.value`.

**Comment by pixelzoom** [comment]
Done in the above commit for my-solar-system.  Still need to do the same for solar-system-common.

**Comment by AgustinVallejo** [comment]
Looks OK, thanks. Closing.
