### ISSUE TITLE
Properties are mutated in place with no call to notifyListenersStatic.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#210]
In NumericalEngine:

```ts
  public override run( dt: number, updateProperties = true ): void {
...
    for ( let i = 0; i < this.bodies.length; i++ ) {
      const body = this.bodies[ i ];

      if ( updateProperties ) {
        body.positionProperty.value = positions[ i ];
        body.velocityProperty.value = velocities[ i ];
        body.accelerationProperty.value = accelerations[ i ];
        body.forceProperty.value = forces[ i ];
      }
      else {
        body.positionProperty.value.set( positions[ i ] );
        body.velocityProperty.value.set( velocities[ i ] );
        body.accelerationProperty.value.set( accelerations[ i ] );
        body.forceProperty.value.set( forces[ i ] );
      }
    }
```

The `else` block shown above looks dangerous, maybe even buggy.  The values of 4 `Property<Vector2>` instances are being mutated in place, with no code to force notification of listeners.  After mutating the value of a Property, I would expect to see a call to `notifyListenersStatic`.

**Comment by pixelzoom** [comment]
Maybe this just needs some documentation about why this is OK/necessary -- for example, if it's a performance improvement.

**Comment by AgustinVallejo** [comment]
This was done in the above commit. Closing.

**Comment by pixelzoom** [comment]
Reopening this.  

The doc that was added to NumericalEngine is:

```ts
      // Here, depending on updateProperties, we either update (and notify) the Properties or mutate their Vector2 values.
      // This is done to avoid notifying the Property change on every iteration, which is expensive.
      // Currently, on SolarSystemCommonModel, it is set to false except on the last iteration of the model.run() method.
```

But `model.run` does not exists. And I don't know what "it is set to false" is referring to.

I also don't understand when the `if` vs `else` block is executed, and how/where listeners are notified for the `else` block. For example, how does Body `speedProperty` know to update when the `else` block executes and mutates the value of `velocityProperty`:

```ts
    this.speedProperty = new DerivedProperty( [ this.velocityProperty ], velocity => velocity.magnitude, {
...
    } );
```

**Comment by pixelzoom** [comment]
OK, I see how this works.  In the above commits, I renamed `updateProperties` to `notifyPropertyListener`, and improved the documentation.

It's odd that EllipticalOrbitEngine doesn't support this `run` parameter.  @AgustinVallejo why is optimization needed in My Solar System, but not in Kepler's Laws?

**Comment by pixelzoom** [comment]
@AgustinVallejo explained why `notifyPropertyListeners` is not relevant for EllipticalOrbitEngine, and I added a bit of doc.

Closing.
