### ISSUE TITLE
Undocumented or under-documented code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#213]
During PhET-iO instrumentation, I'm running into places in the code that are undocumented or under-documented. I'm going to use this issue to tag those places with a TODO.

**Comment by pixelzoom** [comment]
I went through my-solar-system and solar-system-common, and I added a TODO for each field and method that was undocumented (or under-documented) that I did not understand.  Over to @AgustinVallejo to document.

**Comment by AgustinVallejo** [comment]
I believe all the requested documentation has been added. I'll close this now. If more undocumented code appears, feel free to re-open this.
