### ISSUE TITLE
Missing `readonly` keyword

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#214]
During PhET-iO instrumentation, I'm running into places where the TypeScript `readonly` keyword is missing.  I'll use this issue to tag or fix those places.

For example, in SolarSystemCommonModel, these should be `readonly`:

```
  public numberOfActiveBodiesProperty: NumberProperty;
  public engine: EngineType;
```

**Comment by pixelzoom** [comment]
I added missing `readonly` occurences in my-solar-system, solar-system-common, and keplers-laws.  This investigation resulted in the discovered of 2 significant problems in the model: see https://github.com/phetsims/keplers-laws/issues/191 and https://github.com/phetsims/keplers-laws/issues/192.  

Over to @AgustinVallejo for review, close if OK.

**Comment by AgustinVallejo** [comment]
Noted, thanks for the fix. We should work together on the TODO's. Closing
