### ISSUE TITLE
Rename valuesVisibleProperty to speedVisibleProperty?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#219]
While working on https://github.com/phetsims/my-solar-system/issues/218, I noticed that this Property in SolarSystemCommonModel:

```ts
  public readonly valuesVisibleProperty: BooleanProperty;

    this.valuesVisibleProperty = new BooleanProperty( false, {
      tandem: visiblePropertiesTandem.createTandem( 'valuesVisibleProperty' )
    } );
```

... is controlled by the "Speed" checkbox in both my-solar-system and keplers-laws.   This is potentially confusing, because the tandem name is visible in the PhET-iO API.   Can it be renamed `speedVisibleProperty`?  Or is there some reason why `valuesVisibleProperty` is necessary?

**Comment by pixelzoom** [comment]
BodyNodeOptions `valuesVisibleProperty` should also be rename to `speedVisibleProperty`.

**Comment by pixelzoom** [comment]
Done in the above commit.  Note that several things were renamed from "value" to "speed" in BodyNode.

Over to @AgustinVallejo for review. Close if OK.

**Comment by AgustinVallejo** [comment]
Thanks for this refactoring, closing.
