### ISSUE TITLE
Velocity of reproduction 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#22]
We discuss this before in a design meeting, but I'm still feeling that in intro and lab sim, the movement of the bodies in the initial state is slow, and the fast button doesn't make it very fast. Can the Kepler's Law and the other screens have a different velocity of reproduction?  Because for that screen, I find the velocity of reproduction correct. 

For the first and third screen, I would like a velocity compared with the Flash simulation.
**Left:** HTML5 in the fast reproduction. **Right:** the Flash sim in its normal reproduction. My suggestion is to make the HTML5 same velocity in the normal reproduction that the Flash. 

![velocity](https://user-images.githubusercontent.com/26031501/191332891-5c7de9eb-dc78-42ad-a718-c9718048ddf9.gif)

This is fast in the flash, and I find it ok! And I suggest doing the same in the HTML5 sim.   
![fast](https://user-images.githubusercontent.com/26031501/191333290-2be5494f-bb90-4a01-8aeb-6c19ba3dab4d.gif)

What do you think @ariel-phet ?

**Comment by ariel-phet** [comment]
@DianaTavares since the flash sim was very popular and no complaints I am aware of for the speed, if you like the speeds seen in the Flash sim, matching them makes sense to me!
