### ISSUE TITLE
Body `radiusProperty` is initialized twice

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#220]
Noticed while trying to instrument Body for PhET-iO ...

Looks like there's a bug in Body.  `radiusProperty` is initialized twice!

```ts
  public readonly radiusProperty: TReadOnlyProperty<number>;
...
    this.radiusProperty = new NumberProperty( 1 );
...
    this.radiusProperty = new DerivedProperty( [ this.massProperty ], mass => Body.massToRadius( mass ) );
```

**Comment by pixelzoom** [comment]
I delete the first initialization, since it was overwritten by the second.  @AgustinVallejo have a look, in case I missed something. Close if OK.

**Comment by AgustinVallejo** [comment]
Seems good to close, good catch!
