### ISSUE TITLE
Use 1-based index in Body?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#221]
Body currently uses 0-based indexing for it `index` field:

```ts
public constructor( public readonly index: number,
```

But PhET-iO uses 1-based for tandem names.  And there are a number of other places that used 1-based, see below.  So perhaps we should convert to 1-based for the Body `index` field.

<img width="842" alt="screenshot_2816" src="https://github.com/phetsims/my-solar-system/assets/3046552/ab1ad937-6f24-494b-9f30-0740b4ecbc75">

**Comment by pixelzoom** [comment]
We'll change to 1-based indexing. I'll take care of it.

**Comment by pixelzoom** [comment]
In the above commits, I changed Body `index` to be 1-based.

I noticed that keplers-laws OrbitArea also has an `index` field, so I documented that it is 0-based.  I think it's fine to leave it as 0-based, because orbits are not labeled in the UI, and it's unlikely that they will appear in the PhET-iO API.

Over to @AgustinVallejo for review. Close if OK.

**Comment by AgustinVallejo** [comment]
Thanks, closing
