### ISSUE TITLE
PhET-iO design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#224]
The PhET-iO design doc for My Solar System is: https://docs.google.com/document/d/1FTpTD34mptfTyCIun6cHbJarS9WQICkH3n_isCg30uI/edit#heading=h.lu1cj4lotmnh

Sim-specific requirements to identify include:
* Preferences
* Query parameters
* PhET-iO only features
* Customer suggestions
* ...

We had a design meeting on 9/26/2023. @arouinfar will turn the notes from that meeting into requirements.  Please assign this issue to @AgustinVallejo and @pixelzoom  when the design doc is ready, and we'll turn the requirements into GitHub issues as needed.

**Comment by arouinfar** [comment]
@pixelzoom @AgustinVallejo I formatted the meeting notes into the "Desired Features" table near the top of the doc. Please let me know if you need any additional information to get started.

During the design meeting, we concluded that there is no need for query parameters or simulation preferences in this release. Additionally, there are no known customer suggestions.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  I triaged the "Desired Features" section of the design doc, and created GitHub issues were useful. 

@AgustinVallejo feel free to review the design doc, and close this issue when you're familar with it.

**Comment by AgustinVallejo** [comment]
Gave it a thorough read, not sure if I'm entirely familiar yet but definitely looks like a guide I'll be coming back to. Thanks Amy! Closing
