### ISSUE TITLE
Several important Properties do not use standard units.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#229]
There are several important Properties whose values are not in SI units. They are in units that are convenient/practical for the implementation. See the [Units section of model.md](https://github.com/phetsims/my-solar-system/blob/main/doc/model.md#units).

Questions for PhET-iO instrumentation:

* Which Properties specifically have this problem?
* Can we expect the instructional designer to set values in non-standard (non-SI) units?
* How should non-standard units be documented? The `units` option does not support non-standard units. Can we use `phetioDocumentation`?  Should something be noted in examples.md?
* Should we create DerivedProperties that show the values in SI units? If so, where should they live in the Studio Tree?

**Comment by pixelzoom** [comment]
Here's my attempt to identify the Properties that are not in standard units. @AgustinVallejo are there any others?

Body:
* massProperty
* radiusProperty
* positionProperty
* velocityProperty
* accelerationProperty
* forceProperty

SolarSystemCommonModel:
* timeProperty

**Comment by arouinfar** [comment]
> Can we expect the instructional designer to set values in non-standard (non-SI) units?

I don't think so. Looking through the units section of model.md, I think mass is the only easily explainable conversion factor. I cannot imagine asking clients to convert any of the other units on their own.

> How should non-standard units be documented? The units option does not support non-standard units. Can we use phetioDocumentation? Should something be noted in examples.md?

A combination of `phetioDocumentation` and examples.md seems fine to me.

> Should we create DerivedProperties that show the values in SI units? If so, where should they live in the Studio Tree?

Students are able to directly set the mass, position, and velocity of the bodies. Clients should be able to change these with the API, so I don't think DerivedProperties will work for these, but for things like `forceProperty` that seems appropriate.

**Comment by pixelzoom** [comment]
This issue is on hold, pending investigation in https://github.com/phetsims/my-solar-system/issues/252 of whether we can convert model Properties to standard units.

**Comment by AgustinVallejo** [comment]
Removing the on-hold tag, these properties should be ready to be standarized.

**Comment by pixelzoom** [comment]
Since #252 worked out nicely, this issue is now a non-issue.  And we're adding units to Properties in #208 and #244. So I think this issue can be closed.
