### ISSUE TITLE
Convert to static creation of view elements related to Body.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#230]
The view components related to Body are currently created and disposed dynamically, using `ViewSynchronizer`, a pattern that was apparently created by @jonathanolson.

Relevant code in MySolarSystemScreenView:

```ts
    this.bodyNodeSynchronizer = new ViewSynchronizer( this.bodiesLayer, ( body: Body ) => {
      return new BodyNode( body, this.modelViewTransformProperty, {
        speedVisibleProperty: this.visibleProperties.speedVisibleProperty,
        mapPosition: this.constrainBoundaryViewPoint.bind( this ),
        soundViewNode: this
      } );
    } );

    const velocityVectorSynchronizer = new ViewSynchronizer( this.componentsLayer, this.createDraggableVectorNode );

    const forceVectorSynchronizer = new ViewSynchronizer( this.componentsLayer, ( body: Body ) =>
      new VectorNode( body, this.modelViewTransformProperty, this.visibleProperties.gravityVisibleProperty, body.forceProperty, model.forceScaleProperty, {
        fill: SolarSystemCommonColors.gravityColorProperty,
        constrainSize: true
      } )
    );

    // The ViewSynchronizers handle the creation and disposal of Model-View pairs
    const trackers = [
      this.bodyNodeSynchronizer, velocityVectorSynchronizer, forceVectorSynchronizer
    ];
```

Per 10/5/23 PhET-iO design meeting, it is undesirable to have these view elements be dynamic.  They should be converted to static elements, which are always present in the Studio Tree.  And related to https://github.com/phetsims/my-solar-system/issues/222, we should only create view elements for model elements as appropriate for the sim/screen.

This static pattern is consistent with harmonics in Fourier, cups in Mean Share and Balance, and other sims that have a small maximum number of model elements, some of which may be irrelevant depending on other settings in the simulation.

**Comment by pixelzoom** [comment]
@AgustinVallejo and I identified this as relatively high priority, so I'll label it as such.

**Comment by pixelzoom** [comment]
Lots of work in the above commits.   ViewSynchronizer is no longer used to dynamically add/remove the Nodes related to active Body elements.  Instead, all of those Nodes are created at startup, and their visibility is controlled back on whether they are active.   And those Nodes are also instrumented.

Here's the most important code, from MySolarSystemScreenView:
 
```ts
    model.availableBodies.forEach( body => {

      const bodyNode = new BodyNode( body, this.modelViewTransformProperty, {
        ...
        visibleProperty: body.isActiveProperty, // visible when the associated Body is active
        tandem: bodyNodesTandem.createTandem( `body${body.index}Node` )
      } );
      this.bodiesLayer.addChild( bodyNode );

      const velocityVectorNode = new DraggableVelocityVectorNode( body, this.modelViewTransformProperty, {
        ...
        visibleProperty: DerivedProperty.and( [ body.isActiveProperty, this.visibleProperties.velocityVisibleProperty ] ),
        tandem: velocityVectorsTandem.createTandem( `velocityVector${body.index}Node` )
      } );
      this.componentsLayer.addChild( velocityVectorNode );

      const forceVectorNode = new VectorNode( body, this.modelViewTransformProperty, body.forceProperty, model.forceScaleProperty, {
        ...
        visibleProperty: DerivedProperty.and( [ body.isActiveProperty, this.visibleProperties.gravityVisibleProperty ] ),
        tandem: forceVectorsTandem.createTandem( `forceVector${body.index}Node` )
      } );
      this.componentsLayer.addChild( forceVectorNode );
    } );
```

@AgustinVallejo please have a look, close if OK.  Also happy to walk through this in pairing.

**Comment by pixelzoom** [comment]
In the above commits, Nodes that are no longer dynamically added/removed were marked as `isDisposable: false`, and their dispose-related code was removed because it will no longer be executed/tested.

**Comment by AgustinVallejo** [comment]
Was only curious as to how they would be displayed in studio, and now I see the four bodies are listed even though not all are on screen. I think this was the right behavior as we had discussed, but would like to chat about it to better understand it. Closing but noting to ask you whenever possible.
