### ISSUE TITLE
Disabling input for bodies and/or their velocity vectors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#231]
Related to https://github.com/phetsims/my-solar-system/issues/224 ... From the [PhET-iO Design](https://docs.google.com/document/d/1FTpTD34mptfTyCIun6cHbJarS9WQICkH3n_isCg30uI/edit?pli=1) document:

It should be possible to disable interaction with the bodies and/or their velocity vectors. Each body and velocity vector should have an `inputEnabledProperty`.

When inputEnabledProperty=false:
- [x] Bodies: Disable interaction with the corresponding Position cells in the “More Data” view.
- [x] Velocity: Hide the (V) circle at the tip of the vector. 
- [ ] ~~Velocity: Disable interaction with the corresponding Velocity cells in the “More Data” view.~~

**Comment by pixelzoom** [comment]
The ultimate phetioIDs are like to change, but I believe this is working now.

For example in the Lab screen, to disable interaction with body1:

`mySolarSystem.labScreen.view.planetarySystemNodes.body1Node.inputEnabledProperty = false`

To disable with body1's velocity vector:

`mySolarSystem.labScreen.view.planetarySystemNodes.velocityVector1Node.inputEnabledProperty = false`

**Comment by pixelzoom** [comment]
Discussed with @arouinfar and @AgustinVallejo.    We decided NOT to link the `inputEnabledProperty` status of these draggable things to the `inputEnabledProperty` status of the display in `valuesPanel` because:

* It makes it impossible to disable input for one or the other, but not both, which may be desirable.
* It's difficult, would involve adding many new Properties to the model, and would be a complicated API to explain.

So this is ready for review by @arouinfar. Feel free to close if OK.

**Comment by arouinfar** [comment]
I reviewed on main and the behavior looks good to me. Thanks for documenting in #223!

Closing.
