### ISSUE TITLE
Support for client-configurable systems

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#233]
Related to https://github.com/phetsims/my-solar-system/issues/224... From the [PhET-iO Design](https://docs.google.com/document/d/1FTpTD34mptfTyCIun6cHbJarS9WQICkH3n_isCg30uI/edit?pli=1) document:

**Needs more investigation.**

The existing preset systems (e.g. Trojan Asteroids) in the simulation should not be customizable by clients. 

The “Custom” system is overwritten every time students make changes (moving a body, changing mass, etc.) There are too many pathways a client would need to shut down to use the “Custom” option to create a static configuration.

Preset systems are JSON objects.

Possible Pathways:
Create client-configurable systems with corresponding ListBoxItem hidden by default (making it hidden in phet-brand). 
Clients could set the mass, position, and velocity of each object using Studio and then create a Standard wrapper.
Other systems are JSON objects, should clients be able to supply their own JSON? Does it need to be exported or set in Studio? (Model vs. view units could make this tricky.)

**Comment by pixelzoom** [comment]
I'll start giving this some thought about how we can add this feature.

**Comment by pixelzoom** [comment]
I have an uncommitted proposal that I'll shared with @AgustinVallejo at our pairing session later today.

**Comment by pixelzoom** [comment]
Providing an open-ended number of client-configurable orbital systems would be difficult.  I asked @arouinfar if 4 systems would be sufficient, and she said yes.  And if a client asks for more in the future, the solution that I'm thinking of will be able to accommodate adding additional systems.

**Comment by pixelzoom** [comment]
@AgustinVallejo and I made great progress on this today in the above commits.  

Remaining work:
- [ ] Revisit BodyInfoIO, to possibly reduce the number of fields in the JSON that the client sees
- [ ] Summarize the approach and have @arouinfar review

**Comment by pixelzoom** [comment]
Notes to myself about how the client will use this feature.

There are 4 configurable systems, numbered 1-4.   To configure system 1:

* Display the system in `orbitalSystemComboBox` by setting `phetioOrbitalSystem1Item.visibleProperty` to true.
* Change the combo box label by setting `phetioOrbitalSystem1Property`.
* Configure the system by getting and setting the value of `phetioOrbitalSystem1Property`. (Provided details on how to edit the JSON.)

**Comment by pixelzoom** [comment]
I reviewed the approach for this feature with @arouinfar, and she liked it.   We changed the names of some things in the above commits, so that translators don't encounter keys with "phetio", like "phetioOrbitalSystem1".

A few notes:
* We should definitely get `massRange` and `tandemName` out of the JSON that the client edits.
* Setting values for velocity will be tricky for the client, because they are in km/s (and are scaled?) The instructions could tell the client to set up their system first using "Custom", then use the values that they see in the Values panel to configure their system.

**Comment by pixelzoom** [comment]
Before making additonal changes that involve BodyInfo, I published baseline dev versions, so we can compare before & after behavior.

* https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.4/phet/my-solar-system_all_phet.html
* https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.4/phet-io/

* https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.4/phet/keplers-laws_all_phet.html
* https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.4/phet-io/

**Comment by pixelzoom** [comment]
Modifying BodyInfo was full of landmines.  So I created a subset, BodyInfoSubset, that exposes only the mass, position, and velocity fields.  It's private to PhetioOrbitalSystemProperty.ts, which now encapsulates the complete solution for this feature.

**Comment by pixelzoom** [comment]
@arouinfar This is now ready for you to review.  Here's a description of the feature. Feel free to steal bits of this for example.md, if you find any of it useful.

---
There are 4 "client-configurable orbital systems", numbered 1-4.  They will behave like the other presets that are selectable via the combo box in the Lab screen.  But by default, they are not visible in that combo box. 

Configuring any of these 4 systems is similar.  I'll describe how to configure system 1.

1. Make the system visible in the combo box by setting `orbitalSystem1Item.visibleProperty` to true. The default is false.
2. Change the combo box label by setting `orbitalSystem1StringProperty` to the desired name of the system. The default is "Orbital System 1".
3. Configure the system by getting and setting the value of `orbitalSystem1Property` in Studio.

About the value of these Properties...  If you press the "Get Value" button in Studio, you'll see this default value, which looks like this:

```json
[
  {
    "mass": 100,
    "position": {
      "x": -3,
      "y": 0
    },
    "velocity": {
      "x": 0,
      "y": 10
    }
  },
  {
    "mass": 100,
    "position": {
      "x": -1,
      "y": 0
    },
    "velocity": {
      "x": 0,
      "y": 10
    }
  },
  {
    "mass": 100,
    "position": {
      "x": 1,
      "y": 0
    },
    "velocity": {
      "x": 0,
      "y": 10
    }
  },
  {
    "mass": 100,
    "position": {
      "x": 3,
      "y": 0
    },
    "velocity": {
      "x": 0,
      "y": 10
    }
  }
]
```

This is an array of 4 identical data structures, for 4 bodies.  Each data structure is delimited with "{...}", and specifies the mass, position, and velocity for a body.  Change these values as desired. If you want fewer than 4 bodies, then delete one or more of the data structures.  (You must have a least 1 body, and not more than 4 bodies.) For example, here's a system with 2 bodies:

```json
[
  {
    "mass": 250,
    "position": {
      "x": 0,
      "y": 0
    },
    "velocity": {
      "x": 5,
      "y": 5
    }
  },
  {
    "mass": 100,
    "position": {
      "x": 2,
      "y": 0
    },
    "velocity": {
      "x": 0,
      "y": 10
    }
  }
]
```

Press the "Set Value" in Studio when you've finished editing the JSON.

Note that it may be easist to manually configure and test a system in the sim, which 'Custom' is selected, by dragging the bodies and velocity vectors, and/or editing the values shown in the panel at lower-left (with the "More Data" checkbox checked).   When your system looks and behaves as desired, note the mass, position, and velocity values, and use them to edit `orbitalSystem1Property` or one of the other 4 such Properties.

**Comment by arouinfar** [comment]
Thanks for the write-up @pixelzoom. Everything is working well in main, including the recommended flow.

The only thing I might add is some notes about data validation/range.
* Values < 1 need to include a zero preceding the decimal, e.g. `.5` is rejected but `0.5` will be accepted.
* Note that vector quantities are not validated, which is why we recommend testing things in "Custom" first.
