### ISSUE TITLE
Restart logic is buggy

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#236]
When I restart the sim, it-s trying to unnecessarily follow the center of mass

**Comment by pixelzoom** [comment]
Reopening. I think this may still be buggy.  To reproduce:

1. Start the sim, go to Intro screen.
2. Press Play button on time control.
3. Press Restart button on time control. The bodies move to the correct "restart" positions. But the "Follow Center of Mass" button appears. Why?

**Comment by pixelzoom** [comment]
We also noted that `centerOfMass.velocityProperty` is not zero when the orbital system is in its initial state.  It should zero.

**Comment by AgustinVallejo** [comment]
I'll move this discussion to https://github.com/phetsims/my-solar-system/issues/274 so we can also ask QA to test when we're done. Closing this one.
