### ISSUE TITLE
Base level PhET-iO instrumentation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#237]
This issue is for commiting changes for "base level" PhET-iO instrumentation that are not covered by some other GitHub issue. 

This includes a first pass at:

- [x] tandems
- [x] phetioDocumentation
- [x] phetioReadOnly
- [x] phetioFeatured
- [x] units & ranges
- [x] grouping elements in the Tree
- [x] linked elements

**Comment by pixelzoom** [comment]
This is ready to close.  I'll review with @AgustinVallejo in our pairing session today, then close the issue.

We'll still need to complete https://github.com/phetsims/my-solar-system/issues/233 before this is ready to go to @arouinfar for review of the Studio tree.

**Comment by pixelzoom** [comment]
@AgustinVallejo and I reviewed. He provided a description of each of the things in https://github.com/phetsims/my-solar-system/issues/237#issue-1938741779, passed "with flying colors".   So closing this issue.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by pixelzoom** [comment]
TODO addressed. Closing again.
