### ISSUE TITLE
Instrument Body and related parts of SolarSystemCommonModel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#240]
Body is partially instrumented, but there is more to do.   Since it is one of the most important model classes, and will involve a custom IOType, I'll track changes in this issue.

**Comment by pixelzoom** [comment]
SolarSystemCommonModel has this field:

```ts
  // The set of Body instances in availableBodies that are active (body.isActive === true)
  public readonly bodies: ObservableArray<Body>;
```

`bodies` needs to be stateful, and thererfore needs to be instrumented. In order to do that, we need to provide a tandem for the ObservableArray, and tell PhET-iO what type of elements the array contains.  Since it's an array of `Body`, we therefore need to define an associated custom IOType, `BodyIO` in Body.ts:

```ts
  /**
   * BodyIO implements 'Reference type serialization', as described in the Serialization section of
   * https://github.com/phetsims/phet-io/blob/main/doc/phet-io-instrumentation-technical-guide.md#serialization
   * Reference type serialization is appropriate because all Body instances are created at startup, and exist
   * for the lifetime of the simulation.
   */
  public static readonly BodyIO = new IOType<Body, BodyStateObject>( 'BodyIO', {
    valueType: Body,
    supertype: ReferenceIO( IOType.ObjectIO )
  } );
```

The instrumentation of `bodies` then looks like this:

```ts
    this.bodies = createObservableArray( {
      tandem: options.tandem.createTandem( 'bodies' ),
      phetioType: createObservableArray.ObservableArrayIO( Body.BodyIO ),
      phetioDocumentation: 'The set of Body elements that are currently active, and thus visible on the screen'
    } );
```

@AgustinVallejo please take a look at this aspect of instrumentation, and let me know if you have questions. Required reading is https://github.com/phetsims/phet-io/blob/main/doc/phet-io-instrumentation-technical-guide.md#serialization.

**Comment by pixelzoom** [comment]
The Studio tree currently looks like this for the Lab screen:

<img width="255" alt="screenshot_2821" src="https://github.com/phetsims/my-solar-system/assets/3046552/a8391dc5-790b-4436-94d0-dc92408ec8de">

I think it would be preferrable to have the complete set of Body elements under `bodies`, and the array of active Body elements be named `activeBodies`, like this:

<img width="250" alt="screenshot_2822" src="https://github.com/phetsims/my-solar-system/assets/3046552/f438a91d-3a10-41b5-b171-ad2fedde9bc8">

@arouinfar Do you agree?

In addition to changing the tandem names, these fields in SolarSystemCommonModel should be renamed, which I think would be an improvement to the code.

```diff
  // The complete set of Body instances, active and inactive
-  public readonly availableBodies: Body[];
+ public readonly bodies: Body[];

  // The set of Body instances in availableBodies that are active (body.isActive === true)
-  public readonly bodies: ObservableArray<Body>;
+  public readonly activeBodies: ObservableArray<Body>;
```

**Comment by pixelzoom** [comment]
As I've instrumented bits of keplers-laws, I've noticed references to "sun" and "planet" in the code.  So I'm guessing that rather than "body1" and "body2" in the Studio Tree, we'll want to see "sun" and "planet".  In the above commit I added an optional `tandemName` to BodyInfo to make that possible, and used it in KeplersLawsModel.

**Comment by pixelzoom** [comment]
I discussed https://github.com/phetsims/my-solar-system/issues/240#issuecomment-1758666153 with @arouinfar, and she would like to make the proposed change.  I'll make it so.

**Comment by AgustinVallejo** [comment]
Also sounds good to me! Still getting to understand IO types

**Comment by pixelzoom** [comment]
Summary of renames in the above commits:
* bodies => activeBodies
* availableBodies => bodies

**Comment by pixelzoom** [comment]
I made a final pass through Body and SolarSystemCommonModel, added phetioDocumentation, and instrumented one NumberProperty that I had missed.  This is ready to close.
