### ISSUE TITLE
Measuring tape units are not localized.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#241]
The measuring tape displays value with 'AU' units:

<img width="159" alt="screenshot_2823" src="https://github.com/phetsims/my-solar-system/assets/3046552/6a0b0273-ef25-4133-a170-a11adae3bd1d">

There's a bug in SolarSystemCommonScreenView. The units 'AU' are hardcoded, not localized (so not translatable):

```ts
   const measuringTapeUnitsProperty = new Property( { name: 'AU', multiplier: 0.01 } );

   this.measuringTapeNode = new MeasuringTapeNode( measuringTapeUnitsProperty, {
```

So `measuringTapeUnitsProperty` need to be a DerivedProperty that updates when `SolarSystemCommonStrings.units.AUStringProperty` changes.

**Comment by pixelzoom** [comment]
Fixed in the above commit.   This can be confirmed by running with `?stringTest=dynamic`, and verifying that the units on the tape measure change as expected when using the left/right arrow keys to shorten/lengthen AUStringProperty.

@AgustinVallejo please review, close if OK.

**Comment by AgustinVallejo** [comment]
Missed this one when using translatable strings, thanks!
