### ISSUE TITLE
`DEFAULT_SOUND_OUTPUT_LEVEL` is almost never used as the default.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#243]
In SolarSystemCommonConstants:

```ts
  DEFAULT_SOUND_OUTPUT_LEVEL: 0.1,
```

There are 10 usages of `SolarSystemCommonConstants.DEFAULT_SOUND_OUTPUT_LEVEL`. 

9 of those usages are `2 * SolarSystemCommonConstants.DEFAULT_SOUND_OUTPUT_LEVEL`, and only 1 does not change the value.

Questions:

(1) Is this usage in BodyNode correct, or should it also be `2 *` ?

```ts
    this.soundClip = new SoundClip( bodySounds[ body.index - 1 ], {
      initialOutputLevel: SolarSystemCommonConstants.DEFAULT_SOUND_OUTPUT_LEVEL,
      loop: true
    } );
```

(2) Should `DEFAULT_SOUND_OUTPUT_LEVEL` be changed to `0.2`, and the `2 *` removed throughout?

**Comment by AgustinVallejo** [comment]
Good input, solved in the above commits. Closing!
