### ISSUE TITLE
Cleanup related to DraggableVectorNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#245]
The sole usage is in SolarSystemCommonScreenView:

```ts
this.createDraggableVectorNode = ( body: Body, options?: DraggableVectorNodeOptions ) => {
      return new DraggableVectorNode(
        body,
        this.modelViewTransformProperty,
        this.visibleProperties.velocityVisibleProperty,
        body.velocityProperty,
        body.positionProperty,
        1,
        SolarSystemCommonStrings.VStringProperty, {
     ...
  } );
```

- [x] `DraggableVectorNode` should be renamed to `DraggableVelocityVectorNode`, because (as the documentation states) it is specific to velocity:

```ts
/**
 * Used to show the draggable velocity vectors.
 *
```

- [x] Constructor parameter `scale: number` is not used.  It should be deleted.

- [x] Constructor parameter `labelText` is incorrectly named; it's a String Property.  It's also unnecessary, because the value is always the same, so it can be removed.

- [x] Constructor parameters `vectorProperty` and `basePositionProperty` are unnecessary and can be removed.  Since `body` is a parameter, their values are `body.velocityProperty` and `body.positionProperty` respectively. 

- [x] Option value `fill: SolarSystemCommonColors.velocityColorProperty` is always the same, so can me moved inside the constructor.

- [x] `createDraggableVectorNode` is not necessary, and is not consistent with how other dynamic view elements (`BodyNode`, `VectorNode`) are created.  So I recommend removing it, and using a consistent pattern.   This will make it easier to do PhET-iO instrumentation.

**Comment by pixelzoom** [comment]
Done in the above commits.  I think this puts us in a better position to address https://github.com/phetsims/my-solar-system/issues/230, since creation of BodyNode, VectorNode, and DraggableVelocityVectorNode is handled uniformly. 

@AgustinVallejo feel free to have a look, close if OK.

**Comment by AgustinVallejo** [comment]
Cool! I think this was one of the first parts of the code I began working on, so it was definitely a bit sloppy. Thanks for fixing
