### ISSUE TITLE
Revise model.md and implementation-notes.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#246]
... for both my-solar-system and keplers-laws.  After completing PhET-iO instrumentation, we will have renamed and relocated some things.  And we definitely need to revise the "Memory Management" sections as the result of https://github.com/phetsims/my-solar-system/issues/230.

**Comment by pixelzoom** [comment]
We're at a point where we have not been changing the names of things, or moving things around, so this can proceed.

@AgustinVallejo will take a first pass it.   Then he'll assign back to be to add a PhET-iO section to implementation-notes.md.

**Comment by AgustinVallejo** [comment]
Assigning back to @pixelzoom to add PhET-iO sections

**Comment by pixelzoom** [comment]
In the above commits, I added a **PhET-iO** section, and fixed some source code links so that they point to "latest" in main, instead of specific shas.

**Comment by pixelzoom** [comment]
In the above commit, a expanded the **Model** section, and I added a **View** section.  @AgustinVallejo please have a look, feel free to change.  OK to close when you're done.

**Comment by AgustinVallejo** [comment]
Read through the changes and they seem nice, thanks. Closing
