### ISSUE TITLE
MySolarSystemModel override reset is unnecessary

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#247]
In MySolarSystemModel:

```ts
  public override reset(): void {
    super.reset();
    this.userControlledProperty.reset();
  }
```

This override seems unnecessary. MySolarSystemModel does not own `userControlledProperty`, so should not be responsible for resetting it. And the parent class SolarSystemCommonModel already handles resetting `userControlledProperty` in its `reset` method.  @AgustinVallejo can this override be deleted? If so, go ahead and delete it.

**Comment by AgustinVallejo** [comment]
Good catch! Closing this now
