### ISSUE TITLE
Initializing Sound Mapping in My Solar System

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/my-solar-system#25]
Here are four looping audio files to test out with the four bodies. 
https://drive.google.com/drive/folders/1Fb_UlUXWZOlZe2C5r53XpIkGd-rzQxbs?usp=sharing

- Bodies_Strings_e3.wav
- Bodies_Brass_C3.mp3
- Bodies_Brass_C3.wav
- Bodies_Flute_g3.mp3
- Bodies_Flute_g3.wav
- Bodies_Organ_b3.mp3
- Bodies_Organ_b3.wav
- Bodies_Strings_e3.mp3

We use .mp3 since is has a smaller footprint but I always add .wav just in case we need to save a master version.

You can view the mockup video here.
[Orch_Bodies_My_Solar_System_Mockup](https://drive.google.com/file/d/1yZ32Ns5sOEhOaULS_unY9fKn2QK8Cp5y/view?usp=sharing)

**Comment by Ashton-Morris** [comment]
Reach out to me if you have any questions!

**Comment by Ashton-Morris** [comment]
Adding two more options for e3 since it was sounding a bit off. Woodwinds is the softer sounding option of the two.

- Bodies_Strings_e3_v2.wav
- Bodies_Strings_e3_v2.mp3
- Bodies_Woodwinds_e3.wav
- Bodies_Woodwinds_e3.mp3

**Comment by AgustinVallejo** [comment]
Closing because initial sound mapping is already in place. Good job!
