### ISSUE TITLE
InteractiveNumberDisplay `inputEnabledProperty`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#253]
InteractiveNumberDisplay needs `enabledProperty` instrumented.  Setting it to false should not reduce opacity. When disabled, it should look and behave like a non-interactive NumberDisplay.

Related to https://github.com/phetsims/my-solar-system/issues/231... For position and velocity usages in ValuesPanel, `enabledProperty` also needs to be derived from `inputEnabledProperty` for draggable parts of BodyNode.

**Comment by pixelzoom** [comment]
Once I got into this, I realized that `enableProperty` is not what we want here. Since there is no change to the look of the display, we want to use `inputEnabledProperty` to control whether the display is interactive.  That has been done in the above commit by adding `phetioInputEnabledPropertyInstrumented: true`.

**Comment by pixelzoom** [comment]
Discussed with @arouinfar and @AgustinVallejo in a meeting this morning. `inputEnabledProperty` is appropriate and is behaving as desired.  I've also feature `inputEnabledProperty` as requested in the above commits.

**Comment by arouinfar** [comment]
Thanks @pixelzoom! Looks good on main, closing.
