### ISSUE TITLE
bodyAddedEmitter and bodyRemovedEmitter are redundant.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#256]
In SolarSystemCommonModel:

```ts
  // Emitters that fire when a body is added or removed from activeBodies
  public readonly bodyAddedEmitter: TinyEmitter = new TinyEmitter();
  public readonly bodyRemovedEmitter: TinyEmitter = new TinyEmitter();
```

These Emitters seem redundant - why are they needed? `activeBodies` is an ObservableArray, which provides Emitter for exactly this purpose -- see `addItemAddedListener` and `addItemRemovedListener`.

**Comment by AgustinVallejo** [comment]
Done in the above commits
