### ISSUE TITLE
Visual artifacts on path after scale change

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#257]
After implementing https://github.com/phetsims/my-solar-system/issues/252, I noticed the path is being drawn slightly different now. It kinda bugs me but also it seems the artifact was also happening before. Using another issue in case this'll be deferred but I think it's work looking into.

The relevant code is in `PathCanvasNode.ts`

![image](https://github.com/phetsims/my-solar-system/assets/37052186/4dd1d7cc-863a-4607-9497-15a8d7399ff3)

Could it have to do with the fact that the MaxPathLength in PathCanvasNode is different from the MaxPathLength (now MAX_PATH_DISTANCE) used in Body.ts?

**Comment by pixelzoom** [comment]
I'll poke around to see if I can identify this problem.

**Comment by AgustinVallejo** [comment]
Edited the `stepOnce()` function in SolarSystemCommonModel and managed to even get a better path behavior than the baseline:
![image](https://github.com/phetsims/my-solar-system/assets/37052186/d83e797d-7ee2-4232-b34e-0aa64a9ef803)

However, what that function does seems a bit confusing and the comment explanation doesn't clear things much. It's possible the redundancy there, as well as the one inside the NumericalEngine `run()` method (see https://github.com/phetsims/my-solar-system/blob/9c4d1854172c4997e9fd7e053867cb3c42a49988/js/common/model/NumericalEngine.ts#L84) are doing the same thing but in different places. I think it's worth investigating and possibly unifying, maybe creating it's own issue. What do you think @pixelzoom? Please create it and close this one if you agree and consider the path thing to be solved.

**Comment by pixelzoom** [comment]
> ... What do you think @pixelzoom? Please create it and close this one if you agree and consider the path thing to be solved.

I'll take a look.

**Comment by pixelzoom** [comment]
The code that @AgustinVallejo is referring to is:

```ts
    // Limit the number of steps to 50 per frame
    const numberOfSteps = Math.ceil( adjustedDT / 0.0002 );
    adjustedDT /= numberOfSteps;
```

This does not immediately make sense to me either.

**Comment by pixelzoom** [comment]
In the above commit, @AgustinVallejo and I added a marginally better comment for numberOfSteps.  

The arbitrary 0.002 still gives @AgustinVallejo the creeps, so he's going to look at a better solution.

**Comment by AgustinVallejo** [comment]
I think this discussion should be continued in https://github.com/phetsims/my-solar-system/issues/279, since the path artifact has been solved. Would you agree @pixelzoom? If so, please close

**Comment by pixelzoom** [comment]
Yes, agreed. Closing.

**Comment by AgustinVallejo** [comment]
Although this was solved, I wanted to chime in with insights as to why it was happening.

After working in #279, I realized the `0.02` came from 1/50, the duration of a frame if we're aiming for 50fps, as the old comment said. The whole `Math.ceil` ordeal was pretty much making sure every step of the model was happening at least at 0.02s. I remember talking with @jonathanolson about where that dt came from, and that for some computers, Joist might decide for a bigger dt (somebody correct me if I'm wrong).

However, the main problem here is that 50fps is not smooth enough for My Solar System. As an example, the Moon-Planet system takes about 5 seconds to complete an orbit around the sun, during which the moon does about 7 complete orbits. Thus, every moon orbit has about 35 frames for drawing the curve, which will inevitably look choppy (even in the baseline version it did)

In the following commit I'm setting the desired fps to 5000 (the previous solution was setting the magic number to 0.0002)

**Comment by pixelzoom** [comment]
Let's make sure that your explanation in https://github.com/phetsims/my-solar-system/issues/257#issuecomment-1787882593 makes it into the code comments.

**Comment by pixelzoom** [comment]
Lots of good work on this during our pairing session today, see the above commits.  Specifically, we cleaned up the logic and documentation of for how dt is scaled in `stepOnce`, before it is passed to `engine.run`.

This feels ready to close, so...
