### ISSUE TITLE
Move Properties for measuring tape to the model.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#258]
In SolarSystemCommonScreenView:

```ts
    // Add the MeasuringTapeNode
    this.measuringTapeNode = new MeasuringTapeNode( measuringTapeUnitsProperty, {
      basePositionProperty: new Vector2Property( new Vector2( 0, 100 ) ),
      tipPositionProperty: new Vector2Property( new Vector2( 100, 100 ) ),
```

For PhET-iO, the Properties for the measuring tape should appear in the model.  So we'll need to create something like SolarSystemCommonMeasuringTape, and instantiate it in SolarSystemCommonModel.

**Comment by pixelzoom** [comment]
Done in the above commits. Screenshot below shows the Studio Tree.  Over to @AgustinVallejo to review, close if OK.

<img width="262" alt="screenshot_2830" src="https://github.com/phetsims/my-solar-system/assets/3046552/4ed7b9e0-553a-4cd6-a8f2-c93fa98bf06c">

**Comment by AgustinVallejo** [comment]
Looks good, thanks!
