### ISSUE TITLE
Add PhET-iO only Properties

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#261]
Some PhET-iO only Properties that are requested in the PhET-iO Design document:

- [ ] ~~gravityForceMagnitudeProperty (NumberIO, read-only)~~
- [x] speedProperty (NumberIO, read-only)
- [ ] ~~distanceProperty (for each pair of objects, read-only)~~

**Comment by pixelzoom** [comment]
Note to self: The sim has been displaying speed (see "Speed" checkbox) so where has it been deriving speed?

**Comment by pixelzoom** [comment]
Discussed with @arouinfar ...

We will not add `gravityForceMagnitudeProperty` because `gravityForceProperty` is in non-standard units and is "for internal use only".

We will not add `distanceProperty` for each pair for bodies. It will result in a mini-explosion of Properties, and it's unclear whether it's necessary.  `positionProperty` is available for all Body elements, and the PhET-iO client should be able to manage computing the distance between points.

**Comment by pixelzoom** [comment]
`speedProperty` was the only Property added, and it turned out to be useful in the displaying the speed for the bodies.  It's featured, and it's readonly because it's derived.  

@arouinfar please review. Close if OK.

**Comment by arouinfar** [comment]
@pixelzoom something's not quite right. When I select `speedProperty` in Studio, the current value is always `null` regardless of the state in the sim.

For example:
![image](https://github.com/phetsims/my-solar-system/assets/8419308/d4ac2a2e-35de-43bd-97e7-48f45e4e4384)

**Comment by arouinfar** [comment]
Looks good, thanks!
