### ISSUE TITLE
Unused parameter to`loadBodyInfo`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#262]
In SolarSystemCommonModel:

```ts
  public loadBodyInfo( bodiesInfo: BodyInfo[], preventCollision = false ): void {
```

`loadBodyInfo` is never called with a `preventCollision` argument, so it's always `false`. 

Is that a sign that a bug might have been introduced? Like maybe when we made changes related to `defaultBodyInfo` and `startingBodyInfo`.

Or is that feature no longer needed? If that's the case, then the `preventCollision` parameter can be removed, and the code inside `loadBodyInfo` that is related to `preventCollision` be deleted (because it's never being exercised.)

**Comment by pixelzoom** [comment]
Reopening.  In https://github.com/phetsims/solar-system-common/commit/c3fe9054987c4e64b6bd58c4837311bbce16fbb0, you made this change:

```diff
 bodies.forEach( body => {
      if ( body !== this && this.isOverlapping( body ) ) {
        // If it's going to collide, arbitrarily move it 100 pixels up
-        this.positionProperty.value = this.positionProperty.value.plus( new Vector2( 0, 100 ) );
+        this.positionProperty.value = this.positionProperty.value.plus( new Vector2( 0, 1 ) );
        this.preventCollision( bodies );
      }
    } );
```

The documentation above the change is now incorrect ("100 pixels up").  And we're in model coordinates, so it should be "1 AU up", not pixels, correct?

**Comment by AgustinVallejo** [comment]
My bad, fixed the logic but not the docs. Closing now
