### ISSUE TITLE
Measuring tape is broken

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#263]
Probably related to changes in https://github.com/phetsims/my-solar-system/issues/252 ...

The measuring tape's initial `basePositionProperty` value is broken, shown in the screenshot below. The initial `tipPositionProperty` is also broken. None of the "tape" is extended.

Even worse, if the Reset All button is pressed, and the "Measuring Tape" checkbox is check, the measuring tape is nowhere to be seen.

<img width="734" alt="screenshot_2833" src="https://github.com/phetsims/my-solar-system/assets/3046552/d7553b5b-354c-473a-8b39-6b03b18faedf">

**Comment by pixelzoom** [comment]
I noticed that `measuringTapeNode.reset` was being called. That should not be the case, see https://github.com/phetsims/scenery-phet/issues/822.   Corrected in the above commit.

**Comment by pixelzoom** [comment]
The above commit fixes the initial positions for the measuring tape.   I compared to these baseline versions:

https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.1/phet/my-solar-system_en_phet.html
https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-dev.1/phet/keplers-laws_en_phet.html

Over to @AgustinVallejo to verify. Close if OK.

**Comment by AgustinVallejo** [comment]
Looks good! Thanks!
