### ISSUE TITLE
How do we communicate where the origin (0,0) is?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#264]
There is nothing in the user interface that shows where the origin (0,0) is.

How does the user know how to set position values in `valuesPanel` when there's no indication of where the origin is?

How do we communicate to the PhET-iO client where the origin is?

@AgustinVallejo suggested (if this important) having bolder grid lines for the x and y axes. 

@arouinfar thoughts?

**Comment by pixelzoom** [comment]
> @AgustinVallejo suggested (if this important) having bolder grid lines for the x and y axes.

The sim is currently using scenery-phet's `GridNode`, which has no API for stroking the axes differently.  So there would be some common-code work here.

**Comment by pixelzoom** [comment]
And GridNode is in fact all one Path.  So we cannot stroke the axes differently.  We'd likely need to draw another set of lines on top of GridNode.

**Comment by pixelzoom** [comment]
@AgustinVallejo is going to handle this issue.  Feel free to assign to me for review when you're done.

**Comment by AgustinVallejo** [comment]
Added this in the above commit, with the addition of moving the grid line to the bottom layer, as it was obstructing the view of the bodies.
Top layer:
![image](https://github.com/phetsims/my-solar-system/assets/37052186/cab09fa5-a407-41ec-98a6-b014581335ef)


Bottom layer:
![image](https://github.com/phetsims/my-solar-system/assets/37052186/e5ce6730-8e86-4509-ba4e-7c91f174c28e)

@arouinfar do you think we should leave it at the bottom, or should I resurface it? Feel free to close if OK.

**Comment by pixelzoom** [comment]
Code looks great, nice job.

My vote would be to put the grid behind the bodies, centerOfMassNode, etc.  I didn't realize that the grid had been in front all this time, but the thicker axes make it obvious.   I'm wondering was it was ever in front -- if it was a conscious decision, it seems odd.

**Comment by pixelzoom** [comment]
One change I would suggest is using a thinner `lineWidth: 0.25` for the primary grid lines. They are currently (by default) `lineWidth: 1`.  They don't need to be so heavy to be effective, and the axes (`lineWidth: 2`) do not stand out enough.  See screenshots below for comparisons.

@arouinfar @AgustinVallejo thoughts?

In SolarSystemCommonGridNode, that would be:

```diff
      gridNodeOptions: {
        stroke: SolarSystemCommonColors.gridIconStrokeColorProperty,
+       lineWidth: 0.5
      },
```

`lineWidth: 1`:
<img width="1091" alt="screenshot_2857" src="https://github.com/phetsims/my-solar-system/assets/3046552/f6562ced-8160-4931-927c-f81e8d2fa220">

`lineWidth: 0.5`
<img width="1085" alt="screenshot_2856" src="https://github.com/phetsims/my-solar-system/assets/3046552/d634d4fb-7603-487a-8d33-d97a3ef3f67c">

`lineWidth: 1`
<img width="1089" alt="screenshot_2858" src="https://github.com/phetsims/my-solar-system/assets/3046552/a02f6cbd-25ca-445f-a742-b792177ae4e9">

`lineWidth: 0.5`
<img width="1088" alt="screenshot_2859" src="https://github.com/phetsims/my-solar-system/assets/3046552/4b1db15b-f54e-4fef-bd61-a837de8e378a">

**Comment by pixelzoom** [comment]
@AgustinVallejo FYI...

In https://github.com/phetsims/solar-system-common/commit/1d8fc07bc6dee427dd7e0138d355d789e1c391fd I pushed a fix that was crashing Studio.  phetioID 'gridNode' was being used in 2 places.

In https://github.com/phetsims/solar-system-common/commit/054c0362d8b75f361c38abcebf287845f716afd0 I fixed a problem with the color of the origin axes. You used `'gray'` and it should be `SolarSystemCommonColors.gridIconStrokeColorProperty`.  I also factored out constants `STROKE`, `GRID_NODE_LINE_WIDTH`, and `ORIGIN_AXES_LINE_WIDTH`

**Comment by arouinfar** [comment]
> One change I would suggest is using a thinner `lineWidth: 0.25` for the primary grid lines. 

Is this a typo @pixelzoom? You mention `0.25` here but include examples using `0.5`. Regardless, the examples with `lineWidth: 0.5` look good to me.

**Comment by pixelzoom** [comment]
Yes, `lineWidth: 0.25` was a type (and maybe a bit of wishful thinking :)

Changed to `lineWidth: 0.5` in the above commit. Closing.

**Comment by pixelzoom** [comment]
Reopening.

(1) There was a bug in SolarSystemCommonGridNode - it was not passing `numberOfGridLines` to GridNode.

(2) We didn't resolve the issue of rendering order, which @AgustinVallejo brought up in https://github.com/phetsims/my-solar-system/issues/264#issuecomment-1783351947.  I think the grid would look better _behind_ the other UI elements, especially with the heavy axes. @arouinfar your opinion?

**Comment by pixelzoom** [comment]
Also FYI... In the above commit, I reduced `numberOfGridLines` from 100 to 60.  Looking at the doc for GridNode, this is actually the number of grid lines _on each side of the center_.   So 100 results in 200 lines.  60 is plenty, as shown in the screenshot below -- fully zoomed out, on the shortest window that's possible with Chrome.

<img width="1115" alt="screenshot_2880" src="https://github.com/phetsims/my-solar-system/assets/3046552/ab426164-031b-4d75-8f7b-04d975d6cf55">

**Comment by pixelzoom** [comment]
Here's the change that would be needed in SolarSystemCommonScreenView to move gridNode to the back:

```diff
    this.interfaceLayer.addChild( gridNode );
    this.bottomLayer.addChild( gridNode );
```

Putting the grid behind bodies, vectors, etc. looks so much better in My Solar System. For example:

<img width="1114" alt="screenshot_2882" src="https://github.com/phetsims/my-solar-system/assets/3046552/0ea6d7f4-8c34-4779-8d71-4e6d14955911">

But I can see when having the grid in front is useful (necessary?) for the Second Law screen of Kepler's Laws. Compare:

<img width="1116" alt="screenshot_2883" src="https://github.com/phetsims/my-solar-system/assets/3046552/15e285d8-08a8-4624-9cc6-1c74d85746a3">
<img width="1115" alt="screenshot_2881" src="https://github.com/phetsims/my-solar-system/assets/3046552/309b7e63-1840-4f22-a6af-ab15b0973764">

**Comment by pixelzoom** [comment]
Oops, I meant to reopen this several comments ago.

**Comment by pixelzoom** [comment]
> But I can see that having the grid in front is useful (necessary?) for the Second Law screen of Kepler's Laws.

Note that we could have the grid behind for My Solar System, and the grid in front for Kepler's Laws.

**Comment by arouinfar** [comment]
>> But I can see that having the grid in front is useful (necessary?) for the Second Law screen of Kepler's Laws.
>
>Note that we could have the grid behind for My Solar System, and the grid in front for Kepler's Laws.

Grid on bottom always looks better, but grid on top is generally more helpful when trying to place the bodies, particularly when the learning goals are more quantitative. In the case of MSS, position can be entered directly, so it's fine to layer the bodies on top of the grid. However, I would leave the grid on top in Kepler's.

**Comment by pixelzoom** [comment]
I DM'ed @arouinfar and she's OK with leaving the grid on top for both sims.  So no more changes needed here, and closing.
