### ISSUE TITLE
InteractiveNumberDisplay has hardcoded `0.1` threshold

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#268]
In InteractiveNumberDisplay, `0.1` should not be hardcoded here, and certainly not in 2 places. And it's relevant only for Mass.

```ts
      numberFormatter: ( n: number ) => {
        if ( providedOptions?.hideSmallValues && Math.abs( n ) <= 0.1 ) {
          return `${MathSymbols.LESS_THAN_OR_EQUAL} 0.1`;
        }
        else {
          return Utils.toFixed( n, decimalPlaces );
        }
      },
```

Using `providedOptions?.hideSmallValues` is also questionable. It only works because the default is `hideSmallValues: false`.

**Comment by AgustinVallejo** [comment]
Looks reasonable, thanks!
