### ISSUE TITLE
Restart button becomes disabled after pressing Clear button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#273]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Safari 17

**Problem description**
For https://github.com/phetsims/qa/issues/997, when the sim is paused, if I press the Clear button, the Restart button becomes disabled. This doesn't happen in 1.3.0-dev.1.

**Steps to reproduce**
1. On either screen, press Play
2. After the body moves a bit, press Pause
3. Press the Clear button

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/00f25bf3-6524-462c-9910-09ba4b8bcb6c

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.3/phet/my-solar-system_all_phet.html
Version: 1.3.0-dev.3 2023-10-26 20:05:04 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language: en-US
Window: 1273x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Good catch, that does seem to be a bug.  I thought the Clear button was the same as the Restart button, but it's not.  The Clear button resets the clock to "0.00 years" but does not change the orbital system.  The Restart button resets the clock to "0.00 years" _and_ resets the orbitial system to the last state change that was made by the user.

I'll have a look.

**Comment by pixelzoom** [comment]
This bug was introduced by changes that I made in https://github.com/phetsims/my-solar-system/issues/250.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @Nancy-Salpepi please verify in main, close if OK.

**Comment by Nancy-Salpepi** [comment]
This looks fixed in main. Closing.

**Comment by Nancy-Salpepi** [comment]
I'm seeing this issue again in https://github.com/phetsims/qa/issues/1008

**Comment by AgustinVallejo** [comment]
This is ready for review @Nancy-Salpepi

**Comment by AgustinVallejo** [comment]
Sorry, fixing and assigning back again for review @Nancy-Salpepi

**Comment by Nancy-Salpepi** [comment]
Now we are good 😊!

**Comment by pixelzoom** [comment]
Reopening.  I see that MySolarSystemModel `resetTimeEmitter` was added. It looks odd and unnecessary to me.  It's also not PhET-iO instrumented, and has other potential PhET-iO problems.
