### ISSUE TITLE
Bodies immediately collide in Slingshot 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#275]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/997, in the lab screen, the pink and yellow bodies immediately collide in the Slingshot orbital system. 

**Steps to reproduce**
1. On the Lab screen, select Slingshot in the combobox
2. Press Play

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/964ad1a6-c7f2-4a6a-9105-735919f40a5d

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.3/phet/my-solar-system_all_phet.html
Version: 1.3.0-dev.3 2023-10-26 20:05:04 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language: en-US
Window: 1273x728
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Reproduced in main.  This is definitely different behavior than [1.3.0-dev.1](https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.1/phet/my-solar-system_en_phet.html).

**Comment by pixelzoom** [comment]
Before changing the model to standard units for https://github.com/phetsims/my-solar-system/issues/252, `SLINGSHOT` was defined like this in LabModel.ts:

```ts
    this.orbitalSystemMap.set( OrbitalSystem.SLINGSHOT, [
      new BodyInfo( { isActive: true, mass: 200, position: new Vector2( 1, 0 ), velocity: new Vector2( 0, -1 ) } ),
      new BodyInfo( { isActive: true, mass: 10, position: new Vector2( 131, 55 ), velocity: new Vector2( -55, 115 ) } ),
      new BodyInfo( { isActive: true, mass: 0.000001, position: new Vector2( -6, -128 ), velocity: new Vector2( 83, 0 ) } )
    ] );
```

After changing model to standard units:

```ts
    this.orbitalSystemMap.set( OrbitalSystem.SLINGSHOT, [
      new BodyInfo( { isActive: true, mass: 200, position: new Vector2( 1.00, 0 ), velocity: new Vector2( 0, -0.2112 ) } ),
      new BodyInfo( { isActive: true, mass: 10, position: new Vector2( 1.31, 0.55 ), velocity: new Vector2( -11.6172, 24.2906 ) } ),
      new BodyInfo( { isActive: true, mass: 0.000001, position: new Vector2( -0.06, -1.28 ), velocity: new Vector2( 17.5315, 0 ) } )
    ] );
```

It looks like the position for the first body did not get converted. Making this change (not committed) seems to fix the problem:

```diff
-       new BodyInfo( { isActive: true, mass: 200, position: new Vector2( 1.00, 0 ), velocity: new Vector2( 0, -0.2112 ) } ),
+      new BodyInfo( { isActive: true, mass: 200, position: new Vector2( 0.01, 0 ), velocity: new Vector2( 0, -0.2112 ) } ),
```

@AgustinVallejo can you verify that this is a correct fix? If so, apply the fix and assign to @Nancy-Salpepi to verify in main.

**Comment by AgustinVallejo** [comment]
I seem to have missed that spot! Good catch, yes, please commit. Thanks

**Comment by pixelzoom** [comment]
OK, I'll apply the fix.

**Comment by pixelzoom** [comment]
Back to @Nancy-Salpepi to verify. Close if OK.  Thanks for your thoroughness.

**Comment by Nancy-Salpepi** [comment]
You're welcome 😊
Looks good in main.

**Comment by Nancy-Salpepi** [comment]
Actually, I'm going to reopen this. 
The bodies no longer collide, but each time I press the Reset All button and choose Slingshot, the path is slightly different. 
<img width="412" alt="Screenshot 2023-10-30 at 11 13 44 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/dac94d9b-4a33-4760-95aa-4e2775640d57">
<img width="412" alt="Screenshot 2023-10-30 at 11 14 58 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/f1b876a2-00c1-466e-9a48-8f2673c01795">

This isn't limited to Slingshot in main. I tested Double Slingshot as well, and the orbits are slightly different there too each time I press Reset All. In one scenario, two bodies collide.

**Comment by AgustinVallejo** [comment]
After initial investigations of this, I notice that pressing "Play -> Restart" multiple times, alll systems in MSS are going back to incorrect states. For example on the intro screen, see how the planet starts off-grid after like the tenth restart:
![image](https://github.com/phetsims/my-solar-system/assets/37052186/f3fb921f-cb00-4e04-a2f5-9aa82fbd0e30)

Will look into what part of the code could be causing this.

**Comment by AgustinVallejo** [comment]
@Nancy-Salpepi this should be ready to review, but please don't close just yet as this was very odd behavior and I'm discussing with @pixelzoom why it could've happened.

Pasting my slack messages here as well:
I solved it by adding bodyInfo.position.copy() in loadBodyInfo() . But it doesn't give me closure, since currently the mutation was happening as follows:

1. We define this.defaultBodyInfo in the options.
2. We pass each BodyInfo to Body() in their constructor
3. Body was using the initial value of positionPoperty as bodyInfo.position. However, adding copy() there didn't fix anything.
4. After the bodies are created we saveStartingBodyState(), in which the bodies pass their data, creating a NEW BodyInfo AND using copy() on position. All that goes to model.startingBodyInfo() . At this point I'd guess any reference to the defaultBodyInfo should have been lost.
5. In the loadBodyInfo()  those BodyInfos are set as each bodies initialValues. Here's where I added a copy()
6. And yet, even after ALL THAT, loadBodyInfo()  was directly changing this.defaultBodyInfo , and to me that doesn't make sense...

**Comment by pixelzoom** [comment]
In Slack#DM, @AgustinVallejo said:

> it seems this.defaultBodyInfo is being mutated but it shouldn't. I'm looking into it but wanted to let you know in case you have a clue where.
And I have a feeling that by making it a class and setting the Body's parameters with BodyInfo elements, they are being referenced by the body and changed when the body property changes. What's weird is that it apparently changes only in the first step of the model...

> I solved it by adding `bodyInfo.position.copy()` in `loadBodyInfo()`. But it doesn't give me closure, since currently the mutation was happening as follows:
1. We define `this.defaultBodyInfo` in the options.
2. We pass each BodyInfo to Body() in their constructor
3. Body was using the initial value of positionPoperty as `bodyInfo.position`. However, adding copy() there didn't fix anything.
4. After the bodies are created we `saveStartingBodyState()`, in which the bodies pass their data, creating a NEW BodyInfo AND using copy() on position. All that goes to `model.startingBodyInfo()`. At this point I'd guess any reference to the defaultBodyInfo should have been lost.
5. In the `loadBodyInfo()` those BodyInfos are set as each bodies initialValues. Here's where I added a copy()
6. And yet, even after ALL THAT, `loadBodyInfo()` was directly changing `this.defaultBodyInfo`, and to me that doesn't make sense...

**Comment by pixelzoom** [comment]
In NumericalEngine.ts, there are 4 Properties whose value may be mutated directly:

```ts
      else {
        // mutate Vector2 values!
        body.positionProperty.value.set( positions[ i ] );
        body.velocityProperty.value.set( velocities[ i ] );
        body.accelerationProperty.value.set( accelerations[ i ] );
        body.gravityForceProperty.value.set( gravityForces[ i ] );
      }
```

So we'll need to make a copy of the value for each of those Properties. I'll take a stab at doing this.

**Comment by pixelzoom** [comment]
> ... So we'll need to make a copy of the value for each of those Properties. I'll take a stab at doing this.

Actually we only need to make a copy of position and velocity, since they are the only ones that appear in BodyInfo.

**Comment by pixelzoom** [comment]
In the above commit, I added a copy of `copy` calls that seemed necessary, and added doc about why `copy` is needed. (This is an example of why mutating Property values is generally a bad practice, to be avoided.)

After all that, I'm still seeing a difference between 1.3.0-dev.1 and main.

**Comment by AgustinVallejo** [comment]
What difference do you see?

**Comment by pixelzoom** [comment]
@AgustinVallejo and I looked at this, and 1.3.0-dev.1 and main are not identical, but close enough. Definitely does the radical difference that @Nancy-Salpepi observed.

@Nancy-Salpepi could you please have look? Close if OK.

**Comment by Nancy-Salpepi** [comment]
Everything looks good on my end!
