### ISSUE TITLE
Revisit layout of "Return Bodies" button and "Some force vectors..." message

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#276]
The "Return Bodies" button appears at the top of the screen:

<img width="1006" alt="screenshot_2854" src="https://github.com/phetsims/my-solar-system/assets/3046552/5024bf3d-6bcc-4994-9a71-c70d15cd42dc">

The "Some force vectors are too small to display" message also appears at the top of the screen.  If you check the "Gravity Force" checkbox, it can cause the "Return Bodies" button to move:

<img width="1004" alt="screenshot_2855" src="https://github.com/phetsims/my-solar-system/assets/3046552/ac747f9c-8586-4f8c-92cd-ff77867764a9">

Rather than having UI components jumping around, I recommend putting the message under the button, in a VBox that does not move things around when its children are made visible/invisible.  This would result in the button and message having consistent/fixed location.

@arouinfar Does this sound like an OK change?

**Comment by arouinfar** [comment]
> @arouinfar Does this sound like an OK change?

Yes, sounds good to me. Thanks @pixelzoom.

**Comment by pixelzoom** [comment]
Upon futher consideration, and after experiementing with the alternatives, I'm going to leave this as is.   Doing what I suggested resulted in move overlap of the message with bodies and vectors, which is not desirable.  

So... closing as "won't fix".
