### ISSUE TITLE
Orbits can look choppy with Step Forward button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#277]
**Test device**
MacBook Air M1 chip

**Operating System**
14.0

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/997, some orbits aren't smooth when using the Step Forward button. 
This isn't seen with 1.3.0-dev.1.

**Steps to reproduce**
1. On the Lab Screen, select "Sun, Planet, Moon" or "Double Double"
2. Either press and hold or continuously press the Step Forward button

**Visuals**
<img width="509" alt="Screenshot 2023-10-27 at 2 21 50 PM" src="https://github.com/phetsims/my-solar-system/assets/87318828/dc8bfbee-f3d1-4a06-82da-ea29625a4cb6">

<img width="509" alt="Screenshot 2023-10-27 at 2 05 37 PM" src="https://github.com/phetsims/my-solar-system/assets/87318828/b9c3cb58-9573-4a8f-aa51-4b4ab06362ef">

**Comment by pixelzoom** [comment]
Likely related to https://github.com/phetsims/my-solar-system/issues/257.

**Comment by AgustinVallejo** [comment]
Above commit tackles this, can you review and close if ready @Nancy-Salpepi ? Thanks

**Comment by Nancy-Salpepi** [comment]
Orbits look smooth in main.
