### ISSUE TITLE
Dragging velocity vector with the keyboard is unconstrained.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#278]
For DraggableVelocityVectorNode, dragging with the mouse is constrained to the drag bounds, but dragging with the keyboard is not constrained. The KeyboardDragListener should be modified to constrain dragging like the DragListener does.

**Comment by pixelzoom** [comment]
BodyNode does not have this problem because it uses the same `mapPostion` value for both its DragListener and KeyboardDragListener. DraggableVelocityVectorNode provides `mapPostion` only for its  DragListener.  So I tried adding `mapPosition` to the KeyboardDragListener, see the patch below.   This did not work - it totally breaks keyboard dragging for DraggableVelocityVectorNode.  And I don't understand why it works for BodyNode, but not for DraggableVelocityVectorNode.  @AgustinVallejo any ideas?

```diff
Subject: [PATCH] use same order of args for DragListener and KeyboardDragListener, https://github.com/phetsims/my-solar-system/issues/278
---
Index: js/view/DraggableVelocityVectorNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/view/DraggableVelocityVectorNode.ts b/js/view/DraggableVelocityVectorNode.ts
--- a/js/view/DraggableVelocityVectorNode.ts	(revision 43cdf8d36477a09f07979ef02c6f711bc5c4dbc2)
+++ b/js/view/DraggableVelocityVectorNode.ts	(date 1698768083531)
@@ -146,10 +146,13 @@
       this.releaseClip.play();
     };
 
+    // Constrain dragging for DragListener and KeyboardDragListener.
+    const mapPosition = ( point: Vector2 ) => options.mapPosition( point, circleOuterRadius );
+
     const dragListener = new DragListener( {
       positionProperty: velocityCirclePositionProperty,
       transform: transformProperty,
-      mapPosition: point => options.mapPosition( point, circleOuterRadius ),
+      mapPosition: mapPosition,
       start: () => {
         keyboardDragListener.interrupt();
         start();
@@ -167,6 +170,7 @@
     const keyboardDragListener = new KeyboardDragListener( {
       positionProperty: velocityProperty,
       transform: transformProperty,
+      mapPosition: mapPosition,
       start: () => {
         dragListener.interrupt();
         start();
```

**Comment by pixelzoom** [comment]
I just noticed that DraggableVelocityVectorNode is using different `property` values for it DragListener vs KeyboardDragListener.  I'm guessing that is where the problem lies.

```ts
    const dragListener = new DragListener( {
      positionProperty: velocityCirclePositionProperty,
...
    const keyboardDragListener = new KeyboardDragListener( {
      positionProperty: velocityProperty,
```

**Comment by pixelzoom** [comment]
The KeyboardDragListener works if I make this change in DraggableVelocityVectorNode:

```diff
    const keyboardDragListener = new KeyboardDragListener( {
-      positionProperty: velocityProperty,
+      positionProperty: velocityCirclePositionProperty,
```

But the keyboard dragging moves too quickly. This seems to be the reason why we needed large `dragVelocity` and `shiftDragVelocity` values that we didn't understand.

**Comment by pixelzoom** [comment]
And there's another problem -- when starting a keyboard drag for the first time, the velocity vector jumps to the far right of the drag bounds.

**Comment by AgustinVallejo** [comment]
It now supports constraint and does not bug to one of the sides. However, I'm still seeing a misbehavior: When you move the body, then tab to the velocity, it initially begins to the last global position of the velocity tip. Looking into it but the logic around `velocityCirclePositionProperty` doesn't fully convince me, we should look into it.

**Comment by AgustinVallejo** [comment]
This is now fixed. Closing.

**Comment by AgustinVallejo** [comment]
> It now supports constraint and does not bug to one of the sides. However, I'm still seeing a misbehavior: When you move the body, then tab to the velocity, it initially begins to the last global position of the velocity tip. Looking into it but the logic around `velocityCirclePositionProperty` doesn't fully convince me, we should look into it.

The fix to this issue commited in https://github.com/phetsims/solar-system-common/commit/9f6721e4da22db4a41c3e8194b83902313591031 caused other troubles in https://github.com/phetsims/my-solar-system/issues/274. So I rolled back that change.

Basically, that positionProperty link was being triggered when the system was re-centered, and apparently this link was interfering before the system's velocity could also be corrected.

I think there might be a better way to fix this, because currently, when you use the keyboard to move the body around, the velocity arrow appears to behave properly, but when it's moved with the keyboardDragListener, it tries to go back to it's previous position.

**Comment by AgustinVallejo** [comment]
@pixelzoom and I implemented a workaround for this using a guard flag. We never totally understood the problem but this seemed to resolve it, so we are moving on.
