### ISSUE TITLE
Clean up `stepOnce` method for model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#279]
@AgustinVallejo suggested a good refactor, that goes something like this:

1. Move the code in SolarSystemCommonModel `stepOnce` to MySolarSystemModel `stepOnce`
2. Make SolarSystemCommonModel `stepOnce ` abstract
3. Implement KeplersLawModel `stepOnce ` that is more appropriate for that sim

This would also have the advantage of being able to navigate to the approprite `engine.run` method, instead of ending up at the abstract declaration in Engine.ts.

@AgustinVallejo will have a look at this.

**Comment by pixelzoom** [comment]
Why did we say `run` for this issue?  I don't see any `run` method in SolarSystemCommonModel.  Did we mean `stepOnce`?

**Comment by AgustinVallejo** [comment]
Yes, I think we refer to the `step `method in the model which calls the `run `method in the engine. All that logic could benefit from a light refactoring.

**Comment by pixelzoom** [comment]
@AgustinVallejo did a nice job of addressing the 3 points in  https://github.com/phetsims/my-solar-system/issues/279#issue-1969179818.  And we cleaned up MySolarSystemModel `stepOnce` over in https://github.com/phetsims/my-solar-system/issues/257.  The code is now much clearer and maintainable.  So this is ready to close.
