### ISSUE TITLE
Publish My Solar System 1.3 with PhET-iO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#282]
This issue is for tracking completion of major milestones and progress during QA.  For a similar example, see https://github.com/phetsims/acid-base-solutions/issues/192.

**Comment by pixelzoom** [comment]
On 11/13/2023, we completed PhET-iO instrumentation, and started Studio tree review in #295.

**Comment by pixelzoom** [comment]
On 11/29/2023, we had completed PhET-iO instrumentation, addressed all issues, and were ready to start QA dev testing. @AgustinVallejo will create the dev-test issue in the QA repo.

**Comment by pixelzoom** [comment]
Dev test 1.3.0-7 https://github.com/phetsims/qa/issues/1008 started on 12/1/23 and completed on 12/7/23.

**Comment by pixelzoom** [comment]
On 12/11/23, 1.3.0-rc.1 was published for a full RC test:

* https://github.com/phetsims/qa/issues/1015

**Comment by zepumph** [comment]
I published MSS 1.3.0-rc.2 this morning for https://github.com/phetsims/qa/issues/1017. From talking with QA and @AgustinVallejo this morning, it didn't make sense to use it for the MSS RC process at all, so it is just for confirming the MR changes.

**Comment by zepumph** [comment]
All maintenance patches have been applied to the 1.3 branch. rc.2 doesn't encapsulate every change, but all changes have been tested, and you are unblocked from my side for publication of MSS. Thanks for your patience, I know that took a while.

**Comment by AgustinVallejo** [comment]
For the record, I tried deploying rc.3 but due to some unpushed changes the build failed. The current RC spot checking https://github.com/phetsims/qa/issues/1029 is being done on rc.4

**Comment by AgustinVallejo** [comment]
On 01/17/2024, 1.3.0-rc.5 was published for an RC spot checking:
- https://github.com/phetsims/qa/issues/1030

RC spot check completed 01/18/2024.

**Comment by AgustinVallejo** [comment]
On 01/18/2024 1.3.0 version was deployed to the website! Thanks to everyone involved. Closing this issue as completed
