### ISSUE TITLE
Make OrbitalSystem a rich enumeration.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#283]
Turning OrbitalSystem into a rich enumeration would clean things up a bit. 

* Add `public bodyInfo: BodyInfo[]` to OrbitalSystem. (It must be writeable for `PHET_IO_ORBITAL_SYSTEM_1` et. al.)
* Remove `orbitalSystemMap` from LabModel. 

@AgustinVallejo will handle this one.

**Comment by pixelzoom** [comment]
@AgustinVallejo sorry, but this got tangled up with removing duplication in https://github.com/phetsims/my-solar-system/issues/233.  So I went ahead and did it.   Please review, close if OK.

**Comment by AgustinVallejo** [comment]
Looks like a really good change, thanks. Closing
