### ISSUE TITLE
The clock readout flickers

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#286]
When the clock starts ticking, some numbers change the positioning of the string, such as 11.11

![image](https://github.com/phetsims/my-solar-system/assets/37052186/2d90aec5-ee50-492d-a3e5-6ac2896ec0d4)

Will take a look

**Comment by pixelzoom** [comment]
If you mean that the decimal point moves around... I think it's fine.  The only way to really solve that problem would be to use a monospaced font, which I doubt that we'd want to do.

**Comment by AgustinVallejo** [comment]
Gotcha, closing then.
