### ISSUE TITLE
Full Simulation Review

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#29]
Opening this issue for the complete sim design review (Intro and Lab screens, Kepler is still on the works). I suggest running the sim with phetmarks as to have all the latest updates. 

Things that are still to be polished:
- The sliders sounds.
- The length of the path.
- Explosion logic.

**Comment by ariel-phet** [comment]
@AgustinVallejo @kathy-phet @DianaTavares I have finished my review. Overall things are looking pretty good. I think the highest priorities in my mind are

Must fix:
#35, #36

Would be nice to fix:
#38, #32, #33

**Comment by DianaTavares** [comment]
And i think that the issue related with the trace also need to be fixed #21.

**Comment by DianaTavares** [comment]
We can close this issue now that the sim is in QA!
