### ISSUE TITLE
Test in the Standard wrapper

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#293]
This is another aspect of PhET-iO that has not received enough attention. The general idea is:

1. Run the sim in Studio
2. Configure the sim by using it.
3. Press the "Test" button to launch the Standard wrapper.
4. Verify that the Standard wrapper looks the same as the sim does in Studio.
5. Repeat steps 2-4 for many configurations.

Assigning to @AgustinVallejo and myself to do this independently. This should be completed before sending this to @arouinfar for review, and definitely before sending to QA.

**Comment by AgustinVallejo** [comment]
Tested for about an hour and didn't find anything. Unassigning myself :)

**Comment by pixelzoom** [comment]
As with the State wrapper,  the initial state of KeypadDialog is incorrect in the Standard wrapper. See screenshot below, where the range and value are both missing.  But that is to be expected, since we punted on instrumenting KeypadDialog and Keypad (see #234).   And in practice there is no reason to be creating a wrapper where the initial state has the KeypadDialog open.

<img width="1152" alt="screenshot_2894" src="https://github.com/phetsims/my-solar-system/assets/3046552/09aaa464-8bb1-41fe-8d1d-760189922394">

**Comment by pixelzoom** [comment]
I discovered and fixed one serious problem, see https://github.com/phetsims/my-solar-system/issues/294.

Otherwise things look OK, and this issue can be closed.
