### ISSUE TITLE
Studio tree review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#295]
@arouinfar The Studio tree is ready for review.  Let us know what you'd like to change. You can make change requests here (as checklist items please) or create new GitHub issues -- your choice.

I'll also leave it up to you as to whether to create a separate GitHub issue for "phetioFeatured", or address that here.

@AgustinVallejo FYI.

**Comment by pixelzoom** [comment]
Prior to making any change requests related to this issue, I deployed this dev version:

* https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.5/phet/my-solar-system_all_phet.html
* https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.5/phet-io/

**Comment by arouinfar** [comment]
The tree review is complete and all remaining work is tracked in the issues referenced above.

Really excellent work @AgustinVallejo @pixelzoom!
