### ISSUE TITLE
Missing dependencies for DerivedProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#296]
Related to https://github.com/phetsims/axon/issues/441....

In https://github.com/phetsims/solar-system-common/commit/2e845a9aaed506ce21a9ad9d02c87d2397293079, @samreid added `accessNonDependencies: true` to temporarily silence missing dependencies for a DerivedProperties. 

@AgustinVallejo we should investigate for 1.3 release.

**Comment by pixelzoom** [comment]
@AgustinVallejo and I discussed. He'll add `...this.bodies.map( body => body.isActiveProperty )` to the dependencies.

**Comment by AgustinVallejo** [comment]
Added missing dependencies, closing.
