### ISSUE TITLE
Return Bodies button should appear when objects collide

### ISSUE THREAD

**Issue by arouinfar** [phetsims/my-solar-system#297]
In main, destroying a body through collision does not trigger the Return Bodies button to appear. The button correctly appears in the published version, so the bug was introduced sometime after.

In #147 we defined the behavior for the Return Bodies button:

> 1. 'Return bodies' appears either when there's a collision or a body escapes the screen.
> 2. On Intro screen, if a body is destroyed or escapes, we will no longer save body states upon interaction. This is because you would be rewinding to a sim with just one body, which doesn't do much.
> 3. When pressed, 'Return bodies' behaves as a rewind.

**Comment by arouinfar** [comment]
I'd also like to note that the `isAnyBodyCollidedProperty` remains false after collision which seems incorrect to me.

**Comment by pixelzoom** [comment]
Line 177 of SolarSystemCommonModel looks like the cause of this problem:

```ts
    Multilink.multilinkAny( this.bodies.map( body => body.isActiveProperty ), () => {
...
177   this.isAnyBodyCollidedProperty.reset();
    } );
```

When a body collides, its `isActiveProperty` becomes false.  And the code above then resets `isAnyBodyCollidedProperty`.

Git history indicates that @AgustinVallejo added line 177 on 10/23/23 in https://github.com/phetsims/solar-system-common/commit/b338a3088492e0ca2d1199f22921b38e86394bb8 for https://github.com/phetsims/my-solar-system/issues/256.

**Comment by AgustinVallejo** [comment]
Fixed above, assigning back to @arouinfar for review

**Comment by arouinfar** [comment]
Looks good in main, thanks @pixelzoom @AgustinVallejo! Closing.
