### ISSUE TITLE
Velocity vectors snap to zero too easily

### ISSUE THREAD

**Issue by arouinfar** [phetsims/my-solar-system#298]
When adjusting the velocity vector with mouse/touch, there is a threshold at which the vector will snap to zero. This is generally a helpful feature and behaves well in the published version of the sim. However, the snapping behavior is overly sensitive in main.

Steps to reproduce in main:
1. Start sim, select either screen.
2. Click on Body 1's velocity vector. It will snap to zero. This is a bit jarring and a divergence from published.
3. Drag the velocity vector to make it larger. Your cursor will need to move significantly before achieving a non-zero velocity, which happens around here:
![image](https://github.com/phetsims/my-solar-system/assets/8419308/b13eac01-e2dd-4902-bae4-f809c25ba0ae)

This is significantly larger than the minimum possible size in the published version, which roughly about this size:
![image](https://github.com/phetsims/my-solar-system/assets/8419308/2c719cc7-1094-4af1-a9d3-c6d89e43019e)

**Comment by AgustinVallejo** [comment]
This was due to not changing the minimum velocity after modifying the units of the sim in https://github.com/phetsims/my-solar-system/issues/252. The above commit fixes that!

**Comment by pixelzoom** [comment]
Reopening. @arouinfar should be the one to verify and close.

**Comment by arouinfar** [comment]
Thanks @AgustinVallejo! The behavior in main now matches published, closing.
