### ISSUE TITLE
Revisit instrumentation of `valuesPanel.keypadDialog`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#299]
@arouinfar reported that `valuesPanel.keypadDialog` is over-instrumented. See the Studio tree below. There's no reason to instrument any of the buttons.

Also noting that the current level of instrumentation is the result of (1) using the required instrumentation that was identified by Studio via `&phetioPrintMissingTandems`, and (2) the fact that we punted on a designed instrumentation of Keypad/KeypadDialog in #234.

<img width="244" alt="screenshot_2898" src="https://github.com/phetsims/my-solar-system/assets/3046552/12dd4a97-ebae-4ab3-a818-21f236935a12">

**Comment by pixelzoom** [comment]
In the above commit, I opted out of instrumenting `keypadDialog.keypad` and `keypadDialog.enterButton`.  The Studio tree is now minimal (see below) and contains only the elements that come with sun.Dialog.

@arouinfar ready for review, close if OK.

<img width="228" alt="screenshot_2900" src="https://github.com/phetsims/my-solar-system/assets/3046552/8c866442-fc6a-421a-bc39-00240dc76ccb">

**Comment by arouinfar** [comment]
Looks good in main, thanks @pixelzoom!

**Comment by arouinfar** [comment]
Related to #295
