### ISSUE TITLE
Visualizations/better support for Kepler's Laws (legacy)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/my-solar-system#3]
From unfuddle #2248

> I have a suggestion on the “my solar system” simulation. I wonder if you can add a line that goes from the center of mass to the planet in the two objects mode. This line is drawn every second or two seconds and left on screen so that Kepler’s 2nd law about the area swept can be shown with the lines drawn at equal time intervals. I’ve attached a picture to show what I meant. An option may be provided to turn the lines on and off. Thanks for your time. 

![solar_system](https://user-images.githubusercontent.com/4051174/94091487-92254980-fdd5-11ea-82f6-b96e022bd220.GIF)

**Comment by ariel-phet** [comment]
This sort of feature seems worth exploring, perhaps on an "intro" screen

**Comment by DianaTavares** [comment]
This has already been included in the new design of the simulation: 
![image](https://user-images.githubusercontent.com/26031501/111367634-8b77e080-865a-11eb-9e10-1e96b91dc5a6.png)
