### ISSUE TITLE
Hiding `timeControlNode.speedRadioButtonGroup` leaves a blank space in the panel.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#300]
When `timeControlNode.speedRadioButtonGroup.visibleProperty` is set to false, it leaves a blank space in the panel, see screenshot below.  The layout should dynamically update, and close the space.

<img width="115" alt="screenshot_2903" src="https://github.com/phetsims/my-solar-system/assets/3046552/9ce4df3e-b96a-470b-b63b-b462fe2476ce">

**Comment by pixelzoom** [comment]
This bit of code below in SolarSystemCommonTimeControlNode is really awful.  It's reaching into TimeControlNode and changing its layout, which TimeControlNode assumes that it has fully responsibility for.   A better approach would be to replace `TimeControlNodeOptions.speedRadioButtonGroupOnLeft`  with something like `TimeControlNodeOptions.speedRadioButtonGroupPosition: 'left' | 'right' | 'top' | 'bottom'`.

```ts
    // speedRadioButtonGroup is positioned differently on KeplersLaws and MySolarSystem.
    // Here, the position when it's under the play pause step buttons is set as follows:
    // X: Aligned with the play pause step buttons
    // Y: Below the play pause step buttons
    if ( !options.speedRadioButtonGroupOnRight ) {
      this.speedRadioButtonGroupParent!.center = this.getPlayPauseButtonCenter().plusXY(
        -0.9 * ( PLAY_PAUSE_BUTTON_RADIUS + STEP_BUTTON_RADIUS ),
        PLAY_PAUSE_BUTTON_RADIUS + STEP_BUTTON_RADIUS + 3 * PUSH_BUTTON_SPACING
      );
    }
```

**Comment by pixelzoom** [comment]
I created https://github.com/phetsims/scenery-phet/issues/826 to track this as a general problem with TimeControlNode. It's a nontrivial amount of work, and should be scheduled for an iteration.

**Comment by arouinfar** [comment]
Tagging #295

**Comment by pixelzoom** [comment]
@arouinfar and I discussed how to proceed with this, so that it does not block the 1.3 release. We will not wait for https://github.com/phetsims/scenery-phet/issues/826 to be addressed, since that would push us out an iteration or more.   I'm going to take another look at TimeControlNode to see if there's (yet another) simple workaround that can be added to address this.  If not, then we will live with the empty space for the 1.3 release.

**Comment by pixelzoom** [comment]
In the above commit, I identified options that had been previously added to TimeControlNode to work around this problem, and I used them in this sim.   Gory details in https://github.com/phetsims/scenery-phet/issues/826#issuecomment-1832759228.

I also added TODO items in the code, so that this will get cleaned up when https://github.com/phetsims/scenery-phet/issues/826 is eventually addressed.

@arouinfar please review, close if OK.  Toggle `timePanel.timeControlNode.speedRadioButtonGroup.visibleProperty` and verify that the `timePanel` resized as expected, with no "holes" in the layout.

**Comment by arouinfar** [comment]
Looks good in main, thanks @pixelzoom. Closing.
