### ISSUE TITLE
Uninstrument `position*MappedProperty`

### ISSUE THREAD

**Issue by arouinfar** [phetsims/my-solar-system#302]
For #295 

The `valuesPanel.positionSection` contains several MappedProperties that correspond to the x- or y-coordinate of the position.

![image](https://github.com/phetsims/my-solar-system/assets/8419308/d799176c-bc1d-47ab-8ae3-e85ad0d8d1ad)

These properties are unnecessary. Clients can directly edit the body's `positionProperty` which we conveniently link to in each Display.

It seems like these MappedProperties are vestiges of old model in non-standard units. In https://github.com/phetsims/my-solar-system/issues/252 @pixelzoom wrote:
> We would no longer need the`MappedProperty` instances under `valuesPanel`.

I recommend we uninstrument `position*MappedProperty`.

**Comment by pixelzoom** [comment]
The MappedProperties are still necessary - they map between vectors and individual x,y components.  But it's probably not necessary for them to be stateful.  I'll investigate.

**Comment by arouinfar** [comment]
@pixelzoom if they're not going to be stateful, we should add `phetioDocumentation` that indicates they are for internal use only.

**Comment by pixelzoom** [comment]
These MappedProperty elements did not need to be stateful, so I instrumented them, and added a comment referencing this issue in the code.  The Studio tree for `valuesPanel.positionSection` is shown below. Back to @arouinfar for review, close if OK.

<img width="231" alt="screenshot_2910" src="https://github.com/phetsims/my-solar-system/assets/3046552/5db84e4d-c927-415d-8303-4942f8144bd8">

**Comment by arouinfar** [comment]
Thanks @pixelzoom! Looks good in main, closing.
