### ISSUE TITLE
Specify `phetioFeatured` behavior

### ISSUE THREAD

**Issue by arouinfar** [phetsims/my-solar-system#304]
Related to #295.

Self-assigning to review the `phetioFeatured` behavior in Studio and recommend changes.

**Comment by arouinfar** [comment]
@pixelzoom @AgustinVallejo did an excellent job of anticipating which elements should be `phetioFeatured: true` and it really simplified the tree review. 

I identified a few additional elements to feature. Please feature these properties on all applicable screens @AgustinVallejo @pixelzoom.

```ts
/* eslint-disable */
window.phet.preloads.phetio.phetioElementsOverrides =
  {
    "mySolarSystem.introScreen.model.time.isPlayingProperty": {
      "phetioFeatured": true
    },
    "mySolarSystem.introScreen.model.time.timeProperty": {
      "phetioFeatured": true
    },
    "mySolarSystem.introScreen.model.time.timeSpeedProperty": {
      "phetioFeatured": true
    },
    "mySolarSystem.introScreen.model.zoomLevelProperty": {
      "phetioFeatured": true
    },
    "mySolarSystem.labScreen.model.orbitalSystemProperty": {
      "phetioFeatured": true
    },
    "mySolarSystem.labScreen.model.phetioOrbitalSystems.orbitalSystem1Property": {
      "phetioFeatured": true
    },
    "mySolarSystem.labScreen.model.phetioOrbitalSystems.orbitalSystem2Property": {
      "phetioFeatured": true
    },
    "mySolarSystem.labScreen.model.phetioOrbitalSystems.orbitalSystem3Property": {
      "phetioFeatured": true
    },
    "mySolarSystem.labScreen.model.phetioOrbitalSystems.orbitalSystem4Property": {
      "phetioFeatured": true
    }
  };
  ```

**Comment by pixelzoom** [comment]
@AgustinVallejo will handle this one. Please assign to me for code review.

**Comment by AgustinVallejo** [comment]
Assigning back to @pixelzoom for review

**Comment by arouinfar** [comment]
Thanks @pixelzoom @AgustinVallejo. The requests in https://github.com/phetsims/my-solar-system/issues/304#issuecomment-1828722791 all look good in main.

However, some of the linked elements added in #303 aren't showing up in the featured tree because I forgot to ask for the parent to also be featured. Let's additionally feature:
- [ ] `view.panels.timePanel.clockNode` (both screens)
- [ ]  `labScreen.view.numberOfBodiesControl`

**Comment by arouinfar** [comment]
Looks good in main, thanks @pixelzoom
