### ISSUE TITLE
Center of Mass 'X' doesn't move when zooming in/out

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#305]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.1

**Browser**
Safari 17.1

**Problem description**
For https://github.com/phetsims/qa/issues/1008, on both screens the Center of Mass marker doesn't shift when zooming in/out. 
This is different than what occurs in published. 

**Steps to reproduce**
1. On either screen, make the mass of both bodies 100 (easier to see what happens)
2. Check Grid
3. Check Center of Mass
4. Use the Zoom in and out buttons

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/1ae51c9b-9a52-4e31-88b6-ff834657f582

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.3.0-dev.7 2023-12-01 16:11:20 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
Language: en-US
Window: 1359x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Reproduced in master.

Looking at CenterOfMassNode.ts, I see:

```ts
    centerOfMass.positionProperty.link( position => {
      this.translation = modelViewTransformProperty.value.modelToViewPosition( position );
    } );
```

So there's currently nothing that updates the position when the zoom changes.

**Comment by Nancy-Salpepi** [comment]
Looks good to me!
