### ISSUE TITLE
Can't select/unselect "Custom" option with keyboard navigation

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#306]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.1

**Browser**
Safari 17.1

**Problem description**
For https://github.com/phetsims/qa/issues/1008, it isn't possible to select or deselect the Custom option on the Lab screen using the arrow keys. If I select the Custom option with the mouse, I can unselect it by pressing shift + tab. Weird!

**Steps to reproduce**
1. On the Lab Screen, tab to the Orbital System Combobox
2. Use the down arrow to try to select the Custom Option. 

OR
1. Change the mass or move a body
2. Tab to the Orbital System Combobox and try to move up in the combobox. 

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.3.0-dev.7 2023-12-01 16:11:20 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
Language: en-US
Window: 1359x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Hypothesis verified.

If I run the sim in Studio and make the invisible items visible (`orbitalSystem1Item`, `orbitalSystem2Item`, `orbitalSystem3Item`, `orbitalSystem4Item`), then I can use the keyboard to traverse to "Custom".

I can also cause this problem to occur in Density:

1. Run Density in Studio. Note that the Intro screen has the comboBox shown in the screenshot below.
2. Set `density.introScreen.view.blockAControlPanel.comboBox.listBox.aluminumItem.visibleProperty` to false.
3. Go to the Intro screen
4. Traverse to the comboBox, and note that you cannot get to "Custom" with the keyboard.

<img width="142" alt="screenshot_2918" src="https://github.com/phetsims/my-solar-system/assets/3046552/a66fa54d-62ca-4061-99ff-a495f5cb5f2e">

Git history suggested that @jessegreenberg added alt input to ComboBoxListBox, so I'll start by assigning to him. This is high priority -- we are in a dev test, and need to create the release branch as soon as possible after the dev test is completed.

**Comment by Nancy-Salpepi** [comment]
This is fixed in main.
Closing.
