### ISSUE TITLE
Decreasing Number of Bodies sound heard on Reset All 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#307]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.1

**Browser**
Safari 17.1

**Problem description**
For https://github.com/phetsims/qa/issues/1008, on the Lab Screen, pressing Reset All with more than 2 bodies present will trigger the 'Decreasing Number of Bodies' sound. 

**Steps to reproduce**
1. On the Lab Screen, use the increment button to change the number of bodies OR change the orbital system in the combobox
2. Press Reset All

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/b196af90-c027-4bff-9160-551adffdb646

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.3.0-dev.7 2023-12-01 16:11:20 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15
Language: en-US
Window: 1359x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
@Nancy-Salpepi can you review this and close when ready? Thanks!

**Comment by Nancy-Salpepi** [comment]
Sounds good to me now--I don't hear it on Reset All or when changing the orbital system. 
Closing.

**Comment by AgustinVallejo** [comment]
But that's not it. The ComboBox has three sounds: `openedSoundPlayer`, `closedNoChangeSoundPlayer `and the selection sound is defined by `soundPlayer`, all of them found in `ComboBox.ts`. If you compare the selection sounds in [MSS-published](https://phet.colorado.edu/sims/html/my-solar-system/latest/my-solar-system_all.html ) with the baseline or with main, they are different. But I suspect this change might have come from common code.

Again, Balancing-Chemical-Equations still has a selection sound, but other sims do not.

Should we do anything about this or leave it be?

**Comment by pixelzoom** [comment]
Oh, I see.  Published version 1.2.3 (and baseline) are using a custom sound for the `orbitalSystemComboBox`.  That was probably lost when we factored out OrbitalSystemComboBox -- I don't see it setting any custom sounds.

**Comment by pixelzoom** [comment]
OrbitalSystemComboBox was formerly named LabModeComboBox.

**Comment by pixelzoom** [comment]
Promoted to https://github.com/phetsims/sun/issues/861, @jbphet volunteered to investigate.  I'll put this issue on hold until that issue is resolved.

**Comment by pixelzoom** [comment]
Assigning to me and @AgustinVallejo to keep an eye on https://github.com/phetsims/sun/issues/861.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/sun/issues/861 has been addressed (thanks @jbphet!) and is behaving nicely in this sim.  So this issue can be closed.
