### ISSUE TITLE
Traversal order doesn't change when Systems are reordered

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#308]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.1

**Browser**
Safari 17.1

**Problem description**
For https://github.com/phetsims/qa/issues/1008 and seen in Main:
In studio, after the order of orbital systems is the listbox is changed, navigating down the list with the keyboard still highlights each item in the original order.

**Steps to reproduce**
Here is an example:
1. In studio, on the Lab Screen go to mySolarSystem.labScreen.view.panels.orbitalSystemPanel.orbitalSystemComboBox.listBox.hyperbolicItem and move "hyperbolic" from index = 5 to index = 0.
2. Go to mySolarSystem.labScreen.view.panels.orbitalSystemPanel.orbitalSystemComboBox.listBox.slingshotItem and move "slingshot" from index = 6 to index = 9.
3. Press Test
4. In the Standard PhET-iO wrapper, tab to and open the combobox.
5. Continuously press the down arrow key until you have move through all of the items. 

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/5f4bf26a-9578-41a4-b4cb-19d6128df2fc

**Comment by pixelzoom** [comment]
Good catch @Nancy-Salpepi.  This is another general problem in common code.  I've added it to https://github.com/phetsims/sun/issues/859#issuecomment-1839389457, and this issue is on-hold (and blocked) until that is resolved.

**Comment by pixelzoom** [comment]
This has been addressed in https://github.com/phetsims/sun/issues/859.  @Nancy-Salpepi please verify in this sim, close if OK.

**Comment by Nancy-Salpepi** [comment]
Working well on main!
