### ISSUE TITLE
Add metronome sounds for period division on Kepler's Laws 

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/my-solar-system#31]
[Here is a mockup video of how the sounds should be implemented. ](https://drive.google.com/file/d/104LiBVygN0cAI0sLQEEFSWyHHSuBegiU/view?usp=share_link)

**[Here is a link to the folder with the below sounds.](https://drive.google.com/drive/folders/1BmznPlm-X_woQsLtSXoeVqU9YZo_b_z1?usp=share_link)**

- Metronome_Sound_2.mp3
- Metronome_Sound_2.wav
- Metronome_Sound_1.mp3
- Metronome_Sound_1.wav

**Comment by Ashton-Morris** [comment]
I have added these sounds to the same folder above. These are for @AgustinVallejo to experiment with when adjusting the size of the orbit with the metronome sounds.

- Metronome_Sound_Reverb_2.mp3
- Metronome_Sound_Reverb_2.wav
- Metronome_Sound_Reverb_1.mp3
- Metronome_Sound_Reverb_1.wav

**Comment by AgustinVallejo** [comment]
Reopening to include the reverb, just saw that comment...

**Comment by AgustinVallejo** [comment]
Reverb was added!
