### ISSUE TITLE
hiding the massSection on the lab screen can look odd 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#311]
**Test device**
Dell

**Operating System**
Win10

**Browser**
chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1008, one of the examples is to hide the mass section by setting `mySolarSystem.labScreen.view.panels.valuesPanel.massSection.visibleProperty` to false. If 'More Data' isn't checked, the result is this:
<img width="774" alt="Screenshot 2023-12-05 at 4 28 42 PM" src="https://github.com/phetsims/my-solar-system/assets/87318828/3b99308a-9456-4cbe-be5d-61d7cceb3abe">

**Comment by Nancy-Salpepi** [comment]
Also in that section of the examples, you mention setting `mySolarSystem.labScreen.view.panels.valuesPanel.positionSection.visibleProperty` to false to hide the property values. 

If the "More Data" checkbox isn't checked, that value is already `false`. Setting it to `true` causes the the property values to appear. I'm not sure if that should be mentioned somewhere. 
<img width="774" alt="Screenshot 2023-12-05 at 4 40 37 PM" src="https://github.com/phetsims/my-solar-system/assets/87318828/6fe41dda-9313-47c1-8dfc-ae1def5a3db9">

**Comment by pixelzoom** [comment]
I'll take this one.

**Comment by pixelzoom** [comment]
@arouinfar and I discussed.  There's nothing we can do to prevent this configuration, it's a possible intermediate state in configuring `valuesPanel`, and it will hopefully be obvious to the instructional design that this should not be the final state. We will make no code/instrumentation changes.  @arouinfar will elaborate on this and #312 in examples.md, then pass back to @Nancy-Salpepi to review.

**Comment by arouinfar** [comment]
I added this snippet to the section related to setting `massSection.visibleProperty` to `false`.
https://github.com/phetsims/phet-io-sim-specific/blob/main/repos/my-solar-system/examples.md#limit-which-data-is-accessible-to-students

> When hiding the `massSection` we recommend setting `moreDataVisibleProperty` to `true` and hiding the "More Data" checkbox, using the `phetioIDs` provided at the beginning of this section.

@Nancy-Salpepi please review and close if it looks OK.

**Comment by Nancy-Salpepi** [comment]
Perfect addition!
 Closing.

**Comment by Nancy-Salpepi** [comment]
Reopening for https://github.com/phetsims/qa/issues/1015 because the change I see in the link in https://github.com/phetsims/my-solar-system/issues/311#issuecomment-1846512521 is not present in the examples.md in https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.1/phet-io

**Comment by AgustinVallejo** [comment]
The spot check here is to make sure this change is in examples.md

**Comment by Nancy-Salpepi** [comment]
The change is in examples.md. in rc.4

Closing!
