### ISSUE TITLE
Changing velocitySection and positionSection visibleProperty is buggy

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#312]
**Test device**
Dell

**Operating System**
Win10

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1008, in studio on the Lab screen if "more data" isn't checked I can set `mySolarSystem.labScreen.view.panels.valuesPanel.positionSection.visibleProperty` and `mySolarSystem.labScreen.view.panels.valuesPanel.velocitySection.visibleProperty` to `true` causing the panel to look like this:

<img width="629" alt="Screenshot 2023-12-05 at 4 58 35 PM" src="https://github.com/phetsims/my-solar-system/assets/87318828/9d6dc727-261a-465c-bf5f-94aff9238944">

***
If I then check "more data" and then uncheck "more data" that information will disappear. 
Not sure what the intended behavior was supposed to be here. 

**Steps to reproduce**
1. In studio set `mySolarSystem.labScreen.view.panels.valuesPanel.positionSection.visibleProperty` and `mySolarSystem.labScreen.view.panels.valuesPanel.velocitySection.visibleProperty` to `true`
2. Check 'More Data'
3. Uncheck 'More Data'

**Comment by Nancy-Salpepi** [comment]
This is probably also related to https://github.com/phetsims/my-solar-system/issues/311

**Comment by pixelzoom** [comment]
I'll take this one.

**Comment by pixelzoom** [comment]
In the above commit, I wrapped `velocitySection` and `positionSection` in a parent Node that is visible only when `moreDataVisibleProperty` is true.   It's still possible to create a messed-up UI by setting `moreDataVisibleProperty` to true, then setting both `velocitySection.visibleProperty` and `positionSection.visibleProperty` to false.  But that's not something we can prevent, and this is another "don't do that" case.

Along with #311, @arouinfar will update examples.md.  Then assign to @Nancy-Salpepi to verify and close if OK.

**Comment by arouinfar** [comment]
I added this snippet to the section related to setting `massSection.visibleProperty` to `false`.
https://github.com/phetsims/phet-io-sim-specific/blob/main/repos/my-solar-system/examples.md#limit-which-data-is-accessible-to-students

> When hiding the `massSection` we recommend setting `moreDataVisibleProperty` to `true` and hiding the "More Data" checkbox, using the `phetioIDs` provided at the beginning of this section.

@Nancy-Salpepi please review and close if it looks OK.

**Comment by arouinfar** [comment]
Thanks @pixelzoom the behavior looks good on main, but I don't think we need to make changes to examples.md for this issue. We already instruct clients to turn off "More Data" and hide the checkbox if they are only focusing on Mass data.

> The Lab Screen includes position and velocity data when “More Data” is checked. If you want students to focus only on mass data, turn off the “More Data” checkbox and hide it.
> * `mySolarSystem.labScreen.view.visibleProperties.moreDataVisibleProperty`
> * `mySolarSystem.labScreen.view.panels.valuesPanel.moreDataCheckbox.visibleProperty`

Over to @Nancy-Salpepi to verify and close if OK.

**Comment by Nancy-Salpepi** [comment]
This is working nicely on main. Closing!
