### ISSUE TITLE
Possible to have body out of position without orbital system changing to "custom"

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#313]
**Test device**
iPad 9th generation

**Operating System**
17.0.2

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1008, on the iPad if I hold down a body with one finger and change the orbital system with another, the drag listener isn't interrupted. This can lead to a body being out of position without the orbital system changing to custom. 

**Steps to reproduce**
1. Using a multitouch device, on the lab screen, drag Body 1 elsewhere and hold it there
2. With a second finger change the Orbital System to Ellipses
3. Lift your finger off the body

**Visuals**
<img width="544" alt="Screenshot 2023-12-07 at 8 09 01 AM" src="https://github.com/phetsims/my-solar-system/assets/87318828/b6bd7bae-a40f-4ffd-9e56-c851577d9da2">

**Comment by AgustinVallejo** [comment]
This is ready to review, assigning back to @Nancy-Salpepi. Please close if done!

**Comment by Nancy-Salpepi** [comment]
One more I didn't mention the first time around....pressing the Follow Center of Mass button.

**Comment by AgustinVallejo** [comment]
Last one done!

**Comment by Nancy-Salpepi** [comment]
I really blew it on this issue! 
-decrease/increase number of bodies
-zoom buttons
Can you think of others or have we exhausted all options now?
Please forgive me!

**Comment by AgustinVallejo** [comment]
Should zoom buttons interrupt input? I feel like it's okay if they zoom out with the planet on their hand.

The other one I'm working on

**Comment by AgustinVallejo** [comment]
Number of bodies spinner done. I was thinking the slider also doesn't interrupt input but it's probably okay.

**Comment by Nancy-Salpepi** [comment]
I thought the slider was OK too because it doesn't have to do with changing the location.
