### ISSUE TITLE
Extra sound heard when pressing Return Bodies button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#314]
**Test device**
MacBook Air M1 chip and iPad

**Operating System**
14.1.2 and iPadOS 17.0.2

**Browser**
Safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1008,  when the Return Bodies button is pressed, in addition to that UI sound, I also hear the moving bodies sound (usually at a louder volume). I don't hear this in published. 

**Steps to reproduce**
Here is an example:
1. On the Intro Screen, move the Velocity vector for Body 2 so that body 2 will move off of the screen.
2. Press Play.
3. Once Body 2 is off screen, press the Return Bodies button.

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/f4a0f347-e053-464f-ba06-64a6db8ea0bb

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.3.0-dev.7 2023-12-01 16:11:20 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language: en-US
Window: 1365x706
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
I also hear something similar with the Restart button sometimes that I don't hear in published. 
For example:
1. On the lab screen, select Four Star Ballet
2. Move Body 3 so that it will collide with Body 2
3. Press play
4. After bodies collide, press Restart

**Comment by AgustinVallejo** [comment]
The above commit addresses these two findings. Please review and close if ready, @Nancy-Salpepi. Thanks!
