### ISSUE TITLE
Should the numbers entered in the keyboard be stateful?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#315]
**Test device**
iPad
**Operating System**
iPadOS 17
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/qa/issues/1008
The keypad for changing mass or other properties of the bodies is stateful in if it is open or not. Any numbers being entered are not stateful. If you press enter the new data is captured in state. If this is intended, feel free to close

**Visuals**
![numstate](https://github.com/phetsims/my-solar-system/assets/41024075/2de0395f-bb2a-49e8-9c8f-5bdac2890dec)

**Comment by AgustinVallejo** [comment]
@pixelzoom Is this a common code issue or should we take a look into it?

**Comment by pixelzoom** [comment]
Good question @KatieWoe!

Keypad statefulness is still not supported in common code, see https://github.com/phetsims/scenery-phet/issues/540.

And for the 1.3 release of this sim, we specifically punted - see https://github.com/phetsims/my-solar-system/issues/234#issuecomment-1775600082.   The only requirement is that the PhET-iO API needs to include `keypadDialog.isShowingProperty`, and we've done that.

So closing this issue as "won't fix".  @arouinfar @kathy-phet FYI.
