### ISSUE TITLE
Cherry pick changes for gravityForceScalePowerProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/my-solar-system#317]
Over in https://github.com/phetsims/keplers-laws/issues/220, we made changes to gravityForceScalePowerProperty that need to be cherry picked into my-solar-system 1.3 for RC2.

The commits to cherry-pick are:

- [x] https://github.com/phetsims/my-solar-system/commit/f55349b508e5ff2aeb39afe231bac14fd809db86
- [x] https://github.com/phetsims/my-solar-system/commit/d71d9c612be08d3ab69a040b782cb9aaf4efc3b4
- [x] https://github.com/phetsims/solar-system-common/commit/ac875636209c60a40019ae52e99ce0b1b13830a7
- [x] https://github.com/phetsims/phet-io-sim-specific/commit/a7e42ae9c87c78cb92b766dca787e1f62d3107bb

**Comment by AgustinVallejo** [comment]
Done and ready. Also linking the main issue and closing
https://github.com/phetsims/my-solar-system/issues/282
