### ISSUE TITLE
xhtml version doesn't load #1413

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#319]
MSS 1.3 should get the patch in https://github.com/phetsims/chipper/issues/1413 so that the XHTML will load.

https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.1/phet/xhtml/my-solar-system_all.xhtml (currently broken)

Cherry pick https://github.com/phetsims/chipper/commit/8c840539eb5a67b9c48a9ab07d40e424d1aacff8 to fix.

**Comment by zepumph** [comment]
Please hold off on this. The above commit didn't pass review. Wait until we hear back from @jonathanolson in https://github.com/phetsims/chipper/issues/1413#issuecomment-1863222353.

**Comment by Nancy-Salpepi** [comment]
linking to https://github.com/phetsims/qa/issues/1015

**Comment by zepumph** [comment]
Ok we have sorted things out. To cherry pick (in order):
https://github.com/phetsims/chipper/commit/8c840539eb5a67b9c48a9ab07d40e424d1aacff8
https://github.com/phetsims/chipper/commit/4496294d711b1a97222fe2291edb01036c4fbddf

**Comment by AgustinVallejo** [comment]
Done and ready. Also linking the main issue and closing
https://github.com/phetsims/my-solar-system/issues/282
