### ISSUE TITLE
Improvements to Mass Sliders 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/my-solar-system#32]
On both the Intro and Lab screens the sliders have a few issues.

1. I think the sliders should have less granularity. Currently it is difficult to easily make ratios of masses (for instance double the planet mass). Especially on the intro screen, I don't actually think we need decimal precision for the sliders. I think even and increment of "5" could work just fine. But at minimum I think the increment should be "1" (the video below shows difficulty in achieving certain values)

2. As seen in the recording below, the slider "thumbs" change to their default color blue upon hover/click. This behavior does not follow PhET convention, as slider thumbs usually go to a lighter shade of their color. The more traditional highlighting behavior should be used.

3. Also seen in the recording below, the readout for mass gets a highlight yellow background when the mass is adjusted. I think this highlighting behavior is not necessary. If you want to use some sort of highlight, the yellow seems like a poor choice as it seems to have meaning for the yellow mass, but does not match the pink mass. If you really want highlight the readout consider using a very light shade of the mass as a background highlight. However, we generally have not found it necessary to use this sort of highlight as the readout is well associated with the slider and the feedback is quite clear. 

Discovered as part of #29

https://user-images.githubusercontent.com/4051174/201812422-139c9986-0a8f-4609-9115-a531209c7a7e.mp4

**Comment by AgustinVallejo** [comment]
Hello @ariel-phet, thanks for the observations. Regarding the third point, we are following what was done in Collision Lab, where the boxes get the yellow highlight when directly modified or indirectly, by dragging the bodies. Let me know if your opinion on that issue changes after seeing collision lab.

**Comment by ariel-phet** [comment]
@AgustinVallejo @DianaTavares I was no aware this was the behavior in Collision Lab, and that actually seems like an oversight/error in collision lab. So for this sim I would definitely not have the highlight.

**Comment by AgustinVallejo** [comment]
2022-11-17:

Design Meeting:
- Add a "<0.1" for small masses.
- Make the thumbs colors noticeably lighter.
- Add back number display highlighting.
- Leave one decimal place.
