### ISSUE TITLE
No longer able to press and hold Step Forward button

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#321]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1015, I am no longer able to press and hold the Step Forward button with my mouse on either screen. Works just fine in 1.3.0-dev.7.

**Comment by AgustinVallejo** [comment]
The above changes fix this, please review @Nancy-Salpepi and assign back to me for cherry picking if done.

**Comment by Nancy-Salpepi** [comment]
This is still broken.

**Comment by AgustinVallejo** [comment]
Weird, it seems I didn't commit a part of this solution. Sorry for that, please review again.

**Comment by Nancy-Salpepi** [comment]
OK. Looks good now. Ready to 🍒pick.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.4 
Closing.
