### ISSUE TITLE
Restart enabled after changing orbital systems

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#322]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1015, on the Lab screen, the Restart button is enabled if the orbital system is changed while the sim is playing. This is not seen in 1.3.0-dev.7. 

**Steps to reproduce**
1. On the lab Screen, press the Play button
2. Change the Orbital System in the combobox

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/52621b30-7912-4286-a1d8-8f8ffca0e298

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.3.0-rc.1 2023-12-11 18:43:03 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language: en-US
Window: 1372x727
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Assigning back for review @Nancy-Salpepi, if done, please assign back to me to cherry pick. Thanks!

**Comment by Nancy-Salpepi** [comment]
@AgustinVallejo 
The restart button is still enabled if I switch to custom. I just wanted to confirm that this is the desired behavior when intentionally picking "custom" from the combobox? That is also the behavior in published. 
If that is the correct behavior, this issue is ready for cherry-picking.

**Comment by AgustinVallejo** [comment]
I'm making some slight changes to the current behavior. As 'custom' does not change any of the physical properties, it's okay that it just keeps on playing. Furthermore, it will no longer erase the path nor disable the restart button. In essence, selecting custom manually won't do much, and it will be auto selected if making physical changes to the sim (position, mass or velocity).

**Comment by Nancy-Salpepi** [comment]
Your changes look good on main--switching to custom doesn't do anything. The path remains, the sim still plays, and the Restart button is still enabled. Pressing the Restart button returns the bodies to their default positions from the last chosen orbital system (ex. If I switch from "Sun, Planet" to "Custom", the sun and planet will return to the default settings of the "Sun, Planet" scene when pressing Restart).
