### ISSUE TITLE
Center of Mass position may not be consistent at low masses

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#323]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/1015
When the mass of the planets/objects is small, the position of the center of mass can be inconsistent and dependent on which object last had a larger mass. This occurs in the published sim as well and may not be worth addressing.
**Steps to reproduce**
1. Go to the Lab screen
2. Turn on the center of mass x and the grid
3. Go to the ellipses scene
4. Turn the sun down to <= .1 mass
5. Turn a planet up to a higher mass, then back to the minimum

**Visuals**
![cm1](https://github.com/phetsims/my-solar-system/assets/41024075/5de7b8ec-615e-4ff3-b4ea-4c4bdb80408a)
![cm2](https://github.com/phetsims/my-solar-system/assets/41024075/018dd26c-1406-4f92-9d2c-b068588113ad)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.3.0-rc.1 2023-12-11 18:43:03 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
This can be deferred. The initial mass of the planets in that system is like 0.000001, which shows as <=0.1. So when you slide up and then down, the mass goes from that tiny value to actually 0.1 (still shows up as <=0.1), so it makes sense that the CoM changes positions.
