### ISSUE TITLE
Performance much worse than in published [Chromebook]

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#326]
**Test device**
Chromebook 100e

**Operating System**
ChromeOS 119

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1015, the performance with the Chromebook is significantly worse in 1.3.0-rc.1 than in published. 

**Visuals**
rc.1:

https://github.com/phetsims/my-solar-system/assets/87318828/267a6cee-e055-4542-b114-e5ac117472d8

published:

https://github.com/phetsims/my-solar-system/assets/87318828/419beb63-2f73-4102-bc62-9b146f83e8bb

**Comment by KatieWoe** [comment]
I see the same thing in the chromebook in the office. Performance is much worse than in published.

**Comment by pixelzoom** [comment]
It's unfortunate that this was not discovered until RC testing.  In https://github.com/phetsims/qa/issues/1025, I've proposed including a Chromebook performance test as part of all dev tests.

**Comment by AgustinVallejo** [comment]
Yes, we're pretty sure it could be happening either there, on in the stepOnce method, which in theory has a part which ensures the sim runs an N number of steps per second. Both were changed since last publication and are probably the main reasons. Currently investigating.

**Comment by AgustinVallejo** [comment]
I implemented the potential fix, please review in Chromebook and let me know.

**Comment by Nancy-Salpepi** [comment]
Things look much better to me. I would also like @KatieWoe's opinion.

**Comment by KatieWoe** [comment]
I didn't catch this while in the office and don't have a chromebook at the moment. I'll be sure to check this in the next round of testing.

**Comment by KatieWoe** [comment]
Looks good in RC 4 to me
