### ISSUE TITLE
Path doesn't disappear when adding more bodies

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#329]
**Test device**
MacBook Air M1 chip

**Operating System**
14.1.2

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1015, on the Lab screen, a body's path won't disappear when adding more bodies if the orbital system had been previously changed (ex. changing the mass, velocity or location of a body). This behavior is different than if bodies are added while not in "custom". 

**Steps to reproduce**
1. On the Lab screen, change the velocity vector for body 2 (or mass or location)
2. Press Play
3. Increase the number of bodies to 3 

**Visuals**

https://github.com/phetsims/my-solar-system/assets/87318828/0a416932-c986-428a-8b93-fce240f8a780

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.3.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.3.0-rc.1 2023-12-11 18:43:03 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language: en-US
Window: 1379x726
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
This behavior changes in main due to https://github.com/phetsims/my-solar-system/issues/322. Adding new bodies does not disrupt the path anymore. I think it's better that way. Right now the only interaction that deletes the path is dragging the body itself or changing the system. 

Assigning to @arouinfar to make sure it's desired behavior. Please close if it is.

**Comment by arouinfar** [comment]
Thanks for reporting @Nancy-Salpepi. 

Discussed with @AgustinVallejo and @pixelzoom on 1/5/23, and the consensus was that the behavior in the RC was acceptable. Closing as wont-fix.
