### ISSUE TITLE
What should determine the location/mass/velocity of additional bodies?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#330]
For https://github.com/phetsims/qa/issues/1015, I noticed that the properties of a body added to a system are determined by the last system that had that body (what terrible wording!). For example, if I select "Four Star Ballet" and then select "Binary Star, Planet" and add the 4th body, that body will appear with the same location/mass/velocity as it had in Four Star Ballet. Pressing Play results in the first and forth bodies immediately colliding. 
If I had selected "Hyperbolic" first, the 4th body would have appeared in that position. Is this inconsistency OK? 

https://github.com/phetsims/my-solar-system/assets/87318828/3bb7bde9-8858-4ce5-9e1d-189f6710942b

**Comment by AgustinVallejo** [comment]
I implemented a patch that would add a default position for inactive bodies, constant for all systems. They'd be to the sides of the screen with low masses and elliptical orbits, and shouldn't disrupt any of the default systems when added. In the following picture they were added in Sun-Planet, their trajectories in green and blue. @arouinfar let me know if this is a desirable update.
![image](https://github.com/phetsims/my-solar-system/assets/37052186/4d45e4b4-7afe-4708-84d2-817f76ddca2a)

**Comment by AgustinVallejo** [comment]
The new default position seemed satisfactory for @arouinfar. Applying changes and giving back for review.

**Comment by Nancy-Salpepi** [comment]
@AgustinVallejo if I add the bodies without making any changes first, they will always appear in the places you described. If I change the location or mass of an existing body and then add additional ones, they appear in a different place. Is it possible to make this change to a "custom" system?

**Comment by Nancy-Salpepi** [comment]
I am glad you asked me to make you a video because it actually happens AFTER pressing Reset All. 

Steps:
1. Add 2 bodies to the Sun, Planet scene
2. Press Reset All
3. Add 2 bodies again --they appear in different places

https://github.com/phetsims/my-solar-system/assets/87318828/570f60d5-97d5-4e80-9a55-629bba9d7af6

**Comment by AgustinVallejo** [comment]
You're right, missed that spot. The above changes should resolve this.

**Comment by Nancy-Salpepi** [comment]
Looks good now 🙂
