### ISSUE TITLE
drag listener not interrupted when pressing Reset All 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#333]
**Test device**
iPad 

**Operating System**
17.2

**Browser**
Safari 

**Problem description**
For https://github.com/phetsims/qa/issues/1015 and similar to https://github.com/phetsims/my-solar-system/issues/313, if I am holding a body, velocity vector or mass thumb/button, pressing Reset All doesn't reset the sim to default settings. 

**Steps to reproduce**
Here is an example:
1. On the Intro screen, move and hold the Velocity vector for Body 2 with one finger
2. Press Reset All with another finger

**Comment by Nancy-Salpepi** [comment]
I only see this issue on the Intro Screen.

**Comment by AgustinVallejo** [comment]
Assigning back for review

**Comment by Nancy-Salpepi** [comment]
Looks good on main.

**Comment by Nancy-Salpepi** [comment]
looks good in rc.4
Closing
