### ISSUE TITLE
Consider removing some levels of "zoom in"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/my-solar-system#34]
Is there a good reason to have so many levels of ability to "zoom in"? I can see many situations where it would be useful to be able to zoom out, but on the default settings, the objects quickly go offscreen with the highest level of zoom.

Unless there is a good pedagogical reason, I would minimize the number of "zoom in" levels.

Seen as part of #29

**Comment by AgustinVallejo** [comment]
Changed from 7 zoom levels to just 4. It goes from x0.5 to x1.25, default value is 1.00. Ready for review and discussion.
