### ISSUE TITLE
Some polish suggestions

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/my-solar-system#37]
A couple of polish suggestions as part of #29

1. Consider more vertical padding between items in the main control panel. It seems like there is lots of vertical room, and items in this panel seem quite tight (for instance the measuring tape and grid icon are very close together as well as the path icon to the combo box)

2. On the lab screen, the negative space in the more data panel could be improved. Currently the panel is quite tight on the left and right edges. Perhaps something a bit more like shown below.
![Screenshot 2022-11-14 235852](https://user-images.githubusercontent.com/4051174/201852410-986c37c9-d80a-4fdd-8f9e-3bd42eec605e.png)

**Comment by DianaTavares** [comment]
I agree in both suggestions!
