### ISSUE TITLE
Usability issues with velocity adjustment

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/my-solar-system#38]
@DianaTavares @AgustinVallejo as part of #29 I think we might need to do some more design thinking around the way that velocity is controlled, at least on the intro screen.

I think the velocity control works reasonably well for the "planet" on the intro screen, and this control follows a general pattern we have used successfully in Gravity and Orbits.

However, as illustrated in the picture below, there are several issues when it comes to the velocity control on the "star" under default conditions.

1. With the Center of Mass, Gravity Force, and Velocity control checked, the various representation in the vicinity of the Sun are extremely cluttered and difficult to distinguish.

2. The velocity arrow on the sun is very small, and difficult to see with the large "V" on the sun

3. It can be difficult to interact with the correct control when dealing with the sun. If you want to merely move the object but not change the velocity, this action is difficult to achieve.

![MSS sun velocity](https://user-images.githubusercontent.com/4051174/202081139-b38d816c-0ce8-4d25-8264-5a7e4530d147.png)

A few potential remedies to these issues:

1. Allow the velocity of the sun to be shown but not adjusted on the intro screen -- that would make the arrow for velocity more obviously visible, but would limit some of the learning goals

2. Have separate check boxes for the velocity control for the sun and planet on the intro screen. That might make things a bit more clear, a bit easier to parse.

3. (My preferred solution). Move the "Circle and V" to the tip of the velocity arrow. That way the control would be nicely displaced from the Sun, and I think it would all still be quite useable.  A rough sketch (done on the planet velocity control) shown below

![MSS sun velocity 2](https://user-images.githubusercontent.com/4051174/202082218-185d9a67-f982-4f22-973f-fdf2d685a45f.png)

**Comment by DianaTavares** [comment]
I like the option to move the "Circle and V" to the tip of the velocity arrow. I think that when center of mass and gravity are active, all these elements are going to continue being very close together. But with this change, the students can see the size of the velocity vector, and have some space of the sun to drag it to move the yellow circle. 

I play with Collision lab to see if it has the same problem, but in the simulation:
 1) the "Circle and V"  is smaller and not bold, 
2) the smaller object in this simulation is the same size that the circle of the velocity, not like in MSS, where the circle is bigger than the sun.

![image](https://user-images.githubusercontent.com/26031501/202271898-07155f3a-00f7-4e2c-90dc-6590f2e21206.png)

Then we can move the circle to the tip of the arrow, make the circle smaller and use thinner lines (match the circle of collision lab), and can the bodies be bigger? Currently, this is the smaller and bigger that bodies can be in MSS:
![image](https://user-images.githubusercontent.com/26031501/202271604-85375f06-1714-4a5c-a910-64f05d616e2f.png)

Have bigger objects just affect the smaller orbits that can be created:  

something like this: 
![image](https://user-images.githubusercontent.com/26031501/202274308-049668d1-0191-4d6c-b03d-44ccc04dc1e0.png)
 
and bodies three times it size:
![image](https://user-images.githubusercontent.com/26031501/202275719-2171ae9d-1ab4-44d7-9c13-37c09e73096e.png)

**Comment by AgustinVallejo** [comment]
The problem with having bigger bodies is that the Sun-Planet-Moon system stops working for bigger sizes, as the moon is fairly close to the planet and they collide very fast... Should we look for different presets?

**Comment by DianaTavares** [comment]
In that case, let's try with moving the "Circle and V" to the tip of the velocity arrow, making the circle smaller, and, if it is necessary, changing to a thinner lines. What do you think @AgustinVallejo ?

**Comment by AgustinVallejo** [comment]
Decisions on Design Meeting of 2022-11-18:
- To leave Draggable Vector visualization as it is, for the logic would not be clear for small velocities.
- To leave the sizes mapping the same, except for presets where the mass is <0.1
