### ISSUE TITLE
Scene reset doesn't return to new set-ups

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#41]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/860.
According to @DianaTavares on Slack the scene reset (blue reset) button should set the objects to their previous initial conditions. So if you set up new positions and masses, that button should take you to your latest set up. However, it seems this button works as a reset all, returning objects to the first initial position and mass.

**Visuals**
![sceneresetbug](https://user-images.githubusercontent.com/41024075/204662745-d5d7405a-24bb-4866-af6e-2da712605131.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
Hello, can you verify that it is fixed on master? Thanks!

**Comment by DianaTavares** [comment]
It is working very well for me!! I let @KatieWoe review it more deeply!

**Comment by KatieWoe** [comment]
This does seem to be fixed on master
