### ISSUE TITLE
Blue and Green planet crash by default

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#42]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/860
In the lab screen, if you turn on the 3rd and 4th objects and press play with their default settings, the 3rd and 4th objects crash into each other. If this is the intended behavior feel free to close.

**Visuals**
![bluegreencrash](https://user-images.githubusercontent.com/41024075/204668421-2609dae7-9564-4e53-899b-e9290e518ca4.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
Hello, can you verify that it is fixed on master? Thanks!

**Comment by Nancy-Salpepi** [comment]
This looks fixed on master.

**Comment by stemilymill** [comment]
I don't know if this is as significant a problem, but in the default sun, planet, moon scene the moon and planet crash at around 5 years (checked on master)

**Comment by Nancy-Salpepi** [comment]
The same thing happens with Four Star Ballet between 8-9 years. I figured it was supposed to happen.... @AgustinVallejo?

**Comment by Nancy-Salpepi** [comment]
@DianaTavares perhaps https://github.com/phetsims/my-solar-system/issues/42#issuecomment-1333925631 is something to include in Teacher Tips if you haven't already?

**Comment by DianaTavares** [comment]
Yes, definitely something to include in teacher tips! But we don't usually include teacher tips in prototypes.
