### ISSUE TITLE
Reset all does not reset extra object positions

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#43]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/860
The reset all button does not reset the position of the green and blue planets.
**Steps to reproduce**
1. Go to the lab screen
2. Add the 3rd and 4th planets
3. Move the 3rd and 4th planets to new positions
4. Hit reset all
5. Add 3rd and 4th planets again

**Visuals**
![resetallposition](https://user-images.githubusercontent.com/41024075/204672117-10bc33fc-fcfa-439b-9a2a-196a53101771.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
Hello, can you verify that it is fixed on master? Thanks!

**Comment by Nancy-Salpepi** [comment]
This looks fixed on master @AgustinVallejo

**Comment by Nancy-Salpepi** [comment]
Wait....this isn't fixed

**Comment by AgustinVallejo** [comment]
I think this commit fixed it for real, could you please double check? Sorry for all the false positives!

**Comment by KatieWoe** [comment]
Reset all now seems to be doing something where, if the objects are in their original positions already, things are reset to this new position: 
![odd](https://user-images.githubusercontent.com/41024075/204905503-d0a7b208-d418-40e9-a429-70dcfd6b5d58.png)

**Comment by Nancy-Salpepi** [comment]
This is looking really good to me as far as the Reset All button goes. I do see an issue with the Reset button now, which is similar. Not sure if it is a new issue, related to this one or related to https://github.com/phetsims/my-solar-system/issues/41
1. On the lab screen add 2 more bodies
2. Crash the blue one into the Sun
3. Press the Reset Button

https://user-images.githubusercontent.com/87318828/204910667-2a663b9c-2309-4338-8cba-eabf526aac63.mp4
