### ISSUE TITLE
Crash animation may play during a reset all

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#44]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/860
On the lab screen, if you drag one object into another and hit reset all, an extra crash animation plays during reset. I didn't see this on the intro screen or when a crash happened while an orbit was playing.
**Steps to reproduce**
1. Go to the lab screen
2. Grab one of the planets and drag it into the sun
3. Hit reset all

**Visuals**
![explode](https://user-images.githubusercontent.com/41024075/204672885-dffb103f-2abf-4c12-a464-3d380055d9b4.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
I believe this fixed itself while correcting https://github.com/phetsims/my-solar-system/issues/43 
Let me know if it shows again or if its fixed on Master as well. Thanks.

**Comment by KatieWoe** [comment]
This does seem to be fixed on master
