### ISSUE TITLE
Path checkbox doesn't appear on some platforms

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#45]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/860. Not seen on the same device in Firefox. @DianaTavares also didn't see it on Mac + Chrome. This is a bizarre one I haven't seen before.
The Path checkbox did not appear on Win 11 Chrome.

**Visuals**
<img width="960" alt="orhere" src="https://user-images.githubusercontent.com/41024075/204673808-7e6e04d1-3372-4f70-b614-b4304ea2568f.png">
<img width="960" alt="nothere" src="https://user-images.githubusercontent.com/41024075/204673809-613c526f-985b-45bd-98a4-7c76579342c0.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment]
@jonathanolson Might this be something we added to disable that checkbox when WebGL wasn't available? Should we remove it? Since we're no longer using WebGL

**Comment by jonathanolson** [comment]
That's likely the case. If we proceed with the canvas approach, we can undo that change.

**Comment by AgustinVallejo** [comment]
Hello, can you verify that it is fixed on master? Thanks!

**Comment by KatieWoe** [comment]
Using `?webgl=false` this seems to be fixed on master.

**Comment by KatieWoe** [comment]
Extra note: I discovered why webgl wasn't working on my one platform and did fix it.
