### ISSUE TITLE
Possible to lose measuring tape

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#47]
**Test device**
MacBook Air m1 chip

**Operating System**
13.0.1

**Browser**
safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/860, there doesn't seem to be any dev bounds for the measuring tape. 

**Steps to reproduce**
1. On either screen, zoom out as much as possible
2. Check Measuring Tape
3. Toss the Measuring Tape off the screen 

**Visuals**

https://user-images.githubusercontent.com/87318828/204804994-ccccc3a7-52c0-464e-b8ed-7cf3cda1de14.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1564x732
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Hello! Please see that the measuring tape is now properly bounded in Master. Thanks!

**Comment by Nancy-Salpepi** [comment]
I can't lose it anymore but I don't think I should be able to move it in front of the panel. Comparing it to Gravity and Orbits, the measuring tape bounds seem to end at the panel and if the tape is actually extended, it is behind the panel:
<img width="520" alt="Screenshot 2022-11-30 at 11 58 35 AM" src="https://user-images.githubusercontent.com/87318828/204860746-860b6849-7762-414c-bdeb-69611aeddd63.png">

**Comment by AgustinVallejo** [comment]
What does @DianaTavares think? Right now it is bounded by the screen border, but it can be bounded to this red box:
![image](https://user-images.githubusercontent.com/37052186/204864221-20dd864f-3325-4e33-a511-71d128c3584c.png)

The problem would be that for small vertical screens, it would be constrained by just a small space, like in this image:
![image](https://user-images.githubusercontent.com/37052186/204864507-d0b06eb5-6805-45ee-8704-23a957463169.png)
