### ISSUE TITLE
Difficult to see Path icon in projector mode

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#48]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0.1

**Browser**
Safari 16.1

**Problem description**
For https://github.com/phetsims/qa/issues/860, when in projector mode, the icon color for the Path checkbox doesn't change to black making it hard to see. In Gravity and Orbits, the Path Icon changes to black when Projector Mode is on. 

**Visuals**
My Solar System:
<img width="196" alt="Screenshot 2022-11-30 at 8 44 30 AM" src="https://user-images.githubusercontent.com/87318828/204813132-77895e67-8f75-474a-b4b2-0d9c61b36589.png">

Gravity and Orbits:
<img width="147" alt="Screenshot 2022-11-30 at 8 43 32 AM" src="https://user-images.githubusercontent.com/87318828/204813176-54cd391d-6aef-46c7-bc56-01c6c371d679.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1564x732
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Hello, can you verify that it is fixed on master? Thanks!
