### ISSUE TITLE
Body position range seems very large

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#50]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/860, it is confusing to me that on the Lab Screen I can change the value of 'x' and 'y'  from -400 to 400 AU when most of these values move the body off the screen (even when completely zoomed out). As discussed on slack with @AgustinVallejo, perhaps a smaller settable range would make more sense?

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1564x732
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by AgustinVallejo** [comment]
Hi, this should now be corrected, please double check :)

**Comment by Nancy-Salpepi** [comment]
@AgustinVallejo what are the new limits?

**Comment by Nancy-Salpepi** [comment]
When testing the new range, the sim froze with this error:
<img width="1276" alt="Screenshot 2022-11-30 at 1 45 17 PM" src="https://user-images.githubusercontent.com/87318828/204882433-592566bd-3282-4480-a947-6bc472154a9f.png">

**Comment by AgustinVallejo** [comment]
This one was weird, floating point error I guess... Hacked my way around it by changing the position multiplier from 0.1 to 0.11, which doesn't change the sim but fixes this issue. Ideas @jonathanolson ?

Can you verify @Nancy-Salpepi ?

**Comment by Nancy-Salpepi** [comment]
It is still broken. Sorry.

https://user-images.githubusercontent.com/87318828/204904107-c9a6b5cb-5c57-4473-8da6-910cd93718a5.mp4

**Comment by Nancy-Salpepi** [comment]
Steps:
In Master:
1. Go to the lab screen
2. Add 2 more bodies
3. Select more data
4. Change the x position of the green body from -1.1 to 1.7

**Comment by jonathanolson** [comment]
The reentrance is fine here, tagged the Property to allow that above.

**Comment by KatieWoe** [comment]
Things look ok in rc.1. If something comes up we'll reopen.
