### ISSUE TITLE
Reset All button not working correctly on master

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#51]
*Test device**
MacBook Air m1 chip

**Operating System**
13.0.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/860, on master the Reset All button isn't working properly anymore. Perhaps it was broken while fixing https://github.com/phetsims/my-solar-system/issues/43?

**Steps to reproduce**
1. On either screen, press Play
2. Press Reset All

**Visuals**

https://user-images.githubusercontent.com/87318828/204885623-6e22445d-109d-4f4c-ac4a-228a88cf9a4e.mp4

**Comment by AgustinVallejo** [comment]
Yes, forgot to double check Intro screen. Should be functional now, thanks!

**Comment by Nancy-Salpepi** [comment]
It is still broken on the lab screen.

**Comment by AgustinVallejo** [comment]
Can you show me what seems broken? On my end it works as intended and have no working changes

**Comment by Nancy-Salpepi** [comment]
I just cleared my history and tried again. I still see the issue. 
The planet doesn't return to its original position. 
https://user-images.githubusercontent.com/87318828/204901461-1833c049-3fe1-428f-8ba7-e0f9339dca1a.mp4

**Comment by AgustinVallejo** [comment]
Yes, saw the comment in https://github.com/phetsims/my-solar-system/issues/43 and should be fixed now.

**Comment by Nancy-Salpepi** [comment]
Since this is related to #43 I'm going to go ahead and close this.
