### ISSUE TITLE
Should the Mass panel be an accordion panel? 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#53]
For https://github.com/phetsims/qa/issues/860, I thought it would be nice to be able to collapse the Mass panel to see as much of a body's orbit as possible.....especially when there are 4 bodies present. What do you think @DianaTavares?

<img width="1089" alt="Screenshot 2022-11-30 at 5 07 13 PM" src="https://user-images.githubusercontent.com/87318828/204918487-46a879a5-fd4f-4afe-b8f1-41050367519c.png">

**Comment by DianaTavares** [comment]
Interesting suggestion! Only in math sims I have seen controls in collapsible panels. I see the good thing of more play area, but hide the readout and manipulation of an important variable. I need to discuss it with the design team.

**Comment by AgustinVallejo** [comment]
Design meeting decision: No.

**Comment by AgustinVallejo** [comment]
Reopened for potential future discussion.

**Comment by AgustinVallejo** [comment]
Design decision is final: No masses accordion pannel.
