### ISSUE TITLE
Unclear range of mass when entering

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#54]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/860
When manually entering an object's mass, you are instructed to enter "0.1 to 300 x10^28 kg". The 10^28 kg is a unit for both numbers, and you need to enter .1 to 300. But the way I read this was enter a number .1 kg to 300x10^28. Clearer wording may need to be considered.

**Visuals**
![instructions](https://user-images.githubusercontent.com/41024075/204930833-8ba559a3-a43d-417c-96e3-a84ba56ab485.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by DianaTavares** [comment]
I agree with this suggestion.  I can't think of another way this text could be improved. My solution is removed the units from these controls (for all the variables for coherence). I don't think we need units here, just indicate what range of values can be entered. The units are in the readouts, and with the highlight, it is easy to know the variable that is being modified. What do you think @AgustinVallejo ?  If you agree, please take the actions in the code, if not, share your ideas here.

**Comment by AgustinVallejo** [comment]
I had initially thought to include a paretheses: (0.1 to 300) x10^28kg or even distribute the units: 0.1x10^28kg to 300x10^28kg. But I like way more just removing the units and telling the user what values to include, the units are in the main panel. Will do!

**Comment by DianaTavares** [comment]
Let's remove the units! In your hands, Agustin :D

**Comment by KatieWoe** [comment]
Secondary note. While the units are on the main panel in the lab screen, they aren't on the intro screen. It may be good to add it there as well.

**Comment by DianaTavares** [comment]
The true @KatieWoe, is that we did that thinking in intro learners that can get confused by the scientific notation, but it is illogic not to have units only in the mass variable of the intro screen. All the other variables have units! @AgustinVallejo  -i think we need to add the units in the mass control of intro.

**Comment by KatieWoe** [comment]
If we want to avoid scientific notation, could the unit label be "Jupiter masses" or something like that?

**Comment by AgustinVallejo** [comment]
Please verify that it works on master now!

**Comment by KatieWoe** [comment]
Looks good to me!
