### ISSUE TITLE
When should the sim automatically pause?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#55]
**Test device**
MacBook Air (m1 chip) and iPad 9th generation

**Operating System**
macOS 13.0.1 and iPadOS 16

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/860, it is unclear to me when the sim should automatically pause. For example, on the lab screen, after pressing play in any scene, moving a body pauses the sim and changes the scene to "Custom." If I press play again, and move a body, the sim no longer pauses. Also, if I start in Custom, press Play and move a body, the sim doesn't pause at all. Is that correct behavior?

**Visuals**

https://user-images.githubusercontent.com/87318828/205081172-86b9eee6-7ea4-438b-bf97-49eba76f3781.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1564x732
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by DianaTavares** [comment]
Good observation! I have the next ideas:

- Modify the mass of the objects with the slider: not need to pause the simulation. It is fun to see how the movement change while modify the masses.  
- Modify the position and velocity of the objects by dragging them: pause the sim, and restart the path
- Open number pad: pause the sim by simple opening it. If noting is modified, the sim can automatically continue moving, but if something is modified, restart the path and the user need to click play again. 
- Add or remove bodies manually: pause the sim and restart the path.

What do you think @AgustinVallejo? Do you agree or better to bring this discussion to Design Meeting?

**Comment by KatieWoe** [comment]
Instructions in https://github.com/phetsims/my-solar-system/issues/55#issuecomment-133416937 seem to work. Will reopen if something else comes up or other cases are thought of.
