### ISSUE TITLE
Stepping Forward sometimes prevents bodies from crashing

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#56]
**Test device**
MacBook Air (m1 chip) and iPad 9th generation

**Operating System**
macOS 13.0.1 and iPadOS 16

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/860, using the step forward button, sometimes skips over when bodies crash resulting in a body still being there. 

**Steps to reproduce**
Example:
1. On the lab screen, select the Trojan Asteroids scene
2. Move the blue body so that it is in line between the yellow and magenta bodies
3. Press Play--the blue body should crash into the sun and explode
4. Press Reset
5. Use the Step Forward button--the blue body no longer crashes into the sun and explodes

**Visuals**

https://user-images.githubusercontent.com/87318828/205088026-661a1a9e-8a53-4877-8232-8a504f0e333b.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-dev.7/phet/my-solar-system_all_phet.html
Version: 1.0.0-dev.7 2022-11-29 20:47:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1564x732
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
Looking at the Hyperbolic scene, you can see that the path is a little different for the magenta body when using stepping forward vs. play.
With Stepping Forward:
<img width="859" alt="Screenshot 2022-12-01 at 10 20 42 AM" src="https://user-images.githubusercontent.com/87318828/205091533-f217e9d0-fdb3-4fbb-8e95-a54def3b4c10.png">

With Play:
<img width="859" alt="Screenshot 2022-12-01 at 10 20 04 AM" src="https://user-images.githubusercontent.com/87318828/205091575-dffdd664-4246-48cb-9e8a-2f119170280b.png">

**Comment by jonathanolson** [comment]
The commit above should help with both the collisions and the path resolution (without significantly impacting performance). @Nancy-Salpepi can you verify?

**Comment by KatieWoe** [comment]
Things look better in rc.1. Will reopen if something else comes up.
