### ISSUE TITLE
Some aspects of sim may affect individuals with photosensitivity issues

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/my-solar-system#57]
For https://github.com/phetsims/qa/issues/860, I felt like when the sim is in Fast mode, with large gravity force lines spinning around, it creates a situation that may be harmful to people with photosensitivity issues. I know we have never done this before, but maybe we need some sort of warning to users like we see at the beginning of TV shows. Just a thought. 

For example, on the iPad:
1. Go to the lab screen
2. Select Double Double scene
3. Check Path, Gravity Force, Velocity, and Grid Lines checkboxes
4. Select fast mode
5. Press play

The video doesn't totally capture it, but I think you will see what I mean. 

https://user-images.githubusercontent.com/87318828/205114562-108ba48f-0390-417e-86d7-941b6507a67c.mov

**Comment by DianaTavares** [comment]
Let's leave this suggestion to design meeting. Not need to be included in the prototype, but may be something to consider for other sims.

**Comment by DianaTavares** [comment]
Thanks @Nancy-Salpepi for bringing to the design discussion this issues. For @AgustinVallejo and I were hard to decide when to show the warning message. Other PhET sims also get very crowed and had fast animations if the user goes to the extreme of activating everything and making the movement fast. But  also users have the control to avoid that behavior, and also come back to something that not affect them, like with one click stop the animation, or make it slower, or just reset the sim. Then we diced no to take an action about this issue and close it.
