### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#58]
For https://github.com/phetsims/qa/issues/860.
A memory test on the Dev version, with the first result taken at the start and subsequent results taken every minute, suggest a small, but noticeable and persistent memory leak.
<img width="350" alt="memleak" src="https://user-images.githubusercontent.com/41024075/205123610-51c6bb7c-6bc7-4808-b8fc-9845dc488406.png">

**Comment by AgustinVallejo** [comment]
Closed as completed.
