### ISSUE TITLE
Should entering data with the keypad set a new start for scene reset?

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/my-solar-system#59]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/861
Should entering data with the keypad set a new start for scene reset? Currently, if you move an object by dragging it, change its mass with the slider, or change its velocity with the vector, the scene reset will reset to your new conditions. However, if you change these values with the keypad then scene reset does not reset to your new values, but to the values before these changes.
**Steps to reproduce**
1. Go to the lab screen
2. Turn on the more data screen
3. Make changes using the keypad
4. Press play
5. Press the reset scene button

**Visuals**
![keypadreset](https://user-images.githubusercontent.com/41024075/205356586-7bb11a92-e455-4a4e-b328-c1ec267a0795.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪My Solar System‬
URL: https://phet-dev.colorado.edu/html/my-solar-system/1.0.0-rc.1/phet/my-solar-system_all_phet.html
Version: 1.0.0-rc.1 2022-12-01 23:23:12 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</detail>

**Comment by AgustinVallejo** [comment]
It should happen, but probably not for this prototype deployment

**Comment by KatieWoe** [comment]
This looks ok in the spot check
