### ISSUE TITLE
My Solar System - Publish 1.2

### ISSUE THREAD

**Issue by markgammon** [phetsims/my-solar-system#6]
Publish My Solar System simulation.

- [ ] https://github.com/phetsims/my-solar-system/issues/1

**Comment by arouinfar** [comment]
4/5/23 dev test was created (phet-brand only)
* https://github.com/phetsims/qa/issues/927

4/14/23 dev testing was completed.

**Comment by arouinfar** [comment]
4/28/23 1.1.0-rc.1 was created (phet-brand only). Due to an issue with the SHAs, the 1.1 branch was abandoned, and QA is now testing 1.2.0-rc.1
* https://github.com/phetsims/qa/issues/935

**Comment by arouinfar** [comment]
5/5/2023 1.2.0-rc.2 started testing (spot-check)
* https://github.com/phetsims/qa/issues/940

5/9/2023 testing completed
5/12/2023 1.2 deployed to website
