### ISSUE TITLE
Credits needed before prototype publication

### ISSUE THREAD

**Issue by arouinfar** [phetsims/my-solar-system#65]
Related to https://github.com/phetsims/qa/issues/861

@AgustinVallejo @jonathanolson the sim credits are currently empty.
<img width="460" alt="image" src="https://user-images.githubusercontent.com/8419308/205736683-5a743eed-ab73-492a-97ec-cbc1eb0874f1.png">

@DianaTavares @KatieWoe please confirm who should be credited and assign to @AgustinVallejo. Here are the sections:

```
  credits: {
    leadDesign: '',
    softwareDevelopment: '',
    team: '',
    qualityAssurance: '',
    graphicArts: '',
    soundDesign: '',
    thanks: ''
  },
```

**Comment by KatieWoe** [comment]
Jaron Droder, Clifford Hardin, Emily Miller, Nancy Salpepi, and Kathryn Woessner are the QA credits as of RC.1

**Comment by DianaTavares** [comment]
My name  is correct in the last version shown on slack
![image](https://user-images.githubusercontent.com/26031501/205755166-a1219485-b940-4531-af0b-fd8bcb065b00.png)

I assign @AgustinVallejo to this issue to correct the QA team mentioned by @KatieWoe
