### ISSUE TITLE
Inconsistency on bodies position

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#66]
I'm opening a issue for one of the bugs found in [this tweet](https://twitter.com/kilroi22/status/1600166815006543878?s=20&t=RwU48Tg9eyzXZZLYptTjBQ), more specifically, for the body that was at 2AU but the Number Display said 2.2AU... The fix was fairly simple, it was just a constant that I had accidentally changed from 0.01 to 0.011, should now be fixed.

Opening a RC spot check test to move ahead with the maintenance release.

**Comment by KatieWoe** [comment]
This looks ok in the spot check
