### ISSUE TITLE
Apoapsis and Periapsis info text

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#7]
I have been working on the info text about Apoapsis and Periapsis.

One option is:
In a 2-body system in which each object follows an elliptical orbit around the system's center of mass, the Apoapsis is the farthest point of the trajectory from the center of mass, and the Periapsis is the closest point. If one of the bodes is our Sun, the names change to Aphelion and Perihelion, and if the bodies are the Earth and the moon or other artificial satellites, the name change to Perigee and Apogee.

But after reviewing this website:  https://astronomy.swin.edu.au/cosmos/p/Periapsis  and Wikipedia, looks like the definitions of Apoapsis and Periapsis are about the distances between the bodies and not the center of mass. Wikipedia also includes these pictures where is more evident that the distance is between the bodies:
![image](https://user-images.githubusercontent.com/26031501/168143210-a57de74e-7a9f-4bc7-aa8a-2d6de342bab9.png)

 @AgustinVallejo  said that is to the center of mass, just all the pages consider that the center of mass is in the massive body, and he will look for more information to write this text. 

This is the other option of text:
In a 2-body system in which objects follow an elliptical orbit, Apoapsis (from the Greek apo = away from) is the point of greatest separation of the bodies, and Periapsis(from the Greek peri = near) is the point of closest approach.

If one of the bodes is our Sun, the names change to Aphelion and Perihelion, and if the bodies are the Earth and the moon or other artificial satellites, the name change to Perigee and Apogee.

**Comment by DianaTavares** [comment]
After the discussion with some astronomers, we are going to use the definition related to the distance between the planets, then this is the text proposer:

`In a 2-body system in which objects follow an elliptical orbit, Apoapsis (from the Greek apo = away from) is the point of greatest separation between the bodies, and Periapsis(from the Greek peri = near) is the point of closest approach.

If one of the bodes is our Sun, the names change to Aphelion and Perihelion, and if the bodies are the Earth and the moon or other artificial satellites, the name change to Perigee and Apogee.` 

@ariel-phet, what do you think?

**Comment by ariel-phet** [comment]
@DianaTavares 

I am not sure it is necessary to put in the "from the Greek" examples -- especially if people translate these words, in some languages that might not make any sense. I would go with the following which includes some small changes:

> In a 2-body system in which each body follows an elliptical orbit, Apoapsis is the point of greatest separation between the bodies, and Periapsis is their point of closest approach.
> 
> If one of the bodes is our Sun, these terms change to Aphelion and Perihelion, and if the bodies are the Earth and the moon (or artificial satellites), the terms become Perigee and Apogee.
