### ISSUE TITLE
New position and size of the play panel 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#71]
During the last design meeting (December 15th), we agree to move the play panel and make it the same size for all screens. 

For the size, we are going to delete the "and" in the labs setting of `Sun, Plantet, Comet`,`Sun, Planet`, and  `Sun, Planet, Moon`. That changes in the strings will reduce the size of the controls' panel in that screen, and allow that all the right panel (controls, play, and Follow center of Mass button) in all the screens have the same size.  See next mockups as reference:

![image](https://user-images.githubusercontent.com/26031501/208790979-e707f37b-6a4d-41ff-9b69-c2c25adb40e0.png)

![image](https://user-images.githubusercontent.com/26031501/208791007-a3bf4dfd-a6f6-41bf-a053-8e9ba907af53.png)

Observe how in the Lab and intro screens, the mass control now is centered in the play area. Furthermore, in the Lab screen, the bodies control move to the right of the mass control. 

 Kepler Laws scenes:

Second law: this play control is different from the rest because it includes a “only reproduce one orbit” check box on the top of the play button. This checkbox will be active by default. 
![image](https://user-images.githubusercontent.com/26031501/209242530-fb183d58-9a5c-40b1-be0f-3598589f6e3f.png)

Third Law:
![image](https://user-images.githubusercontent.com/26031501/208791482-1ac569cd-0a2d-4944-9957-bd4f16516205.png)

**Comment by DianaTavares** [comment]
The time control has the next update in design: 
![image](https://user-images.githubusercontent.com/26031501/210670100-c954f6a9-6085-46be-bcb9-a7a150fdcaca.png)

The position of this control in each screen still the same that the first comment in this issue.

**Comment by AgustinVallejo** [comment]
These panels are now properly set :)
