### ISSUE TITLE
Kepler's Laws will be its own sim  

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#73]
This topic is very popular, then after My Solar System it is ready, think in how to have an own sim for Kepler's Laws. Some ideas:

- One screen per Law called: First, second and third Law. 
- First Law can be focused on understand what it is an eclipse with information about focuses and probably eccentricity.

**Comment by AgustinVallejo** [comment]
We split the sims succesfully! Here's the issue board for Kepler's Laws :)
https://github.com/phetsims/keplers-laws/issues
