### ISSUE TITLE
Kepler Law scene icons

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/my-solar-system#74]
These are the icons for the Kepler's law scenes:

First Law:
![MySolarSystem (2)-17](https://user-images.githubusercontent.com/26031501/209243788-9b969d10-3e1f-4a08-af37-5a9a8e143032.png)

Second Law: Similar to the screen icon for Kepler's Law, but with less area division.
![MySolarSystem (2)-18](https://user-images.githubusercontent.com/26031501/209243801-18b3338e-d079-456b-a288-4ce0ff622fa9.png)

Third Law:
![MySolarSystem (2)-19](https://user-images.githubusercontent.com/26031501/209243937-d9842439-a930-4470-b9fe-130a2f996197.png)

the position of the icons and how they looks when they are active/inactive is shown in the next picture:
![image](https://user-images.githubusercontent.com/26031501/209244063-d012c7e9-bce5-4203-930a-3b76ab116021.png)

**Comment by DianaTavares** [comment]
They look amazing! But now that we change the foci to blue in the scene, then I think that the icon need also be blue. Here is the picture with transparent background. 


![MySolarSystem (2)-16](https://user-images.githubusercontent.com/26031501/210899640-a8eb332f-0274-4330-825f-60c7f79589f1.png)

**Comment by AgustinVallejo** [comment]
Corrected!

**Comment by DianaTavares** [comment]
Perfect!!
