### ISSUE TITLE
mass2 cannot be 0

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#89]
CT is showing an error that I can reproduce with ?fuzzBoard. I traced it down and added an upstream assertion for clarity. Looks like a mass is getting set to 0, perhaps from the KeyboardFuzzer. I'll take a look.

**Comment by zepumph** [comment]
It is possible that https://github.com/phetsims/scenery/commit/a3720c89231e7928ed6bafabe0640abef4f1b7a9 fixed this, as fuzzing now is not showing it, but this was at least good to investigate a bit, it also caused me to work on https://github.com/phetsims/axon/issues/426#issuecomment-1460718066 to help catch these cases easier. I'll look at CT in a few rounds.

**Comment by zepumph** [comment]
I was able to hit this again. @AgustinVallejo what do you think about adding validation to the massProperty to say that it can't be set to 0? This may help us understand this problem.

https://github.com/phetsims/solar-system-common/blob/baf7cc196ec2f0813730576a2af072e6a055ca9f/js/model/Body.ts#L54

**Comment by AgustinVallejo** [comment]
This was being caused by the mass slider new buttons, should be fixed now!
