### ISSUE TITLE
Limit the number of digits allowed in the keypad

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#90]
A minor design thought, if the max allowed value for a keypad input is 300, then perhaps we should limit the keypad to entering 3 digits. This seems weird to me:

![image](https://user-images.githubusercontent.com/6856943/223828939-2c2ef922-e632-4f7c-b39a-305c6481c239.png)

Over to responsible dev @AgustinVallejo.

**Comment by samreid** [comment]
I'll take a look too.

**Comment by samreid** [comment]
I pushed a proposed fix, @AgustinVallejo can you please review?

**Comment by samreid** [comment]
Unfortunately that fix allows you to type 9999 since it has 4 digits.  Should we upgrade to a "value-aware" input limiter? Where you can type "." after 100 but not a digit?

**Comment by zepumph** [comment]
Yeah, it seems inherently challenging to not have complete control for the "leftOfMantissa". Not sure how to manage it, but I also don't think it is too big of a deal. 9999 seems ok, and much better than 8 digits.

**Comment by AgustinVallejo** [comment]
With @samreid, @arouinfar and @zepumph we decided that: 
- Based on the sim's usages, even though this might look kind of odd, it actually works as intended and it's probably not worth to polish even further. It could even be disruptive.
