### ISSUE TITLE
Fuzzing triggers errors in built versions

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#91]
Example:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/480878/223839809-4880721b-79cd-4dc8-8288-cba41f958cce.png">

**Comment by AgustinVallejo** [comment]
@zepumph could this be related to the AltInput additions?

**Comment by zepumph** [comment]
Not sure. I wouldn't be surprised if this was from something about the PDOM of DraggableVectorNode, but we will want to look into things.

**Comment by samreid** [comment]
I've been fuzzing in built versions for a while for https://github.com/phetsims/my-solar-system/issues/108 and have not seen this symptom.  Also have not seen it on CT.  Closing until it is seen again.
