### ISSUE TITLE
Negative distances not allowed

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#92]
Triggered this error during unbuilt fuzzing:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/480878/223849515-88d2a4aa-c258-4ae8-91b4-d992e0c7dd68.png">

**Comment by AgustinVallejo** [comment]
Potentially solved in https://github.com/phetsims/my-solar-system/issues/89 but will leave open for a while just in case

**Comment by samreid** [comment]
My Solar System has been clear on CT for many columns, so I suspect this has been fixed.  I'll close for now, but anyone feel free to reopen for any reason.
