### ISSUE TITLE
Updates to BasicActionsKeyboardHelpSection keyboard section for basic alt-input

### ISSUE THREAD

**Issue by zepumph** [phetsims/my-solar-system#93]
From alt input meeting today, and from #86.

@Matthew-Moore240 will take a first pass on it.

**Comment by zepumph** [comment]
An idea from the meeting. Add 2 more items to the "basic actions" section:

1. 2d dragging. "Navigate to the draggable and move the arrow keys to drag me!"
2. Keypad interaction "Type numbers, backspace, decimal, minus to use the keypad".

![image](https://user-images.githubusercontent.com/6856943/223863830-3c123938-b503-442a-a215-d99522a149dd.png)


Please provide for each row:

1. visual look of the row
2. described pdom content
3. placement of the row in the section.

**Comment by zepumph** [comment]
patch to add basic section to MSS:

<details>

```diff
Subject: [PATCH] translatable strings for hot key help content, https://github.com/phetsims/scenery-phet/issues/797
---
Index: js/lab/LabScreen.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/lab/LabScreen.ts b/js/lab/LabScreen.ts
--- a/js/lab/LabScreen.ts	(revision 68f366b3d1f9550b8c58c91dd3c699fdde8a94e2)
+++ b/js/lab/LabScreen.ts	(date 1678313569678)
@@ -14,6 +14,7 @@
 import LabScreenView from './view/LabScreenView.js';
 import LabScreenIcon from './view/LabScreenIcon.js';
 import MySolarSystemStrings from '../MySolarSystemStrings.js';
+import BasicActionsKeyboardHelpSection from '../../../scenery-phet/js/keyboard/help/BasicActionsKeyboardHelpSection.js';
 
 class LabScreen extends Screen<LabModel, LabScreenView> {
 
@@ -23,7 +24,10 @@
       homeScreenIcon: new LabScreenIcon(),
       backgroundColorProperty: SolarSystemCommonColors.backgroundProperty,
       tandem: tandem,
-      name: MySolarSystemStrings.screen.labStringProperty
+      name: MySolarSystemStrings.screen.labStringProperty,
+      createKeyboardHelpNode: () => {
+        return new BasicActionsKeyboardHelpSection( { withCheckboxContent: true } );
+      }
     };
 
     super(
Index: js/intro/IntroScreen.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/intro/IntroScreen.ts b/js/intro/IntroScreen.ts
--- a/js/intro/IntroScreen.ts	(revision 68f366b3d1f9550b8c58c91dd3c699fdde8a94e2)
+++ b/js/intro/IntroScreen.ts	(date 1678313433728)
@@ -14,6 +14,7 @@
 import IntroScreenView from './view/IntroScreenView.js';
 import IntroScreenIcon from './view/IntroScreenIcon.js';
 import MySolarSystemStrings from '../MySolarSystemStrings.js';
+import BasicActionsKeyboardHelpSection from '../../../scenery-phet/js/keyboard/help/BasicActionsKeyboardHelpSection.js';
 
 class IntroScreen extends Screen<IntroModel, IntroScreenView> {
 
@@ -23,7 +24,10 @@
       homeScreenIcon: new IntroScreenIcon(),
       backgroundColorProperty: SolarSystemCommonColors.backgroundProperty,
       tandem: tandem,
-      name: MySolarSystemStrings.screen.introStringProperty
+      name: MySolarSystemStrings.screen.introStringProperty,
+      createKeyboardHelpNode: () => {
+        return new BasicActionsKeyboardHelpSection( { withCheckboxContent: true } );
+      }
     };
 
     super(

**Comment by Matthew-Moore240** [comment]
Here are the new keyboard shortcuts along with the order they are in. @zepumph 

H2: Basic Actions
UL:
  LI: Move to next item or group with Tab key.
  LI: Move to previous item or group with Shift plus Tab key.
  LI: Move between items in a group with Left and Right arrow keys or Up and Down arrow keys.
  LI: Move draggable objects with Left and Right arrow keys or Up and Down arrow keys.
  LI: Set values within pop-up keypad using number keys 0-9.
  LI: Toggle checkboxes with Space key.
  LI: Press buttons with Space key.
  LI: Exit a dialog with Escape key.

**Comment by zepumph** [comment]
>Set values within pop-up keypad using number keys 0-9.

What if we got rid of the "pop-up". There are may keypads that are not popup, or at least not in the same way as a full, modal dialog.

**Comment by zepumph** [comment]
- [ ] It looks like we have lost the "reset all" row. Do you want that gone?

**Comment by zepumph** [comment]
Perhaps https://github.com/phetsims/scenery-phet/issues/800 is blocking My Solar System publication. Just noting here.

**Comment by zepumph** [comment]
Alright all done here. Please respond to the above two checkboxes

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/225194266-50b7a67d-c45c-484c-9651-8582fb54d2bb.png)

![image](https://user-images.githubusercontent.com/6856943/225194303-03e2f1b8-0969-4da4-80c6-a5b916b7da96.png)

**Comment by samreid** [comment]
API files are now showing `moveDraggableObjectsStringProperty` and `setValuesInKeypadStringProperty`. I'll commit the updated API files and reassign to @zepumph to review.

**Comment by Matthew-Moore240** [comment]
I am totally okay with getting rid of the "pop-up" in the help text. I am not totally sure what you mean by the second checkbox.

**Comment by zepumph** [comment]
pop-up removed above. If the placement of the "reset all" line is acceptable. @Matthew-Moore240 please feel free to close this issue:

![image](https://user-images.githubusercontent.com/6856943/225397278-741d2d72-f9be-4dcf-aa57-ddebc734016a.png)


![image](https://user-images.githubusercontent.com/6856943/225397331-8045e634-29f8-4eec-8699-662ea70ab5a1.png)

**Comment by zepumph** [comment]
From review today with @arouinfar:

- [ ] We will remove the draggable part from Basic section, and instead do https://github.com/phetsims/scenery-phet/issues/801
- [ ] Add TimeControlKeyboardHelpSection
- [ ] Add SliderControlsKeyboardHelpSectionOptions

Keep on using keypad in basic section

**Comment by zepumph** [comment]
Here is what my working copy currently looks like:

![image](https://user-images.githubusercontent.com/6856943/225997310-db66ca53-d8d5-4d26-90cf-a3edbe6f1498.png)
![image](https://user-images.githubusercontent.com/6856943/225997518-50821cda-b997-4471-aa53-757a3e788c87.png)


(it's always a bit ironic that my picture of the PDOM is not accessible here in github). @arouinfar does that seem right to you? What order are you imagining?

**Comment by zepumph** [comment]
Commits pushed

**Comment by arouinfar** [comment]
@zepumph the keyboard help dialog looks so good, thank you! Section order and PDOM content also look reasonable to me, so I think we're good to close.
