### ISSUE TITLE
mass2 should not be 0

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#94]
Assertion triggered while fuzzing unbuilt:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/480878/223873270-693f35d2-9326-4ca5-ae74-00fda545c63f.png">

**Comment by samreid** [comment]
Is this a duplicate of https://github.com/phetsims/my-solar-system/issues/89?

**Comment by AgustinVallejo** [comment]
It is! Thanks for pointing it out
