### ISSUE TITLE
Handle REVIEW comments in my-solar-system/solar-system-common

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/my-solar-system#95]
Creating an issue so it's easier to track.

**Comment by jonathanolson** [comment]
I believe I've completed adding notes, based on all of the changed commits since I last reviewed.

**Comment by samreid** [comment]
For unknown reasons, I tracked some of this work in https://github.com/phetsims/my-solar-system/issues/88

**Comment by samreid** [comment]
All REVIEW comments complete.  @AgustinVallejo can you please review?

**Comment by samreid** [comment]
I also moved one string utility to Kepler's Law since it was not used in Solar System Common or My Solar System.

**Comment by AgustinVallejo** [comment]
This is looking good, thanks again!
