### ISSUE TITLE
Code Review: Add model.md

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#96]
For https://github.com/phetsims/my-solar-system/issues/88

**Comment by jonathanolson** [comment]
Assign me once this is done for review (I'll also be available to help create it, if so that won't be needed)

**Comment by samreid** [comment]
@AgustinVallejo said this is ready for review. @jonathanolson can you please take a look?

**Comment by AgustinVallejo** [comment]
I believe this, along https://github.com/phetsims/my-solar-system/issues/97 are ready for review

**Comment by jonathanolson** [comment]
I think it would be good to put the Lab mode configurations into the model.md, so that people can see what coordinates they start with (without being rounded at all). Since we're setting them in "model" units, they would be getting rounded "view" units.

**Comment by jonathanolson** [comment]
Oops, actually, they're referenced! We'll need to not break that link.

**Comment by jonathanolson** [comment]
Made some changes above, can you review?

Additionally, I think it would be good to mention some things about collisions. Does it preserve momentum?

**Comment by jonathanolson** [comment]
Looks good, just the one item above!

**Comment by AgustinVallejo** [comment]
Added a big section with Physical Simplifications, to adress body sizes, mass scales, collisions, and how accurate is each pre-set with their real world counterparts. So another fast review would be nice.

**Comment by jonathanolson** [comment]
This is excellent!

My only question would be whether the "Distances and Sizes" and "Radii of Bodies" are really separate - they are both talking about the radii/size (same thing?), and might be combinable.

**Comment by AgustinVallejo** [comment]
I think they work good separately. Closing.
