### ISSUE TITLE
Code Review: add implementation-notes.md

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#97]
For https://github.com/phetsims/my-solar-system/issues/88

**Comment by jonathanolson** [comment]
Assign me once this is done for review (I'll also be available to help create it, if so that won't be needed)

**Comment by samreid** [comment]
I started on that file, but it could use more help.

**Comment by AgustinVallejo** [comment]
I believe this, as well as https://github.com/phetsims/my-solar-system/issues/96 are ready for review

**Comment by jonathanolson** [comment]
Looks good, can you review the above change (and if that's good, close?)

**Comment by AgustinVallejo** [comment]
It's good, closing. Thanks!
