### ISSUE TITLE
Code Review: Memory testing

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#98]
For https://github.com/phetsims/my-solar-system/issues/88

**Comment by jonathanolson** [comment]
Let's have this done for the next dev test, after or as part of QA (one published after the 9 memory fixes I made).

**Comment by samreid** [comment]
About a minute between snapshots in this test, looking very reasonable!

![image](https://user-images.githubusercontent.com/679486/224228559-dc4e7da6-3e8f-4380-9e36-4b918035ee3a.png)

Are there any other modes such as query parameters that require independent testing?

**Comment by AgustinVallejo** [comment]
There's only one query parameter, `cueingArrows=true`. I believe those are being properly disposed but might be useful to double check. Unless the version you tested had those on by default, in which case this is done.

**Comment by samreid** [comment]
Since BodyNode always creates and disposes the `CueingArrowsNode` it seems unlikely that `cueingArrows=true` could introduce a memory leak. I feel this issue could be closed.

**Comment by AgustinVallejo** [comment]
Thanks, closing now.
