### ISSUE TITLE
Code Review: Performance testing and sign-off

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/my-solar-system#99]
For https://github.com/phetsims/my-solar-system/issues/88

**Comment by jonathanolson** [comment]
Similarly to https://github.com/phetsims/my-solar-system/issues/98, this should be done off a fresh dev version, by QA.

**Comment by KatieWoe** [comment]
From the dev test:
>Chrome book performance looked ok. There were a few instances of brief lag, but not much, and nothing I would worry about.

**Comment by arouinfar** [comment]
Thanks @KatieWoe. Sounds like the performance was acceptable on performance-limited devices, so we can close.
